from typing import Tuple, Set, Iterable, List


class LinterExtensionDescriptor:
    def __init__(self, id: str, name: str): ...
    @property
    def Id(self) -> str: ...
    @property
    def Name(self) -> str: ...
    def Equals(self, obj: Object) -> bool: ...
    def GetHashCode(self) -> int: ...


class LinterManager(NotificationObject):
    def __init__(self, extensionManager: IExtensionManager): ...
    @property
    def AvailableLinters(self) -> HashSet: ...
    @property
    def ActiveLinter(self) -> LinterExtensionDescriptor: ...
    def SetActiveLinter(self, value: LinterExtensionDescriptor, fullActivation: bool) -> None: ...
    def Dispose(self) -> None: ...
