from typing import Tuple, Set, Iterable, List


class Document:
    @property
    def ActiveView(self) -> View: ...
    @property
    def IsFamilyDocument(self) -> bool: ...
    @property
    def FilePath(self) -> str: ...
    @property
    def Current() -> Document: ...
    @property
    def WorksharingPath(self) -> str: ...
    @property
    def IsCloudPath(self) -> bool: ...
    def PurgeUnused(self, fullPurge: bool) -> List: ...
    @property
    def Location(self) -> Location: ...
    def SaveFamilyToFolder(self, family: Family, directoryPath: str) -> str: ...
    def UnitTypeBySpecType(self, specType: ForgeType) -> Unit: ...
    def GetLinkInstances(self) -> List: ...


class FamilyDocument(Document):
    @property
    def Category(self) -> Category: ...
    @property
    def Parameters(self) -> List: ...
    @property
    def Types(self) -> List: ...
    def SetCategory(self, category: Category) -> FamilyDocument: ...
    def SetFormula(self, parameterName: str, formula: str) -> FamilyDocument: ...
    def GetFormula(self, parameterName: str) -> str: ...
    def GetParameterValueByName(self, familyTypeName: str, parameterName: str) -> Object: ...
    def SetParameterValueByName(self, familyTypeName: str, parameter: str, value: Object) -> FamilyDocument: ...
    def AddParameter(self, parameterName: str, groupType: GroupType, specType: SpecType, isInstance: bool) -> FamilyParameter: ...
    def DeleteParameter(self, parameterName: str) -> Int64: ...
    def ByDocument(document: Document) -> FamilyDocument: ...


class Warning:
    def GetWarningByGuid(guid: str) -> List: ...
    @property
    def Description(self) -> str: ...
    @property
    def Severity(self) -> str: ...
    def GetWarnings(document: Document) -> List: ...
    def GetFailingElements(self) -> List: ...
