from typing import Tuple, Set, Iterable, List


class TransactionManager:
    def add_OnLog(value: Action) -> None: ...
    def remove_OnLog(value: Action) -> None: ...
    @property
    def DisableTransactions(self) -> bool: ...
    @DisableTransactions.setter
    def DisableTransactions(self, value: bool) -> None: ...
    def add_DisableTransactionsChanged(self, value: EventHandler) -> None: ...
    def remove_DisableTransactionsChanged(self, value: EventHandler) -> None: ...
    @overload
    def SetupManager() -> None: ...
    @overload
    def SetupManager(strategy: ITransactionStrategy) -> None: ...
    @property
    def Instance() -> TransactionManager: ...
    @property
    def Strategy(self) -> ITransactionStrategy: ...
    @Strategy.setter
    def Strategy(self, value: ITransactionStrategy) -> None: ...
    @property
    def TransactionWrapper(self) -> TransactionWrapper: ...
    def EnsureInTransaction(self, document: Document) -> None: ...
    def TransactionTaskDone(self) -> None: ...
    def ForceCloseTransaction(self) -> None: ...
    @property
    def DoAssertInIdleThread(self) -> bool: ...
    @DoAssertInIdleThread.setter
    def DoAssertInIdleThread(self, value: bool) -> None: ...


class ITransactionStrategy:
    def EnsureInTransaction(self, wrapper: TransactionWrapper, document: Document) -> TransactionHandle: ...
    def TransactionTaskDone(self, handle: TransactionHandle) -> None: ...
    def ForceCloseTransaction(self, handle: TransactionHandle) -> None: ...


class DebugTransactionStrategy:
    def __init__(self): ...
    def EnsureInTransaction(self, wrapper: TransactionWrapper, document: Document) -> TransactionHandle: ...
    def TransactionTaskDone(self, handle: TransactionHandle) -> None: ...
    def ForceCloseTransaction(self, handle: TransactionHandle) -> None: ...


class AutomaticTransactionStrategy:
    def __init__(self): ...
    def EnsureInTransaction(self, wrapper: TransactionWrapper, document: Document) -> TransactionHandle: ...
    def TransactionTaskDone(self, handle: TransactionHandle) -> None: ...
    def ForceCloseTransaction(self, handle: TransactionHandle) -> None: ...


class TransactionWrapper:
    def add_FailuresRaised(self, value: FailureDelegate) -> None: ...
    def remove_FailuresRaised(self, value: FailureDelegate) -> None: ...
    def add_TransactionStarted(self, value: Action) -> None: ...
    def remove_TransactionStarted(self, value: Action) -> None: ...
    def add_TransactionCommitted(self, value: Action) -> None: ...
    def remove_TransactionCommitted(self, value: Action) -> None: ...
    def add_TransactionCancelled(self, value: Action) -> None: ...
    def remove_TransactionCancelled(self, value: Action) -> None: ...
    def StartTransaction(self, document: Document) -> TransactionHandle: ...
    @property
    def TransactionActive(self) -> bool: ...


class TransactionHandle:
    def CommitTransaction(self) -> TransactionStatus: ...
    def CancelTransaction(self) -> TransactionStatus: ...
    @property
    def Status(self) -> TransactionStatus: ...


class FailureDelegate:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, failures: FailuresAccessor) -> None: ...
    def BeginInvoke(self, failures: FailuresAccessor, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
