from typing import Tuple, Set, Iterable, List


class CodeBlockNodeSearchElement(NodeModelSearchElementBase):
    def __init__(self, data: TypeLoadData, manager: LibraryServices): ...


class CustomNodeSearchElement(NodeSearchElement):
    def __init__(self, customNodeManager: ICustomNodeSource, info: CustomNodeInfo): ...
    @property
    def ID(self) -> Guid: ...
    @property
    def CreationName(self) -> str: ...
    @property
    def Path(self) -> str: ...
    def SyncWithCustomNodeInfo(self, info: CustomNodeInfo) -> None: ...


class NodeModelSearchElement(NodeModelSearchElementBase):
    @property
    def CreationName(self) -> str: ...


class NodeModelSearchElementBase(NodeSearchElement):


class NodeSearchElement:
    @property
    def IsVisibleInSearch(self) -> bool: ...
    @IsVisibleInSearch.setter
    def IsVisibleInSearch(self, value: bool) -> None: ...
    @property
    def CreationName(self) -> str: ...
    @property
    def Categories(self) -> ICollection: ...
    @property
    def FullName(self) -> str: ...
    @property
    def FullCategoryName(self) -> str: ...
    @FullCategoryName.setter
    def FullCategoryName(self, value: str) -> None: ...
    @property
    def Name(self) -> str: ...
    @property
    def Parameters(self) -> str: ...
    @property
    def SearchKeywords(self) -> ICollection: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @property
    def IconName(self) -> str: ...
    @property
    def Group(self) -> SearchElementGroup: ...
    @Group.setter
    def Group(self, value: SearchElementGroup) -> None: ...
    @property
    def Assembly(self) -> str: ...
    @property
    def InputParameters(self) -> Iterable[Tuple]: ...
    @property
    def OutputParameters(self) -> Iterable[str]: ...
    @property
    def ElementType(self) -> ElementTypes: ...
    def add_ItemProduced(self, value: Action) -> None: ...
    def remove_ItemProduced(self, value: Action) -> None: ...
    def Clone(self) -> Object: ...


class AutoCompletionNodeMachineLearningInfo:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, displayIcon: bool, isByRecommendation: bool, confidenceScore: float): ...
    @property
    def DisplayIcon(self) -> bool: ...
    @DisplayIcon.setter
    def DisplayIcon(self, value: bool) -> None: ...
    @property
    def ConfidenceScore(self) -> float: ...
    @ConfidenceScore.setter
    def ConfidenceScore(self, value: float) -> None: ...
    @property
    def IsByUse(self) -> bool: ...
    @IsByUse.setter
    def IsByUse(self, value: bool) -> None: ...
    @property
    def IsByRecommendation(self) -> bool: ...
    @IsByRecommendation.setter
    def IsByRecommendation(self, value: bool) -> None: ...


class DragDropNodeSearchElementInfo:
    def __init__(self, searchElement: NodeSearchElement): ...
    @property
    def SearchElement(self) -> NodeSearchElement: ...


class SearchElementBase(BrowserInternalElement):
    @property
    def CreationName(self) -> str: ...
    @property
    def Searchable(self) -> bool: ...
    @property
    def Type(self) -> str: ...
    @property
    def Description(self) -> str: ...
    @property
    def Keywords(self) -> str: ...
    @Keywords.setter
    def Keywords(self, value: str) -> None: ...
    @property
    def Weight(self) -> float: ...
    @Weight.setter
    def Weight(self, value: float) -> None: ...


class SearchElementGroup:
    #None = 0
    Create = 1
    Action = 2
    Query = 3


class ElementTypes:
    #None = 0
    ZeroTouch = 1
    CustomNode = 2
    BuiltIn = 65536
    Packaged = 131072


class ZeroTouchSearchElement(NodeSearchElement):
    def __init__(self, functionDescriptor: FunctionDescriptor): ...
    @property
    def CreationName(self) -> str: ...
    @property
    def FullName(self) -> str: ...


class SearchElementHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, ele: SearchElementBase) -> None: ...
    def BeginInvoke(self, ele: SearchElementBase, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
