from typing import Tuple, Set, Iterable, List


class AnnotationModel(ModelBase):
    @overload
    def __init__(self, nodes: Iterable[NodeModel], notes: Iterable[NoteModel]): ...
    @overload
    def __init__(self, nodes: Iterable[NodeModel], notes: Iterable[NoteModel], groups: Iterable[AnnotationModel]): ...
    def add_ModelBaseRequested(self, value: Func) -> None: ...
    def remove_ModelBaseRequested(self, value: Func) -> None: ...
    @property
    def InitialTop(self) -> float: ...
    @InitialTop.setter
    def InitialTop(self, value: float) -> None: ...
    @property
    def InitialHeight(self) -> float: ...
    @InitialHeight.setter
    def InitialHeight(self, value: float) -> None: ...
    @property
    def DeletedModelBases(self) -> List: ...
    @DeletedModelBases.setter
    def DeletedModelBases(self, value: List) -> None: ...
    @property
    def loadFromXML(self) -> bool: ...
    @loadFromXML.setter
    def loadFromXML(self, value: bool) -> None: ...
    @property
    def Width(self) -> float: ...
    @Width.setter
    def Width(self, value: float) -> None: ...
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> None: ...
    @property
    def ModelAreaHeight(self) -> float: ...
    @ModelAreaHeight.setter
    def ModelAreaHeight(self, value: float) -> None: ...
    @property
    def Text(self) -> str: ...
    @Text.setter
    def Text(self, value: str) -> None: ...
    @property
    def AnnotationText(self) -> str: ...
    @AnnotationText.setter
    def AnnotationText(self, value: str) -> None: ...
    @property
    def AnnotationDescriptionText(self) -> str: ...
    @AnnotationDescriptionText.setter
    def AnnotationDescriptionText(self, value: str) -> None: ...
    @property
    def Background(self) -> str: ...
    @Background.setter
    def Background(self, value: str) -> None: ...
    @property
    def Nodes(self) -> Iterable[ModelBase]: ...
    @Nodes.setter
    def Nodes(self, value: Iterable[ModelBase]) -> None: ...
    @property
    def GUID(self) -> Guid: ...
    @GUID.setter
    def GUID(self, value: Guid) -> None: ...
    @property
    def Rect(self) -> Rect2D: ...
    @property
    def TextBlockHeight(self) -> float: ...
    @TextBlockHeight.setter
    def TextBlockHeight(self, value: float) -> None: ...
    @property
    def TextMaxWidth(self) -> float: ...
    @TextMaxWidth.setter
    def TextMaxWidth(self, value: float) -> None: ...
    @property
    def FontSize(self) -> float: ...
    @FontSize.setter
    def FontSize(self, value: float) -> None: ...
    @property
    def GroupStyleId(self) -> Guid: ...
    @GroupStyleId.setter
    def GroupStyleId(self, value: Guid) -> None: ...
    @property
    def PinnedNode(self) -> NodeModel: ...
    @PinnedNode.setter
    def PinnedNode(self, value: NodeModel) -> None: ...
    @property
    def WidthAdjustment(self) -> float: ...
    @WidthAdjustment.setter
    def WidthAdjustment(self, value: float) -> None: ...
    @property
    def HeightAdjustment(self) -> float: ...
    @HeightAdjustment.setter
    def HeightAdjustment(self, value: float) -> None: ...
    @property
    def IsExpanded(self) -> bool: ...
    @IsExpanded.setter
    def IsExpanded(self, value: bool) -> None: ...
    @property
    def GroupState(self) -> ElementState: ...
    @property
    def HasNestedGroups(self) -> bool: ...
    @property
    def IsVisible(self) -> bool: ...
    def Select(self) -> None: ...
    def Deselect(self) -> None: ...
    def ContainsModel(self, modelBase: ModelBase) -> bool: ...
    def Dispose(self) -> None: ...
