from typing import Tuple, Set, Iterable, List


class DisposeLogic:
    def __init__(self): ...
    @property
    def IsShuttingDown() -> bool: ...
    @IsShuttingDown.setter
    def IsShuttingDown(value: bool) -> None: ...
    @property
    def IsClosingHomeworkspace() -> bool: ...
    @IsClosingHomeworkspace.setter
    def IsClosingHomeworkspace(value: bool) -> None: ...


class ElementUtils:
    @overload
    def TryGetElement(document: Document, uniqueId: str) -> Tuple[bool, T]: ...
    @overload
    def TryGetElement(document: Document, id: ElementId) -> Tuple[bool, T]: ...
    def AllElementsOfType(document: Document) -> Iterable[Element]: ...


class RevitServicesUpdater:
    def add_ElementsAdded(self, value: ElementUpdateDelegate) -> None: ...
    def remove_ElementsAdded(self, value: ElementUpdateDelegate) -> None: ...
    def add_ElementAddedForID(self, value: ElementUpdateDelegateElementId) -> None: ...
    def remove_ElementAddedForID(self, value: ElementUpdateDelegateElementId) -> None: ...
    def add_ElementsModified(self, value: ElementUpdateDelegate) -> None: ...
    def remove_ElementsModified(self, value: ElementUpdateDelegate) -> None: ...
    def add_ElementsDeleted(self, value: ElementDeleteDelegate) -> None: ...
    def remove_ElementsDeleted(self, value: ElementDeleteDelegate) -> None: ...
    def add_ElementsUpdated(self, value: EventHandler) -> None: ...
    def remove_ElementsUpdated(self, value: EventHandler) -> None: ...
    def Initialize(updaters: Iterable[IUpdater]) -> None: ...
    @property
    def IsInitialized() -> bool: ...
    @property
    def Instance() -> RevitServicesUpdater: ...
    def DisposeInstance() -> None: ...
    def AddUpdater(self, updater: IUpdater) -> None: ...
    def RemoveUpdater(self, updater: IUpdater) -> None: ...
    @property
    def DocumentToWatch(self) -> Document: ...
    def RollBack(self, doc: Document, deleted: ICollection) -> None: ...
    def ApplicationDocumentChanged(self, sender: Object, args: DocumentChangedEventArgs) -> None: ...
    def UnRegisterAllChangeHooks(self) -> None: ...


class ElementUpdateEventArgs:
    def __init__(self, doc: Document, elements: Iterable[ElementId], transactions: Iterable[str], operation: UpdateType): ...
    def GetUniqueIds(self) -> Iterable[str]: ...
    @property
    def Elements(self) -> Iterable[ElementId]: ...
    @property
    def RevitDocument(self) -> Document: ...
    @property
    def Transactions(self) -> Iterable[str]: ...
    @property
    def Operation(self) -> UpdateType: ...


class ElementUpdateDelegate:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, updated: Iterable[str]) -> None: ...
    def BeginInvoke(self, updated: Iterable[str], callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class ElementUpdateDelegateElementId:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, document: Document, updated: Iterable[ElementId]) -> None: ...
    def BeginInvoke(self, document: Document, updated: Iterable[ElementId], callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class ElementDeleteDelegate:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, document: Document, deleted: Iterable[ElementId]) -> None: ...
    def BeginInvoke(self, document: Document, deleted: Iterable[ElementId], callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class UpdaterHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, sender: Object, args: UpdaterArgs) -> None: ...
    def BeginInvoke(self, sender: Object, args: UpdaterArgs, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class UpdaterArgs:
    def __init__(self, added: ICollection, modified: ICollection, deleted: ICollection): ...
    @property
    def Added(self) -> ICollection: ...
    @Added.setter
    def Added(self, value: ICollection) -> None: ...
    @property
    def Modified(self) -> ICollection: ...
    @Modified.setter
    def Modified(self, value: ICollection) -> None: ...
    @property
    def Deleted(self) -> ICollection: ...
    @Deleted.setter
    def Deleted(self, value: ICollection) -> None: ...


class ElementTypeSpecificUpdater:
    def add_Updated(self, value: UpdaterHandler) -> None: ...
    def remove_Updated(self, value: UpdaterHandler) -> None: ...
    def Execute(self, data: UpdaterData) -> None: ...
    def GetUpdaterId(self) -> UpdaterId: ...
    def GetChangePriority(self) -> ChangePriority: ...
    def GetUpdaterName(self) -> str: ...
    def GetAdditionalInformation(self) -> str: ...


class SunPathUpdater(ElementTypeSpecificUpdater):
    def __init__(self, id: AddInId): ...
    def Execute(self, data: UpdaterData) -> None: ...
    def GetUpdaterName(self) -> str: ...
    def GetAdditionalInformation(self) -> str: ...


class UpdateType:
    Added = 0
    Modified = 1
    Deleted = 2
