from typing import Tuple, Set, Iterable, List


class DefaultRenderPackageFactory:
    def __init__(self): ...
    @property
    def TessellationParameters(self) -> TessellationParameters: ...
    @TessellationParameters.setter
    def TessellationParameters(self, value: TessellationParameters) -> None: ...
    def CreateRenderPackage(self) -> IRenderPackage: ...


class DefaultRenderPackage:
    def __init__(self): ...
    def AddPointVertex(self, x: float, y: float, z: float) -> None: ...
    def AddPointVertexColor(self, red: Byte, green: Byte, blue: Byte, alpha: Byte) -> None: ...
    def AddTriangleVertex(self, x: float, y: float, z: float) -> None: ...
    def AddTriangleVertexNormal(self, x: float, y: float, z: float) -> None: ...
    def AddTriangleVertexUV(self, u: float, v: float) -> None: ...
    def AddTriangleVertexColor(self, red: Byte, green: Byte, blue: Byte, alpha: Byte) -> None: ...
    def AddLineStripVertex(self, x: float, y: float, z: float) -> None: ...
    def AddLineStripVertexCount(self, n: int) -> None: ...
    def AddLineStripVertexColor(self, red: Byte, green: Byte, blue: Byte, alpha: Byte) -> None: ...
    def ApplyPointVertexColors(self, colors: Set(Byte)) -> None: ...
    def ApplyLineVertexColors(self, colors: Set(Byte)) -> None: ...
    def ApplyMeshVertexColors(self, colors: Set(Byte)) -> None: ...
    def SetColors(self, colors: Set(Byte)) -> None: ...
    def Clear(self) -> None: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @property
    def IsSelected(self) -> bool: ...
    @IsSelected.setter
    def IsSelected(self, value: bool) -> None: ...
    @property
    def HasRenderingData(self) -> bool: ...
    @property
    def DisplayLabels(self) -> bool: ...
    @DisplayLabels.setter
    def DisplayLabels(self, value: bool) -> None: ...
    @property
    def RequiresPerVertexColoration(self) -> bool: ...
    @RequiresPerVertexColoration.setter
    def RequiresPerVertexColoration(self, value: bool) -> None: ...
    @property
    def PointVertexCount(self) -> int: ...
    @property
    def LineVertexCount(self) -> int: ...
    @property
    def MeshVertexCount(self) -> int: ...
    @property
    def LineStripVertexCounts(self) -> Iterable[int]: ...
    @property
    def LineStripVertices(self) -> Iterable[float]: ...
    @property
    def LineStripVertexColors(self) -> Iterable[Byte]: ...
    @property
    def LineStripIndices(self) -> Iterable[int]: ...
    @property
    def MeshVertices(self) -> Iterable[float]: ...
    @property
    def MeshVertexColors(self) -> Iterable[Byte]: ...
    @property
    def MeshIndices(self) -> Iterable[int]: ...
    @property
    def MeshNormals(self) -> Iterable[float]: ...
    @property
    def MeshTextureCoordinates(self) -> Iterable[float]: ...
    @property
    def PointVertices(self) -> Iterable[float]: ...
    @property
    def PointVertexColors(self) -> Iterable[Byte]: ...
    @property
    def PointIndices(self) -> Iterable[int]: ...
    @property
    def Colors(self) -> Iterable[Byte]: ...
    @property
    def ColorsStride(self) -> int: ...
    @ColorsStride.setter
    def ColorsStride(self, value: int) -> None: ...
    @property
    def PointVertexColorCount(self) -> int: ...
    @property
    def LineVertexColorCount(self) -> int: ...
    @property
    def MeshVertexColorCount(self) -> int: ...
    def UpdatePointVertexColorForRange(self, startIndex: int, endIndex: int, red: Byte, green: Byte, blue: Byte, alpha: Byte) -> None: ...
    def AppendPointVertexColorRange(self, colors: Set(Byte)) -> None: ...
    def UpdateLineVertexColorForRange(self, startIndex: int, endIndex: int, red: Byte, green: Byte, blue: Byte, alpha: Byte) -> None: ...
    def AppendLineVertexColorRange(self, colors: Set(Byte)) -> None: ...
    def UpdateMeshVertexColorForRange(self, startIndex: int, endIndex: int, red: Byte, green: Byte, blue: Byte, alpha: Byte) -> None: ...
    def AppendMeshVertexColorRange(self, colors: Set(Byte)) -> None: ...
    @property
    def TextureMapsList(self) -> List: ...
    @property
    def TextureMapsStrideList(self) -> List: ...
    @property
    def MeshVerticesRangesAssociatedWithTextureMaps(self) -> List: ...
    def AddTextureMapForMeshVerticesRange(self, startIndex: int, endIndex: int, textureMap: Set(Byte), stride: int) -> None: ...
    @property
    def AllowLegacyColorOperations(self) -> bool: ...
    @AllowLegacyColorOperations.setter
    def AllowLegacyColorOperations(self, value: bool) -> None: ...


class IRenderPackageFactory:
    @property
    def TessellationParameters(self) -> TessellationParameters: ...
    @TessellationParameters.setter
    def TessellationParameters(self, value: TessellationParameters) -> None: ...
    def CreateRenderPackage(self) -> IRenderPackage: ...




class RenderPackageCache:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, otherPackages: Iterable[IRenderPackage]): ...
    @property
    def Packages(self) -> Iterable[IRenderPackage]: ...
    def GetPortPackages(self, portId: Guid) -> RenderPackageCache: ...
    def IsEmpty(self) -> bool: ...
    @overload
    def Add(self, other: RenderPackageCache) -> None: ...
    @overload
    def Add(self, package: IRenderPackage) -> None: ...
    @overload
    def Add(self, package: IRenderPackage, outputPortId: Guid) -> None: ...
