from typing import Tuple, Set, Iterable, List


class LogLevel:
    Console = 0
    File = 1
    Warning = 2
    ConsoleOnly = 3


class WarningLevel:
    Mild = 0
    Moderate = 1
    Error = 2


class LogEventHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, args: LogEventArgs) -> None: ...
    def BeginInvoke(self, args: LogEventArgs, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class LogEventArgs:
    @overload
    def __init__(self, message: str, level: LogLevel): ...
    @overload
    def __init__(self, e: Exception, level: LogLevel): ...
    @property
    def Message(self) -> str: ...
    @Message.setter
    def Message(self, value: str) -> None: ...
    @property
    def Level(self) -> LogLevel: ...
    @Level.setter
    def Level(self, value: LogLevel) -> None: ...


class DynamoLogger(NotificationObject):
    def __init__(self, debugSettings: DebugSettings, logDirectory: str, isTestMode: bool, isCLIMode: bool, isServiceMode: bool): ...
    def add_NotificationLogged(self, value: Action) -> None: ...
    def remove_NotificationLogged(self, value: Action) -> None: ...
    @property
    def WarningLevel(self) -> WarningLevel: ...
    @WarningLevel.setter
    def WarningLevel(self, value: WarningLevel) -> None: ...
    @property
    def Warning(self) -> str: ...
    @Warning.setter
    def Warning(self, value: str) -> None: ...
    @property
    def LogPath(self) -> str: ...
    @property
    def LogText(self) -> str: ...
    @property
    def StartupNotifications(self) -> Iterable[NotificationMessage]: ...
    @overload
    def Log(self, message: str, level: LogLevel) -> None: ...
    def LogNotification(self, sender: str, title: str, shortMessage: str, detailedMessage: str) -> None: ...
    def LogWarning(self, message: str, level: WarningLevel) -> None: ...
    @overload
    def LogError(self, error: str) -> None: ...
    @overload
    def LogError(self, tag: str, error: str) -> None: ...
    def LogInfo(self, tag: str, info: str) -> None: ...
    def ClearStartupNotifications(self) -> None: ...
    @overload
    def Log(self, message: str) -> None: ...
    @overload
    def Log(self, e: Exception) -> None: ...
    @overload
    def Log(self, tag: str, data: str) -> None: ...
    def Dispose(self) -> None: ...


class ILogger:
    @overload
    def Log(self, message: str) -> None: ...
    @overload
    def Log(self, tag: str, message: str) -> None: ...
    def LogError(self, error: str) -> None: ...
    def LogWarning(self, warning: str, level: WarningLevel) -> None: ...
    @overload
    def Log(self, e: Exception) -> None: ...


class ILogMessage:
    def Log(self, logger: ILogger) -> None: ...


class ILogSource:
    def add_MessageLogged(self, value: Action) -> None: ...
    def remove_MessageLogged(self, value: Action) -> None: ...


class LogMessage:
    def Warning(message: str, severity: WarningLevel) -> ILogMessage: ...
    @overload
    def Error(message: str) -> ILogMessage: ...
    @overload
    def Error(exception: Exception) -> ILogMessage: ...
    def Info(message: str) -> ILogMessage: ...
    def Log(logger: ILogger, message: ILogMessage) -> None: ...


class LogSourceBase:
    def __init__(self): ...
    def add_MessageLogged(self, value: Action) -> None: ...
    def remove_MessageLogged(self, value: Action) -> None: ...
    def AsLogger(self) -> ILogger: ...


class NotificationMessage:
    def __init__(self, sender: str, shortMessage: str, detailedMessage: str, title: str): ...
    @property
    def Sender(self) -> str: ...
    @property
    def Title(self) -> str: ...
    @property
    def ShortMessage(self) -> str: ...
    @property
    def DetailedMessage(self) -> str: ...
