from typing import Tuple, Set, Iterable, List


class Resources:
    @property
    def ResourceManager() -> ResourceManager: ...
    @property
    def Culture() -> CultureInfo: ...
    @Culture.setter
    def Culture(value: CultureInfo) -> None: ...
    @property
    def ArggOKButton() -> str: ...
    @property
    def ArgumentNullException() -> str: ...
    @property
    def Autocomplete() -> str: ...
    @property
    def AutocompleteLowConfidenceMessage() -> str: ...
    @property
    def AutocompleteLowConfidenceTitle() -> str: ...
    @property
    def AutocompleteLowConfidenceTooltip() -> str: ...
    @property
    def AutocompleteNoRecommendationsMessage() -> str: ...
    @property
    def AutocompleteNoRecommendationsTitle() -> str: ...
    @property
    def AutocompleteSearchTextBlockText() -> str: ...
    @property
    def BackUpOriginalFileMessage() -> str: ...
    @property
    def BackupSavedMsg() -> str: ...
    @property
    def BadIdentifierSyntax() -> str: ...
    @property
    def BadRangeSyntax() -> str: ...
    @property
    def BuildSublistsDescription() -> str: ...
    @property
    def ButtonDownloadLastest() -> str: ...
    @property
    def ButtonProcess() -> str: ...
    @property
    def CancelButton() -> str: ...
    @property
    def CannotHave0Step() -> str: ...
    @property
    def CannotOpenFile() -> str: ...
    @property
    def ClearingWorkflow() -> str: ...
    @property
    def ClearingWorkSpace() -> str: ...
    @property
    def CodeBlockDescription() -> str: ...
    @property
    def CodeBlockNodeDescription() -> str: ...
    @property
    def CodeBlockSearchTags() -> str: ...
    @property
    def CodeBlockTempIdentifierOutputLabel() -> str: ...
    @property
    def ComposeFunctionNodeDescription() -> str: ...
    @property
    def ComposeFunctionPortDataFunctionToolTip() -> str: ...
    @property
    def ComposeFunctionPortDataResultToolTip() -> str: ...
    @property
    def CoreLibraryLoadFailureForBlockedAssembly() -> str: ...
    @property
    def CoreLibraryLoadFailureMessageBoxTitle() -> str: ...
    @property
    def CouldNotCompressFile() -> str: ...
    @property
    def CouldNotGetLatestBuild() -> str: ...
    @property
    def CouldNotGetUpdateData() -> str: ...
    @property
    def CouldNotLoadTypes() -> str: ...
    @property
    def CouldNotRepairOneNodeHoles() -> str: ...
    @property
    def CreatingConnectorError() -> str: ...
    @property
    def CustomNodeCouldNotBeInitialized() -> str: ...
    @property
    def CustomNodeDesciption() -> str: ...
    @property
    def CustomNodeFolderLoadFailure() -> str: ...
    @property
    def CustomNodeNotLoaded() -> str: ...
    @property
    def DefaultCustomNodeCategory() -> str: ...
    @property
    def DefaultHomeWorkspaceName() -> str: ...
    @property
    def DefaultValue() -> str: ...
    @property
    def DefaultValueDisabled() -> str: ...
    @property
    def DescriptionResource1() -> str: ...
    @property
    def DirectoryNotFound() -> str: ...
    @property
    def DisplayEngineFailureMessageDescription() -> str: ...
    @property
    def DllLoadException() -> str: ...
    @property
    def DownloadLatestButton() -> str: ...
    @property
    def DSFunctionNodeDescription() -> str: ...
    @property
    def DulicatedPackage() -> str: ...
    @property
    def DummyNodeDescription() -> str: ...
    @property
    def DuplicatedModelGuidError() -> str: ...
    @property
    def DuplicatedNewerPackage() -> str: ...
    @property
    def DuplicatedOlderPackage() -> str: ...
    @property
    def DuplicateMigrationTypeRegistered() -> str: ...
    @property
    def DynamoLanguages_noxlate() -> str: ...
    @property
    def DynamoUpToDate() -> str: ...
    @property
    def ElapsedWhenLoadingXml() -> str: ...
    @property
    def EvaluationCompleted() -> str: ...
    @property
    def ExceptionEncountered() -> str: ...
    @property
    def FailedInsertFileNodeExistNotification() -> str: ...
    @property
    def FailedToGetMirrorVariable() -> str: ...
    @property
    def FailedToHandleReadyEvent() -> str: ...
    @property
    def FailedToLoad() -> str: ...
    @property
    def FailedToLoadCustomNode() -> str: ...
    @property
    def FailedToLoadHeader() -> str: ...
    @property
    def FailedToLoadLibrary() -> str: ...
    @property
    def FailedToLoadType() -> str: ...
    @property
    def FailedToSave() -> str: ...
    @property
    def FileBackUpLocation() -> str: ...
    @property
    def FileCannotBeOpened() -> str: ...
    @property
    def FileLoadFailureMessageBoxTitle() -> str: ...
    @property
    def FileNotOpenedCorrectly() -> str: ...
    @property
    def FormulaDSConversionFailure() -> str: ...
    @property
    def FormulaMigrated() -> str: ...
    @property
    def FunctionDefinitionOverwrittenMessage() -> str: ...
    @property
    def FunctionDescription() -> str: ...
    @property
    def FunctionNodeDescription() -> str: ...
    @property
    def FutureFileDescription() -> str: ...
    @property
    def FutureFileSummary() -> str: ...
    @property
    def FutureFileTitle() -> str: ...
    @property
    def GoodByeLog() -> str: ...
    @property
    def GroupDefaultText() -> str: ...
    @property
    def GroupNameDefaultText() -> str: ...
    @property
    def GroupStyleDefaultActions() -> str: ...
    @property
    def GroupStyleDefaultActionsColor() -> str: ...
    @property
    def GroupStyleDefaultInputs() -> str: ...
    @property
    def GroupStyleDefaultInputsColor() -> str: ...
    @property
    def GroupStyleDefaultOutputs() -> str: ...
    @property
    def GroupStyleDefaultOutputsColor() -> str: ...
    @property
    def GroupStyleDefaultReview() -> str: ...
    @property
    def GroupStyleDefaultReviewColor() -> str: ...
    @property
    def HeaderAction() -> str: ...
    @property
    def HeaderCreate() -> str: ...
    @property
    def HeaderQuery() -> str: ...
    @property
    def IdentifiersNotFound() -> str: ...
    @property
    def IncompatibleOfFileAndDynamo() -> str: ...
    @property
    def IncorrectlyFormattedNodeLibraryDisplay() -> str: ...
    @property
    def IncorrectlyFormattedNodeLibraryWarning() -> str: ...
    @property
    def IncorrectVersionToOpenFile() -> str: ...
    @property
    def InputLabel() -> str: ...
    @property
    def InputNodeDescription() -> str: ...
    @property
    def InputNodeRenameHint() -> str: ...
    @property
    def InputNodeSearchTags() -> str: ...
    @property
    def InputPortAlternativeName() -> str: ...
    @property
    def InsertDialogBoxText() -> str: ...
    @property
    def InsertGraphRunModeNotificationText() -> str: ...
    @property
    def InvalidCustomNodeFolderWarning() -> str: ...
    @property
    def InvalidInputSymbolCustomNodeWarning() -> str: ...
    @property
    def InvalidInputSymbolErrorMessage() -> str: ...
    @property
    def InvalidInputSymbolWarningMessage() -> str: ...
    @property
    def InvalidInputSymbolWarningShortMessage() -> str: ...
    @property
    def InvalidInputSymbolWarningTitle() -> str: ...
    @property
    def InvalidLibraryFormat() -> str: ...
    @property
    def InvalidPackageVersion() -> str: ...
    @property
    def InvalidStartOrEndOfRange() -> str: ...
    @property
    def LegacyTraceDataWarning() -> str: ...
    @property
    def LibraryBuildError() -> str: ...
    @property
    def LibraryHasBeenLoaded() -> str: ...
    @property
    def LibraryIsDumped() -> str: ...
    @property
    def LibraryLoadFailureForBlockedAssembly() -> str: ...
    @property
    def LibraryLoadFailureMessageBoxTitle() -> str: ...
    @property
    def LibraryPathCannotBeFound() -> str: ...
    @property
    def LoadingNodeDefinition() -> str: ...
    @property
    def LocateInDisk() -> str: ...
    @property
    def LoginNeededMessage() -> str: ...
    @property
    def LoginNeededTitle() -> str: ...
    @property
    def MalformedHeaderPackage() -> str: ...
    @property
    def MessageCustomNodePackageFailedToLoad() -> str: ...
    @property
    def MissingXmlTagConsoleMessage() -> str: ...
    @property
    def ModelNotFoundError() -> str: ...
    @property
    def MoreButtonTextFormat() -> str: ...
    @property
    def MoveLabel() -> str: ...
    @property
    def NewNoteString() -> str: ...
    @property
    def NodeDeprecatedMsg() -> str: ...
    @property
    def NodeInformationalStateShowAllErrors() -> str: ...
    @property
    def NodeNotResolvedMsg() -> str: ...
    @property
    def NodeOfTypeDeprecatedMsg() -> str: ...
    @property
    def NodeOfTypeNotResolvedMsg() -> str: ...
    @property
    def NodeProblemEncountered() -> str: ...
    @property
    def NoDescriptionAvailable() -> str: ...
    @property
    def NodeUnhandledMsg() -> str: ...
    @property
    def NoHeaderPackage() -> str: ...
    @property
    def NoMatchesFound() -> str: ...
    @property
    def NoneLinterDescriptorName() -> str: ...
    @property
    def NoneString() -> str: ...
    @property
    def NothingIsSelectedWarning() -> str: ...
    @property
    def NumberNodeDescription() -> str: ...
    @property
    def ObsoleteFileDescription() -> str: ...
    @property
    def ObsoleteFileTitle() -> str: ...
    @property
    def OKButton() -> str: ...
    @property
    def OpeningHomeWorkspace() -> str: ...
    @property
    def OpenWorkbenchError() -> str: ...
    @property
    def OpenWorkspaceError() -> str: ...
    @property
    def OutputLabel() -> str: ...
    @property
    def OutputNodeDescription() -> str: ...
    @property
    def OutputPortAlternativeName() -> str: ...
    @property
    def PackageEmpty() -> str: ...
    @property
    def PackageLoadFailureForBlockedAssembly() -> str: ...
    @property
    def PackageManagerPackageAlreadyExists() -> str: ...
    @property
    def PackageManagerPackagePreviewCounter() -> str: ...
    @property
    def PackageManagerPackageSelectCounter() -> str: ...
    @property
    def PackageManagerUserIsNotAMaintainer() -> str: ...
    @property
    def PackageStateError() -> str: ...
    @property
    def PackageStateErrorTooltip() -> str: ...
    @property
    def PackageStateLoaded() -> str: ...
    @property
    def PackageStateLoadedTooltip() -> str: ...
    @property
    def PackageStatePendingUnload() -> str: ...
    @property
    def PackageStatePendingUnloadTooltip() -> str: ...
    @property
    def PackageStateUnloaded() -> str: ...
    @property
    def PackageStateUnloadedTooltip() -> str: ...
    @property
    def PackageTooLarge() -> str: ...
    @property
    def PathNotRegconizableAsStableOrDailyBuild() -> str: ...
    @property
    def PortDataFunctionOutputToolTip() -> str: ...
    @property
    def PortDataInputToolTip() -> str: ...
    @property
    def PortDataOutputToolTip() -> str: ...
    @property
    def PortDataParameterToolTip() -> str: ...
    @property
    def PortDataPathToFileToolTip() -> str: ...
    @property
    def PortDataReturnValueToolTip() -> str: ...
    @property
    def PortDataSymbolToolTip() -> str: ...
    @property
    def PortDataVariableToolTip() -> str: ...
    @property
    def PortsNameDescriptionDoNotEqualWarningMessage() -> str: ...
    @property
    def Preview3DOutageTitle() -> str: ...
    @property
    def ProceedButton() -> str: ...
    @property
    def PythonTemplateAppData() -> str: ...
    @property
    def PythonTemplateDefaultFile() -> str: ...
    @property
    def PythonTemplateDefinedByHost() -> str: ...
    @property
    def PythonTemplateUserFile() -> str: ...
    @property
    def RangeEndCouldNotBeParsed() -> str: ...
    @property
    def RangeOrApprIdentifierAlrUsed() -> str: ...
    @property
    def RangePortDataAmountToolTip() -> str: ...
    @property
    def RangePortDataEndToolTip() -> str: ...
    @property
    def RangePortDataSeqToolTip() -> str: ...
    @property
    def RangePortDataStartToolTip() -> str: ...
    @property
    def RangePortDataStepToolTip() -> str: ...
    @property
    def RangeStepCouldNotBeParsed() -> str: ...
    @property
    def RangeValuesGreaterThanZero() -> str: ...
    @property
    def RemoveLabel() -> str: ...
    @property
    def RequestingVersionUpdate() -> str: ...
    @property
    def ResourcePropertyIsNotStringTypeMessage() -> str: ...
    @property
    def ResourceTypeDoesNotHavePropertyMessage() -> str: ...
    @property
    def RunTypeToolTipAutomatically() -> str: ...
    @property
    def RunTypeToolTipManually() -> str: ...
    @property
    def RunTypeToolTipPeriodicallyDisabled() -> str: ...
    @property
    def RunTypeToolTipPeriodicallyEnabled() -> str: ...
    @property
    def SavingInProgress() -> str: ...
    @property
    def SearchTextBlockText() -> str: ...
    @property
    def SplashScreenInitPreferencesSettings() -> str: ...
    @property
    def SplashScreenLoadNodeLibrary() -> str: ...
    @property
    def StringNodeDescription() -> str: ...
    @property
    def SublistPortDataResultToolTip() -> str: ...
    @property
    def SublistsPortDataListToolTip() -> str: ...
    @property
    def SublistsPortDataOffsetToolTip() -> str: ...
    @property
    def SubmitBugButton() -> str: ...
    @property
    def SubmitBugToGithub() -> str: ...
    @property
    def SymbolNodeDescription() -> str: ...
    @property
    def SymbolSearchTags() -> str: ...
    @property
    def ToolTipForTempVar() -> str: ...
    @property
    def ToolTipFunctionOutput() -> str: ...
    @property
    def ToolTipInput() -> str: ...
    @property
    def ToolTipInputData() -> str: ...
    @property
    def ToolTipOutput() -> str: ...
    @property
    def ToolTipOutputData() -> str: ...
    @property
    def ToolTipReturnValue() -> str: ...
    @property
    def TopResult() -> str: ...
    @property
    def UnableToCreateCustomNodeID() -> str: ...
    @property
    def UnhandledExceptionInDynamoEngine() -> str: ...
    @property
    def UnhandledExceptionSummary() -> str: ...
    @property
    def UnhandledExceptionTitle() -> str: ...
    @property
    def UnknownVersion() -> str: ...
    @property
    def UnresolvedNodesWarningMessage() -> str: ...
    @property
    def UnresolvedNodesWarningShortMessage() -> str: ...
    @property
    def UnresolvedNodesWarningTitle() -> str: ...
    @property
    def UpdateAvailable() -> str: ...
    @property
    def UpdateDownloadComplete() -> str: ...
    @property
    def UpdateDownloadProgress() -> str: ...
    @property
    def UpdateDownloadStarted() -> str: ...
    @property
    def UsageReportingErrorMessage() -> str: ...
    @property
    def WarningCannotFindType() -> str: ...
    @property
    def WarningInvalidInput() -> str: ...
    @property
    def WarningInvalidOutput() -> str: ...
    @property
    def WatermarkLabelText() -> str: ...
    @property
    def WelcomeMessage() -> str: ...
    @property
    def WorkbenchNotOpen() -> str: ...
