from typing import Tuple, Set, Iterable, List


class IExecutionSession:
    @property
    def CurrentWorkspacePath(self) -> str: ...
    def GetParameterValue(self, parameter: str) -> Object: ...
    def GetParameterKeys(self) -> Iterable[str]: ...
    def ResolveFilePath(self, filepath: str) -> Tuple[bool, str]: ...


class ParameterKeys:
    def __init__(self): ...
