from typing import Tuple, Set, Iterable, List


class CurveUtils:
    def ReferencePointsAreSame(pnt1: ReferencePoint, pnt2: ReferencePoint) -> bool: ...
    def PointArraysAreSame(pnts1: ReferencePointArray, pnts2: ReferencePointArray) -> bool: ...
    def GetPlaneFromCurve(c: Curve, planarOnly: bool) -> Plane: ...
    def IsLineLike(crv: Curve) -> bool: ...
    def CurvesAreSimilar(a: Curve, b: Curve) -> bool: ...


class DynamoToRevitBRep:
    @overload
    def ToRevitType(sol: Solid, performHostUnitConversion: bool, materialId: ElementId) -> GeometryObject: ...
    @overload
    def ToRevitType(surf: Surface, performHostUnitConversion: bool, materialId: ElementId) -> GeometryObject: ...


class GeometryObjectConverter:
    def Convert(geom: GeometryObject, reference: Reference, transform: CoordinateSystem) -> Object: ...
    def ConvertToMany(solid: Solid, reference: Reference, transform: CoordinateSystem) -> Iterable[Object]: ...
    def InternalConvert(geom: PolyLine) -> PolyCurve: ...


class GeometryPrimitiveConverter:
    def ToRevitBoundingBox(cs: CoordinateSystem, minPoint: Point, maxPoint: Point, convertUnits: bool) -> BoundingBoxXYZ: ...
    @overload
    def ToRevitType(bb: BoundingBox, convertUnits: bool) -> BoundingBoxXYZ: ...
    @overload
    def ToRevitType(pt: Point, convertUnits: bool) -> XYZ: ...
    @overload
    def ToRevitType(vec: Vector, convertUnits: bool) -> XYZ: ...
    @overload
    def ToXyz(pt: Point, convertUnits: bool) -> XYZ: ...
    @overload
    def ToXyz(vec: Vector, convertUnits: bool) -> XYZ: ...
    def ToTransform(cs: CoordinateSystem, convertUnits: bool) -> Transform: ...
    @overload
    def ToPlane(plane: Plane, convertUnits: bool) -> Plane: ...
    @overload
    def ToXyzs(list: List, convertUnits: bool) -> List: ...
    @overload
    def ToXyzs(list: Set(Point), convertUnits: bool) -> Set(XYZ): ...
    @overload
    def ToXyzs(list: Set(Vector), convertUnits: bool) -> Set(XYZ): ...
    def ToDoubleArray(list: Set(float)) -> DoubleArray: ...
    @overload
    def ToProtoType(xyz: BoundingBoxXYZ, convertUnits: bool) -> BoundingBox: ...
    def ToPoint(xyz: XYZ, convertUnits: bool) -> Point: ...
    @overload
    def ToProtoType(point: Point, convertUnits: bool) -> Point: ...
    def ToVector(xyz: XYZ, convertUnits: bool) -> Vector: ...
    @overload
    def ToProtoType(uv: UV) -> UV: ...
    @overload
    def ToPlane(plane: Plane, convertUnits: bool) -> Plane: ...
    def ToCoordinateSystem(t: Transform, convertUnits: bool) -> CoordinateSystem: ...
    def ToPoints(list: List, convertUnits: bool) -> List: ...
    def ToRadians(degrees: float) -> float: ...
    def ToDegrees(degrees: float) -> float: ...
    @overload
    def GetPerpendicular(xyz: XYZ) -> XYZ: ...
    @overload
    def GetPerpendicular(vector: Vector) -> Vector: ...


class NurbsUtils:
    def ElevateBezierDegree(crv: NurbsCurve, finalDegree: int) -> NurbsCurve: ...


class PolygonContainment:
    def GetQuadrant(vertex: UV, p: UV) -> int: ...
    def GetXIntercept(p: UV, q: UV, y: float) -> float: ...
    def AdjustDelta(delta: int, vertex: UV, next_vertex: UV, p: UV) -> Tuple[int]: ...
    def PolygonContains(polygon: List, point: UV) -> bool: ...


class ProtoToRevitCurve:
    @overload
    def ToRevitType(crv: Curve, performHostUnitConversion: bool) -> Curve: ...
    @overload
    def ToRevitType(pcrv: PolyCurve, performHostUnitConversion: bool) -> CurveLoop: ...


class ProtoToRevitMesh:
    @overload
    def ToRevitType(srf: Surface, target: TessellatedShapeBuilderTarget, fallback: TessellatedShapeBuilderFallback, MaterialId: ElementId, performHostUnitConversion: bool) -> List[GeometryObject]: ...
    @overload
    def ToRevitType(solid: Solid, target: TessellatedShapeBuilderTarget, fallback: TessellatedShapeBuilderFallback, MaterialId: ElementId, performHostUnitConversion: bool) -> List[GeometryObject]: ...
    @overload
    def ToRevitType(mesh: Mesh, target: TessellatedShapeBuilderTarget, fallback: TessellatedShapeBuilderFallback, MaterialId: ElementId, performHostUnitConversion: bool) -> List[GeometryObject]: ...
    def CreateBoundingBoxMeshForErrors(minPoint: Point, maxPoint: Point, performHostUnitConversion: bool) -> List[GeometryObject]: ...


class ProtoToRevitSolid:
    def ToRevitFamilyType(solidGeometry: Solid, name: str, category: Category, templatePath: str, material: Material, isVoid: bool, subcategory: str) -> FamilySymbol: ...


class FamilyImportOptions:
    def __init__(self): ...
    def OnFamilyFound(self, familyInUse: bool) -> Tuple[bool, bool]: ...
    def OnSharedFamilyFound(self, sharedFamily: Family, familyInUse: bool) -> Tuple[bool, FamilySource, bool]: ...


class RevitToProtoCurve:
    @overload
    def ToProtoType(revitCurve: Curve, performHostUnitConversion: bool, referenceOverride: Reference) -> Curve: ...
    @overload
    def ToProtoType(revitCurves: CurveArray, performHostUnitConversion: bool) -> PolyCurve: ...
    @overload
    def ToProtoType(geom: PolyLine, performHostUnitConversion: bool) -> PolyCurve: ...


class RevitToProtoFace:
    def ToProtoType(revitFace: Face, performHostUnitConversion: bool, referenceOverride: Reference) -> Iterable[Surface]: ...


class RevitToProtoMesh:
    @overload
    def ToProtoType(mesh: Mesh, performHostUnitConversion: bool) -> Mesh: ...
    @overload
    def ToProtoType(meshArray: Iterable[Mesh], performHostUnitConversion: bool) -> Set(Mesh): ...


class RevitToProtoSolid:
    def ToProtoType(solid: Solid, performHostUnitConversion: bool) -> Solid: ...


class SurfaceExtractor:
    @overload
    def ExtractSurface(face: PlanarFace, edgeLoops: Iterable[PolyCurve]) -> Surface: ...
    @overload
    def ExtractSurface(face: CylindricalFace, edgeLoops: Iterable[PolyCurve]) -> Surface: ...
    @overload
    def ExtractSurface(face: ConicalFace, edgeLoops: Iterable[PolyCurve]) -> Surface: ...
    @overload
    def ExtractSurface(face: HermiteFace, edgeLoops: Iterable[PolyCurve]) -> Surface: ...
    @overload
    def ExtractSurface(face: RevolvedFace, edgeLoops: Iterable[PolyCurve]) -> Surface: ...
    @overload
    def ExtractSurface(face: RuledFace, edgeLoops: Iterable[PolyCurve]) -> Surface: ...


class UnitConverter:
    def DynamoToHostFactor(specTypeId: ForgeTypeId) -> float: ...
    def ConvertRevitInternalUnitTypeIdToSupportedUnitTypeId(forgeTypeId: ForgeTypeId) -> ForgeTypeId: ...
    def HostToDynamoFactor(specTypeId: ForgeTypeId) -> float: ...
    def InDynamoUnits(geometry: T) -> T: ...
    def InHostUnits(geometry: T) -> T: ...
    def ConvertToDynamoUnits(geometry: T) -> Tuple[T]: ...
    def ConvertToHostUnits(geometry: T) -> Tuple[T]: ...
