from typing import Tuple, Set, Iterable, List


class ScopeSetAction:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, name: str, value: Object) -> None: ...
    def BeginInvoke(self, name: str, value: Object, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class ScopeGetAction:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, name: str) -> Object: ...
    def BeginInvoke(self, name: str, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> Object: ...


class EvaluationStartedEventHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, code: str, bindingValues: IList, scopeSet: ScopeSetAction) -> None: ...
    def BeginInvoke(self, code: str, bindingValues: IList, scopeSet: ScopeSetAction, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class EvaluationFinishedEventHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, state: EvaluationState, code: str, bindingValues: IList, scopeGet: ScopeGetAction) -> None: ...
    def BeginInvoke(self, state: EvaluationState, code: str, bindingValues: IList, scopeGet: ScopeGetAction, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
