from typing import Tuple, Set, Iterable, List


class SpmPrimitiveIdPair:
    @overload
    def __init__(self, spatialFieldManagerID: Int64, primitiveIds: List): ...
    @overload
    def __init__(self): ...
    @property
    def SpatialFieldManagerID(self) -> Int64: ...
    @SpatialFieldManagerID.setter
    def SpatialFieldManagerID(self, value: Int64) -> None: ...
    @property
    def PrimitiveIds(self) -> List: ...
    @PrimitiveIds.setter
    def PrimitiveIds(self, value: List) -> None: ...


class SpmRefPrimitiveIdListPair:
    @overload
    def __init__(self, spatialFieldManagerID: Int64, refIdPairs: Dictionary): ...
    @overload
    def __init__(self): ...
    @property
    def SpatialFieldManagerID(self) -> Int64: ...
    @SpatialFieldManagerID.setter
    def SpatialFieldManagerID(self, value: Int64) -> None: ...
    @property
    def RefIdPairs(self) -> Dictionary: ...
    @RefIdPairs.setter
    def RefIdPairs(self, value: Dictionary) -> None: ...


class AbstractAnalysisDisplay:


class FaceAnalysisDisplay(AbstractAnalysisDisplay):
    def ByViewFacePointsAndValues(view: View, surface: Surface, sampleLocations: Set(UV), samples: Set(float), name: str, description: str, unitType: Type) -> FaceAnalysisDisplay: ...
    def ByViewAndFaceAnalysisData(view: View, data: SurfaceData, name: str, description: str, unitType: Type) -> FaceAnalysisDisplay: ...


class PointAnalysisDisplay(AbstractAnalysisDisplay):
    def ByViewPointsAndValues(view: View, sampleLocations: Set(Point), samples: Set(float), name: str, description: str, unitType: Type) -> PointAnalysisDisplay: ...
    def ByViewAndPointAnalysisData(view: View, data: PointData, name: str, description: str, unitType: Type) -> PointAnalysisDisplay: ...


class VectorAnalysisDisplay(AbstractAnalysisDisplay):
    def ByViewPointsAndVectorValues(view: View, sampleLocations: Set(Point), samples: Set(Vector), name: str, description: str, unitType: Type) -> VectorAnalysisDisplay: ...
    def ByViewAndVectorAnalysisData(view: View, data: VectorData, name: str, description: str, unitType: Type) -> VectorAnalysisDisplay: ...
