from typing import Tuple, Set, Iterable, List


class BrowserInternalElement(BrowserItem):
    @property
    def Items(self) -> ObservableCollection: ...
    @Items.setter
    def Items(self, value: ObservableCollection) -> None: ...
    @property
    def Siblings(self) -> ObservableCollection: ...
    @property
    def Parent(self) -> BrowserItem: ...
    @Parent.setter
    def Parent(self, value: BrowserItem) -> None: ...
    @property
    def OldParent(self) -> BrowserItem: ...
    @OldParent.setter
    def OldParent(self, value: BrowserItem) -> None: ...
    @property
    def UIParent(self) -> Object: ...
    @UIParent.setter
    def UIParent(self, value: Object) -> None: ...
    @property
    def Name(self) -> str: ...
    @property
    def FullCategoryName(self) -> str: ...
    @FullCategoryName.setter
    def FullCategoryName(self, value: str) -> None: ...


class BrowserItem(NotificationObject):
    @property
    def Items(self) -> ObservableCollection: ...
    @Items.setter
    def Items(self, value: ObservableCollection) -> None: ...
    @property
    def Name(self) -> str: ...
    @property
    def Height(self) -> int: ...
    @Height.setter
    def Height(self, value: int) -> None: ...
    @property
    def Visibility(self) -> bool: ...
    @Visibility.setter
    def Visibility(self, value: bool) -> None: ...
    @property
    def IsSelected(self) -> bool: ...
    @IsSelected.setter
    def IsSelected(self, value: bool) -> None: ...
    @property
    def IsExpanded(self) -> bool: ...
    @IsExpanded.setter
    def IsExpanded(self, value: bool) -> None: ...
    def add_Executed(self, value: BrowserItemHandler) -> None: ...
    def remove_Executed(self, value: BrowserItemHandler) -> None: ...






class ISearchEntry:
    @property
    def Name(self) -> str: ...
    @property
    def SearchTags(self) -> ICollection: ...
    @property
    def SearchTagWeights(self) -> Iterable[float]: ...
    @property
    def Description(self) -> str: ...




class LuceneSearch:
    def __init__(self): ...
    @property
    def Instance() -> LuceneSearch: ...


class NodeSearchModel:




class SearchCategoryUtil:


class BrowserItemHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, ele: BrowserItem) -> None: ...
    def BeginInvoke(self, ele: BrowserItem, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
