from typing import Tuple, Set, Iterable, List


class NodeModelAssemblyLoader(LogSourceBase):
    def __init__(self): ...
    @property
    def LoadedAssemblies(self) -> Iterable[Assembly]: ...
    def add_AssemblyLoaded(self, value: AssemblyLoadedHandler) -> None: ...
    def remove_AssemblyLoaded(self, value: AssemblyLoadedHandler) -> None: ...


class DynamoPreferencesData:
    def __init__(self, scaleFactor: float, hasRunWithoutCrash: bool, isVisibleInDynamoLibrary: bool, version: str, runType: str, runPeriod: str): ...
    @property
    def ScaleFactor(self) -> float: ...
    @property
    def HasRunWithoutCrash(self) -> bool: ...
    @property
    def IsVisibleInDynamoLibrary(self) -> bool: ...
    @property
    def Version(self) -> str: ...
    @property
    def RunType(self) -> str: ...
    @property
    def RunPeriod(self) -> str: ...
    def Default() -> DynamoPreferencesData: ...


class HostAnalyticsInfo:


class IEngineControllerManager:
    @property
    def EngineController(self) -> EngineController: ...


class DynamoModel:
    @property
    def IsTestMode() -> bool: ...
    @IsTestMode.setter
    def IsTestMode(value: bool) -> None: ...
    @property
    def IsHeadless() -> bool: ...
    @IsHeadless.setter
    def IsHeadless(value: bool) -> None: ...
    @property
    def IsCrashing() -> bool: ...
    @IsCrashing.setter
    def IsCrashing(value: bool) -> None: ...
    @property
    def EnableMigrationLogging() -> bool: ...
    @EnableMigrationLogging.setter
    def EnableMigrationLogging(value: bool) -> None: ...
    @property
    def EngineController(self) -> EngineController: ...
    @EngineController.setter
    def EngineController(self, value: EngineController) -> None: ...
    @property
    def ShutdownRequested(self) -> bool: ...
    @property
    def Version() -> str: ...
    @property
    def HostVersion(self) -> str: ...
    @HostVersion.setter
    def HostVersion(self, value: str) -> None: ...
    @property
    def HostAnalyticsInfo() -> HostAnalyticsInfo: ...
    @HostAnalyticsInfo.setter
    def HostAnalyticsInfo(value: HostAnalyticsInfo) -> None: ...
    @property
    def PathManager(self) -> IPathManager: ...
    @property
    def ExtensionManager(self) -> IExtensionManager: ...
    @property
    def LinterManager(self) -> LinterManager: ...
    @property
    def Scheduler(self) -> DynamoScheduler: ...
    @property
    def PreferenceSettings(self) -> PreferenceSettings: ...
    @property
    def CurrentWorkspace(self) -> WorkspaceModel: ...
    @CurrentWorkspace.setter
    def CurrentWorkspace(self, value: WorkspaceModel) -> None: ...
    @property
    def ClipBoard(self) -> ObservableCollection: ...
    @ClipBoard.setter
    def ClipBoard(self, value: ObservableCollection) -> None: ...
    @property
    def IsShowingConnectors(self) -> bool: ...
    @IsShowingConnectors.setter
    def IsShowingConnectors(self, value: bool) -> None: ...
    @property
    def IsShowingConnectorTooltip(self) -> bool: ...
    @IsShowingConnectorTooltip.setter
    def IsShowingConnectorTooltip(self, value: bool) -> None: ...
    @property
    def ConnectorType(self) -> ConnectorType: ...
    @ConnectorType.setter
    def ConnectorType(self, value: ConnectorType) -> None: ...
    @property
    def Workspaces(self) -> Iterable[WorkspaceModel]: ...
    @property
    def TraceReconciliationProcessor(self) -> ITraceReconciliationProcessor: ...
    @TraceReconciliationProcessor.setter
    def TraceReconciliationProcessor(self, value: ITraceReconciliationProcessor) -> None: ...
    @property
    def AuthenticationManager(self) -> AuthenticationManager: ...
    @AuthenticationManager.setter
    def AuthenticationManager(self, value: AuthenticationManager) -> None: ...
    def ShutDown(self, shutdownHost: bool) -> None: ...
    @property
    def State(self) -> DynamoModelState: ...
    @property
    def CLIMode(self) -> bool: ...
    @property
    def CERLocation(self) -> str: ...
    @overload
    def Start() -> DynamoModel: ...
    @overload
    def Start(configuration: IStartConfiguration) -> DynamoModel: ...
    def AddPackagePath(self, path: str, file: str) -> bool: ...
    def PostTraceReconciliation(self, orphanedSerializables: Dictionary) -> None: ...
    def Dispose(self) -> None: ...
    def ResetEngine(self, markNodesAsDirty: bool) -> None: ...
    def ForceRun(self) -> None: ...
    def OpenFileFromJson(self, fileContents: str, forceManualExecutionMode: bool) -> None: ...
    def OpenFileFromPath(self, filePath: str, forceManualExecutionMode: bool) -> None: ...
    def OpenTemplateFromPath(self, filePath: str, forceManualExecutionMode: bool) -> None: ...
    def InsertFileFromPath(self, filePath: str, forceManualExecutionMode: bool) -> None: ...
    def SetUICulture(locale: str) -> None: ...
    def AddHomeWorkspace(self) -> None: ...
    def AddCustomNodeWorkspace(self, workspace: CustomNodeWorkspaceModel) -> None: ...
    def RemoveWorkspace(self, workspace: WorkspaceModel) -> None: ...
    def OpenCustomNodeWorkspace(self, guid: Guid) -> bool: ...
    def Copy(self) -> None: ...
    @overload
    def Paste(self) -> None: ...
    @overload
    def Paste(self, targetPoint: Point2D, useOffset: bool) -> None: ...
    def AddToSelection(self, parameters: Object) -> None: ...
    def ClearCurrentWorkspace(self) -> None: ...
    def AddWorkspace(self, workspace: WorkspaceModel) -> None: ...
    def ExecuteCommand(self, command: RecordableCommand) -> None: ...
    def add_PropertyChanged(self, value: PropertyChangedEventHandler) -> None: ...
    def remove_PropertyChanged(self, value: PropertyChangedEventHandler) -> None: ...
    def add_RequestDispatcherInvoke(value: ActionHandler) -> None: ...
    def remove_RequestDispatcherInvoke(value: ActionHandler) -> None: ...
    def OnRequestDispatcherInvoke(action: Action) -> None: ...
    def add_RequestDispatcherBeginInvoke(value: ActionHandler) -> None: ...
    def remove_RequestDispatcherBeginInvoke(value: ActionHandler) -> None: ...
    def OnRequestDispatcherBeginInvoke(action: Action) -> None: ...
    def add_RequestLayoutUpdate(self, value: EventHandler) -> None: ...
    def remove_RequestLayoutUpdate(self, value: EventHandler) -> None: ...
    def OnRequestLayoutUpdate(self, sender: Object, e: EventArgs) -> None: ...
    def add_WorkspaceClearing(self, value: Action) -> None: ...
    def remove_WorkspaceClearing(self, value: Action) -> None: ...
    def OnWorkspaceClearing(self) -> None: ...
    def add_WorkspaceClearingStarted(self, value: Action) -> None: ...
    def remove_WorkspaceClearingStarted(self, value: Action) -> None: ...
    def OnWorkspaceClearingStarted(self, workspace: WorkspaceModel) -> None: ...
    def add_WorkspaceCleared(self, value: Action) -> None: ...
    def remove_WorkspaceCleared(self, value: Action) -> None: ...
    def OnWorkspaceCleared(self, workspace: WorkspaceModel) -> None: ...
    def add_WorkspaceAdded(self, value: Action) -> None: ...
    def remove_WorkspaceAdded(self, value: Action) -> None: ...
    def add_WorkspaceRemoveStarted(self, value: Action) -> None: ...
    def remove_WorkspaceRemoveStarted(self, value: Action) -> None: ...
    def add_WorkspaceRemoved(self, value: Action) -> None: ...
    def remove_WorkspaceRemoved(self, value: Action) -> None: ...
    def add_DeletionStarted(self, value: Action) -> None: ...
    def remove_DeletionStarted(self, value: Action) -> None: ...
    def OnDeletionStarted(self, modelsToDelete: List, cancelEventArgs: CancelEventArgs) -> None: ...
    def add_DeletionComplete(self, value: EventHandler) -> None: ...
    def remove_DeletionComplete(self, value: EventHandler) -> None: ...
    def OnDeletionComplete(self, sender: Object, e: EventArgs) -> None: ...
    def add_CleaningUp(self, value: Action) -> None: ...
    def remove_CleaningUp(self, value: Action) -> None: ...
    def OnCleanup(self) -> None: ...
    def add_RequestCancelActiveStateForNode(self, value: NodeHandler) -> None: ...
    def remove_RequestCancelActiveStateForNode(self, value: NodeHandler) -> None: ...
    def add_WorkspaceHidden(self, value: WorkspaceHandler) -> None: ...
    def remove_WorkspaceHidden(self, value: WorkspaceHandler) -> None: ...
    def add_RequestsRedraw(self, value: EventHandler) -> None: ...
    def remove_RequestsRedraw(self, value: EventHandler) -> None: ...
    def OnRequestsRedraw(self, sender: Object, e: EventArgs) -> None: ...
    def add_RequestNodeSelect(self, value: NodeEventHandler) -> None: ...
    def remove_RequestNodeSelect(self, value: NodeEventHandler) -> None: ...
    def add_RunCompleted(self, value: RunCompletedHandler) -> None: ...
    def remove_RunCompleted(self, value: RunCompletedHandler) -> None: ...
    def OnRunCompleted(self, sender: Object, success: bool) -> None: ...
    def add_RequestsCrashPrompt(self, value: CrashPromptHandler) -> None: ...
    def remove_RequestsCrashPrompt(self, value: CrashPromptHandler) -> None: ...
    def OnRequestsCrashPrompt(self, args: CrashErrorReportArgs) -> None: ...
    def add_EvaluationCompleted(self, value: EventHandler) -> None: ...
    def remove_EvaluationCompleted(self, value: EventHandler) -> None: ...
    def OnEvaluationCompleted(self, sender: Object, e: EvaluationCompletedEventArgs) -> None: ...
    def add_RefreshCompleted(self, value: Action) -> None: ...
    def remove_RefreshCompleted(self, value: Action) -> None: ...
    def OnRefreshCompleted(self, sender: Object, e: EventArgs) -> None: ...
    def add_WorkspaceSaved(self, value: WorkspaceHandler) -> None: ...
    def remove_WorkspaceSaved(self, value: WorkspaceHandler) -> None: ...
    def add_WorkspaceSaving(self, value: WorkspaceSaveHandler) -> None: ...
    def remove_WorkspaceSaving(self, value: WorkspaceSaveHandler) -> None: ...
    def add_RequestWorkspaceBackUpSave(self, value: Action) -> None: ...
    def remove_RequestWorkspaceBackUpSave(self, value: Action) -> None: ...
    def add_WorkspaceOpening(self, value: Action) -> None: ...
    def remove_WorkspaceOpening(self, value: Action) -> None: ...
    def add_WorkspaceOpened(self, value: WorkspaceHandler) -> None: ...
    def remove_WorkspaceOpened(self, value: WorkspaceHandler) -> None: ...
    def add_ShutdownStarted(self, value: DynamoModelHandler) -> None: ...
    def remove_ShutdownStarted(self, value: DynamoModelHandler) -> None: ...
    def add_ShutdownCompleted(self, value: DynamoModelHandler) -> None: ...
    def remove_ShutdownCompleted(self, value: DynamoModelHandler) -> None: ...
    def add_DynamoReady(self, value: Action) -> None: ...
    def remove_DynamoReady(self, value: Action) -> None: ...


class DynamoModelHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, model: DynamoModel) -> None: ...
    def BeginInvoke(self, model: DynamoModel, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class NodeHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, node: NodeModel) -> None: ...
    def BeginInvoke(self, node: NodeModel, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class WorkspaceHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, workspace: WorkspaceModel) -> None: ...
    def BeginInvoke(self, workspace: WorkspaceModel, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class WorkspaceSaveHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, workspace: WorkspaceModel, saveContext: SaveContext) -> None: ...
    def BeginInvoke(self, workspace: WorkspaceModel, saveContext: SaveContext, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class ActionHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, action: Action) -> None: ...
    def BeginInvoke(self, action: Action, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class NodeEventHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, sender: Object, e: EventArgs) -> None: ...
    def BeginInvoke(self, sender: Object, e: EventArgs, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class EvaluationCompletedEventArgs:
    def __init__(self, evaluationTookPlace: bool, errorMsg: Exception): ...
    @property
    def EvaluationTookPlace(self) -> bool: ...
    @property
    def EvaluationSucceeded(self) -> bool: ...
    @property
    def Error(self) -> Exception: ...


class RunType:
    Manual = 0
    Automatic = 1
    Periodic = 2


class NodeAutocompleteSuggestion:
    MLRecommendation = 0
    ObjectType = 1


class RunSettings(NotificationObject):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, runType: RunType, period: int): ...
    @property
    def RunPeriod(self) -> int: ...
    @RunPeriod.setter
    def RunPeriod(self, value: int) -> None: ...
    @property
    def RunType(self) -> RunType: ...
    @RunType.setter
    def RunType(self, value: RunType) -> None: ...
    @property
    def RunEnabled(self) -> bool: ...
    @RunEnabled.setter
    def RunEnabled(self, value: bool) -> None: ...
    @property
    def RunTypesEnabled(self) -> bool: ...
    @RunTypesEnabled.setter
    def RunTypesEnabled(self, value: bool) -> None: ...


class AssemblyLoadedHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, args: AssemblyLoadedEventArgs) -> None: ...
    def BeginInvoke(self, args: AssemblyLoadedEventArgs, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class AssemblyLoadedEventArgs:
    def __init__(self, assembly: Assembly): ...
    @property
    def Assembly(self) -> Assembly: ...


class DynamoModelState:
    NotStarted = 0
    StartedUIless = 1
    StartedUI = 2


class IStartConfiguration:
    @property
    def Context(self) -> str: ...
    @Context.setter
    def Context(self, value: str) -> None: ...
    @property
    def DynamoCorePath(self) -> str: ...
    @DynamoCorePath.setter
    def DynamoCorePath(self, value: str) -> None: ...
    @property
    def DynamoHostPath(self) -> str: ...
    @DynamoHostPath.setter
    def DynamoHostPath(self, value: str) -> None: ...
    @property
    def Preferences(self) -> IPreferences: ...
    @Preferences.setter
    def Preferences(self, value: IPreferences) -> None: ...
    @property
    def PathResolver(self) -> IPathResolver: ...
    @PathResolver.setter
    def PathResolver(self, value: IPathResolver) -> None: ...
    @property
    def StartInTestMode(self) -> bool: ...
    @StartInTestMode.setter
    def StartInTestMode(self, value: bool) -> None: ...
    @property
    def SchedulerThread(self) -> ISchedulerThread: ...
    @SchedulerThread.setter
    def SchedulerThread(self, value: ISchedulerThread) -> None: ...
    @property
    def GeometryFactoryPath(self) -> str: ...
    @GeometryFactoryPath.setter
    def GeometryFactoryPath(self, value: str) -> None: ...
    @property
    def AuthProvider(self) -> IAuthProvider: ...
    @AuthProvider.setter
    def AuthProvider(self, value: IAuthProvider) -> None: ...
    @property
    def Extensions(self) -> Iterable[IExtension]: ...
    @Extensions.setter
    def Extensions(self, value: Iterable[IExtension]) -> None: ...
    @property
    def ProcessMode(self) -> TaskProcessMode: ...
    @ProcessMode.setter
    def ProcessMode(self, value: TaskProcessMode) -> None: ...
    @property
    def IsHeadless(self) -> bool: ...
    @IsHeadless.setter
    def IsHeadless(self, value: bool) -> None: ...
    @property
    def NoNetworkMode(self) -> bool: ...
    @property
    def HostAnalyticsInfo(self) -> HostAnalyticsInfo: ...
    @HostAnalyticsInfo.setter
    def HostAnalyticsInfo(self, value: HostAnalyticsInfo) -> None: ...


class CrashReporterStartupOptions:
    @property
    def CERLocation(self) -> str: ...
    @CERLocation.setter
    def CERLocation(self, value: str) -> None: ...


class IStartConfigCrashReporter:
    @property
    def CRStartConfig(self) -> CrashReporterStartupOptions: ...
    @CRStartConfig.setter
    def CRStartConfig(self, value: CrashReporterStartupOptions) -> None: ...


class DefaultStartConfiguration:
    @property
    def Context(self) -> str: ...
    @Context.setter
    def Context(self, value: str) -> None: ...
    @property
    def DynamoCorePath(self) -> str: ...
    @DynamoCorePath.setter
    def DynamoCorePath(self, value: str) -> None: ...
    @property
    def DynamoHostPath(self) -> str: ...
    @DynamoHostPath.setter
    def DynamoHostPath(self, value: str) -> None: ...
    @property
    def Preferences(self) -> IPreferences: ...
    @Preferences.setter
    def Preferences(self, value: IPreferences) -> None: ...
    @property
    def PathResolver(self) -> IPathResolver: ...
    @PathResolver.setter
    def PathResolver(self, value: IPathResolver) -> None: ...
    @property
    def StartInTestMode(self) -> bool: ...
    @StartInTestMode.setter
    def StartInTestMode(self, value: bool) -> None: ...
    @property
    def SchedulerThread(self) -> ISchedulerThread: ...
    @SchedulerThread.setter
    def SchedulerThread(self, value: ISchedulerThread) -> None: ...
    @property
    def GeometryFactoryPath(self) -> str: ...
    @GeometryFactoryPath.setter
    def GeometryFactoryPath(self, value: str) -> None: ...
    @property
    def AuthProvider(self) -> IAuthProvider: ...
    @AuthProvider.setter
    def AuthProvider(self, value: IAuthProvider) -> None: ...
    @property
    def Extensions(self) -> Iterable[IExtension]: ...
    @Extensions.setter
    def Extensions(self, value: Iterable[IExtension]) -> None: ...
    @property
    def ProcessMode(self) -> TaskProcessMode: ...
    @ProcessMode.setter
    def ProcessMode(self, value: TaskProcessMode) -> None: ...
    @property
    def IsHeadless(self) -> bool: ...
    @IsHeadless.setter
    def IsHeadless(self, value: bool) -> None: ...
    @property
    def NoNetworkMode(self) -> bool: ...
    @NoNetworkMode.setter
    def NoNetworkMode(self, value: bool) -> None: ...
    @property
    def IsServiceMode(self) -> bool: ...
    @IsServiceMode.setter
    def IsServiceMode(self, value: bool) -> None: ...
    @property
    def PythonTemplatePath(self) -> str: ...
    @PythonTemplatePath.setter
    def PythonTemplatePath(self, value: str) -> None: ...
    @property
    def DefaultPythonEngine(self) -> str: ...
    @DefaultPythonEngine.setter
    def DefaultPythonEngine(self, value: str) -> None: ...
    @property
    def HostAnalyticsInfo(self) -> HostAnalyticsInfo: ...
    @HostAnalyticsInfo.setter
    def HostAnalyticsInfo(self, value: HostAnalyticsInfo) -> None: ...
    @property
    def CLIMode(self) -> bool: ...
    @CLIMode.setter
    def CLIMode(self, value: bool) -> None: ...


class RunCompletedHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, sender: Object, success: bool) -> None: ...
    def BeginInvoke(self, sender: Object, success: bool, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class CrashPromptHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, sender: Object, e: CrashPromptArgs) -> None: ...
    def BeginInvoke(self, sender: Object, e: CrashPromptArgs, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class RecordableCommand:


class ModelBasedRecordableCommand:
    @property
    def ModelGuid(self) -> Guid: ...
    @property
    def ModelGuids(self) -> Iterable[Guid]: ...


class PausePlaybackCommand:
    def __init__(self, pauseDurationInMs: int): ...


class OpenFileCommand:
    @overload
    def __init__(self, filePath: str, forceManualExecutionMode: bool): ...
    @overload
    def __init__(self, filePath: str, forceManualExecutionMode: bool, isTemplate: bool): ...


class InsertFileCommand:
    def __init__(self, filePath: str, forceManualExecutionMode: bool): ...


class OpenFileFromJsonCommand:
    def __init__(self, fileContents: str, forceManualExecutionMode: bool): ...


class RunCancelCommand:
    def __init__(self, showErrors: bool, cancelRun: bool): ...


class ForceRunCancelCommand:
    def __init__(self, showErrors: bool, cancelRun: bool): ...


class MutateTestCommand:
    def __init__(self): ...


class CreateNodeCommand:
    @overload
    def __init__(self, node: NodeModel, x: float, y: float, defaultPosition: bool, transformCoordinates: bool): ...
    @overload
    def __init__(self, nodeId: Iterable[Guid], nodeName: str, x: float, y: float, defaultPosition: bool, transformCoordinates: bool): ...
    @overload
    def __init__(self, nodeId: str, nodeName: str, x: float, y: float, defaultPosition: bool, transformCoordinates: bool): ...
    @property
    def Name(self) -> str: ...


class CreateAndConnectNodeCommand:
    def __init__(self, newNodeGuid: Guid, existingNodeGuid: Guid, newNodeName: str, outPortIndex: int, inPortIndex: int, x: float, y: float, createAsDownstreamNode: bool, addNewNodeToSelection: bool): ...
    @property
    def NewNodeName(self) -> str: ...


class CreateProxyNodeCommand:
    def __init__(self, nodeId: str, customnodeFunctionId: str, x: float, y: float, defaultPosition: bool, transformCoordinates: bool, name: str, inputs: int, outputs: int): ...


class CreateNoteCommand:
    @overload
    def __init__(self, nodeId: Guid, noteText: str, x: float, y: float, defaultPosition: bool): ...
    @overload
    def __init__(self, nodeIds: Iterable[Guid], noteText: str, x: float, y: float, defaultPosition: bool): ...
    @overload
    def __init__(self, nodeId: str, noteText: str, x: float, y: float, defaultPosition: bool): ...


class SelectModelCommand:
    @overload
    def __init__(self, modelGuid: str, modifiers: ModifierKeys): ...
    @overload
    def __init__(self, modelGuid: Guid, modifiers: ModifierKeys): ...
    @overload
    def __init__(self, modelGuids: Iterable[Guid], modifiers: ModifierKeys): ...


class SelectInRegionCommand:
    def __init__(self, region: Rect2D, isCrossSelection: bool): ...


class DragSelectionCommand:
    def __init__(self, mouseCursor: Point2D, operation: Operation): ...


class MakeConnectionCommand:
    @overload
    def __init__(self, nodeId: str, portIndex: int, portType: PortType, mode: Mode): ...
    @overload
    def __init__(self, nodeId: Guid, portIndex: int, portType: PortType, mode: Mode): ...
    @overload
    def __init__(self, nodeId: Iterable[Guid], portIndex: int, portType: PortType, mode: Mode): ...
    @property
    def PortIndex(self) -> int: ...
    @property
    def ConnectionMode(self) -> Mode: ...


class DeleteModelCommand:
    @overload
    def __init__(self, modelGuid: str): ...
    @overload
    def __init__(self, modelGuid: Guid): ...
    @overload
    def __init__(self, modelGuids: Iterable[Guid]): ...


class UndoRedoCommand:
    def __init__(self, operation: Operation): ...


class ModelEventCommand:
    @overload
    def __init__(self, modelGuid: str, eventName: str, value: int): ...
    @overload
    def __init__(self, modelGuid: str, eventName: str): ...
    @overload
    def __init__(self, modelGuid: Guid, eventName: str, value: int): ...
    @overload
    def __init__(self, modelGuid: Guid, eventName: str): ...
    @overload
    def __init__(self, modelGuid: Iterable[Guid], eventName: str, value: int): ...
    @overload
    def __init__(self, modelGuid: Iterable[Guid], eventName: str): ...
    @property
    def EventName(self) -> str: ...
    @property
    def Value(self) -> int: ...


class UpdateModelValueCommand:
    @overload
    def __init__(self, workspaceGuid: Guid, modelGuid: Guid, name: str, value: str): ...
    @overload
    def __init__(self, modelGuid: str, name: str, value: str): ...
    @overload
    def __init__(self, modelGuid: Guid, name: str, value: str): ...
    @overload
    def __init__(self, modelGuid: Iterable[Guid], name: str, value: str): ...
    @overload
    def __init__(self, workspaceGuid: Guid, modelGuid: Iterable[Guid], name: str, value: str): ...
    @property
    def ModelGuids(self) -> Iterable[Guid]: ...
    @property
    def Name(self) -> str: ...
    @property
    def Value(self) -> str: ...
    def ToString(self) -> str: ...


class ConvertNodesToCodeCommand:


class CreateCustomNodeCommand:
    @overload
    def __init__(self, nodeId: str, name: str, category: str, description: str, makeCurrent: bool): ...
    @overload
    def __init__(self, nodeId: Guid, name: str, category: str, description: str, makeCurrent: bool): ...
    @overload
    def __init__(self, nodeId: Iterable[Guid], name: str, category: str, description: str, makeCurrent: bool): ...


class SwitchTabCommand:
    def __init__(self, modelIndex: int): ...


class CreateAnnotationCommand:
    @overload
    def __init__(self, annotationId: Guid, annotationText: str, x: float, y: float, defaultPosition: bool): ...
    @overload
    def __init__(self, annotationId: Guid, annotationText: str, annotationDescriptionText: str, x: float, y: float, defaultPosition: bool): ...
    @overload
    def __init__(self, annotationId: Iterable[Guid], annotationText: str, x: float, y: float, defaultPosition: bool): ...
    @overload
    def __init__(self, annotationId: Iterable[Guid], annotationText: str, annotationDescriptionText: str, x: float, y: float, defaultPosition: bool): ...


class UngroupModelCommand:
    @overload
    def __init__(self, modelGuid: str): ...
    @overload
    def __init__(self, modelGuid: Guid): ...
    @overload
    def __init__(self, modelGuid: Iterable[Guid]): ...


class AddModelToGroupCommand:
    @overload
    def __init__(self, modelGuid: str): ...
    @overload
    def __init__(self, modelGuid: Guid): ...
    @overload
    def __init__(self, modelGuid: Iterable[Guid]): ...


class AddGroupToGroupCommand:
    @overload
    def __init__(self, modelGuid: str, hostModelGuid: str): ...
    @overload
    def __init__(self, modelGuid: Guid, hostModelGuid: Guid): ...
    @overload
    def __init__(self, modelGuid: Iterable[Guid], hostModelGuid: Guid): ...
    @property
    def HostGroupGuid(self) -> Guid: ...
    @HostGroupGuid.setter
    def HostGroupGuid(self, value: Guid) -> None: ...


class AddPresetCommand:
    def __init__(self, name: str, description: str, currentSelectionIds: Iterable[Guid]): ...


class ApplyPresetCommand:
    def __init__(self, workspaceID: Guid, stateID: Guid): ...


class Operation:
    BeginDrag = 0
    EndDrag = 1


class Mode:
    Begin = 0
    End = 1
    BeginShiftReconnections = 2
    EndShiftReconnections = 3
    EndAndStartCtrlConnection = 4
    Cancel = 5
    BeginDuplicateConnection = 6
    BeginCreateConnections = 7


class Operation:
    Undo = 0
    Redo = 1
