from typing import Tuple, Set, Iterable, List


class AstBuiltEventHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, sender: Object, e: CompiledEventArgs) -> None: ...
    def BeginInvoke(self, sender: Object, e: CompiledEventArgs, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class EngineController(LogSourceBase):
    def __init__(self, libraryServices: LibraryServices, geometryFactoryFileName: str, verboseLogging: bool): ...
    def add_AstBuilt(self, value: AstBuiltEventHandler) -> None: ...
    def remove_AstBuilt(self, value: AstBuiltEventHandler) -> None: ...
    @property
    def LiveRunnerCore(self) -> Core: ...
    @property
    def LiveRunnerRuntimeCore(self) -> RuntimeCore: ...
    @property
    def LibraryServices(self) -> LibraryServices: ...
    @property
    def ExecutionTimeData(self) -> IProfilingExecutionTimeData: ...
    @property
    def IsDisposed(self) -> bool: ...
    def Dispose(self) -> None: ...
    def EnableProfiling(self, enable: bool, workspace: HomeWorkspaceModel, nodes: Iterable[NodeModel]) -> None: ...
    def GetMirror(self, variableName: str) -> RuntimeMirror: ...
    @property
    def HasPendingGraphSyncData(self) -> bool: ...
    def OnCompiling(self, nodeGuid: Guid) -> None: ...
    def OnCompiled(self, nodeGuid: Guid, astNodes: Iterable[AssociativeNode]) -> None: ...
    def NodeDeleted(self, node: NodeModel) -> None: ...


class CompilationServices:
    def __init__(self, libraryServices: LibraryServices): ...


class ITraceReconciliationProcessor:
    def PostTraceReconciliation(self, orphanedSerializables: Dictionary) -> None: ...


class LiveRunnerServices(LogSourceBase):
    def __init__(self, controller: EngineController, geometryFactoryFileName: str): ...
    def Dispose(self) -> None: ...
    @property
    def Core(self) -> Core: ...
    @property
    def RuntimeCore(self) -> RuntimeCore: ...


class IFunctionDescriptor:
    @property
    def DisplayName(self) -> str: ...
    @property
    def MangledName(self) -> str: ...
    @property
    def ReturnKeys(self) -> Iterable[str]: ...
    @property
    def Parameters(self) -> Iterable[TypedParameter]: ...
    @property
    def FunctionName(self) -> str: ...
    @property
    def ReturnType(self) -> Type: ...


class FunctionDescriptorParams:
    def __init__(self): ...
    @property
    def Assembly(self) -> str: ...
    @Assembly.setter
    def Assembly(self, value: str) -> None: ...
    @property
    def ClassName(self) -> str: ...
    @ClassName.setter
    def ClassName(self, value: str) -> None: ...
    @property
    def FunctionName(self) -> str: ...
    @FunctionName.setter
    def FunctionName(self, value: str) -> None: ...
    @property
    def Summary(self) -> str: ...
    @Summary.setter
    def Summary(self, value: str) -> None: ...
    @property
    def ObsoleteMsg(self) -> str: ...
    @ObsoleteMsg.setter
    def ObsoleteMsg(self, value: str) -> None: ...
    @property
    def Parameters(self) -> Iterable[TypedParameter]: ...
    @Parameters.setter
    def Parameters(self, value: Iterable[TypedParameter]) -> None: ...
    @property
    def ReturnType(self) -> Type: ...
    @ReturnType.setter
    def ReturnType(self, value: Type) -> None: ...
    @property
    def FunctionType(self) -> FunctionType: ...
    @FunctionType.setter
    def FunctionType(self, value: FunctionType) -> None: ...
    @property
    def IsVisibleInLibrary(self) -> bool: ...
    @IsVisibleInLibrary.setter
    def IsVisibleInLibrary(self, value: bool) -> None: ...
    @property
    def CanUpdatePeriodically(self) -> bool: ...
    @CanUpdatePeriodically.setter
    def CanUpdatePeriodically(self, value: bool) -> None: ...
    @property
    def ReturnKeys(self) -> Iterable[str]: ...
    @ReturnKeys.setter
    def ReturnKeys(self, value: Iterable[str]) -> None: ...
    @property
    def PathManager(self) -> IPathManager: ...
    @PathManager.setter
    def PathManager(self, value: IPathManager) -> None: ...
    @property
    def IsVarArg(self) -> bool: ...
    @IsVarArg.setter
    def IsVarArg(self, value: bool) -> None: ...
    @property
    def IsBuiltIn(self) -> bool: ...
    @IsBuiltIn.setter
    def IsBuiltIn(self, value: bool) -> None: ...
    @property
    def IsPackageMember(self) -> bool: ...
    @IsPackageMember.setter
    def IsPackageMember(self, value: bool) -> None: ...
    @property
    def IsLacingDisabled(self) -> bool: ...
    @IsLacingDisabled.setter
    def IsLacingDisabled(self, value: bool) -> None: ...


class FunctionDescriptor:
    def __init__(self, funcDescParams: FunctionDescriptorParams): ...
    @property
    def IsOverloaded(self) -> bool: ...
    @IsOverloaded.setter
    def IsOverloaded(self, value: bool) -> None: ...
    @property
    def Assembly(self) -> str: ...
    @property
    def ClassName(self) -> str: ...
    @property
    def FunctionName(self) -> str: ...
    @property
    def Parameters(self) -> Iterable[TypedParameter]: ...
    @property
    def ReturnType(self) -> Type: ...
    @property
    def ReturnKeys(self) -> Iterable[str]: ...
    @property
    def IsVarArg(self) -> bool: ...
    @property
    def IsBuiltIn(self) -> bool: ...
    @property
    def IsPackageMember(self) -> bool: ...
    @property
    def ObsoleteMessage(self) -> str: ...
    @property
    def IsObsolete(self) -> bool: ...
    @property
    def Type(self) -> FunctionType: ...
    @property
    def Summary(self) -> str: ...
    @property
    def Description(self) -> str: ...
    @property
    def Returns(self) -> Iterable[Tuple]: ...
    @property
    def InputParameters(self) -> Iterable[Tuple]: ...
    @property
    def Category(self) -> str: ...
    @property
    def QualifiedName(self) -> str: ...
    @property
    def MangledName(self) -> str: ...
    @property
    def Signature(self) -> str: ...
    @property
    def UserFriendlyName(self) -> str: ...
    @property
    def DisplayName(self) -> str: ...
    @property
    def IsVisibleInLibrary(self) -> bool: ...
    @property
    def CanUpdatePeriodically(self) -> bool: ...
    @property
    def UnqualifedClassName(self) -> str: ...
    @property
    def Namespace(self) -> str: ...
    @property
    def PathManager(self) -> IPathManager: ...
    @property
    def IsLacingDisabled(self) -> bool: ...
    def Equals(self, obj: Object) -> bool: ...
    def GetHashCode(self) -> int: ...


class FunctionGroup:
    def __init__(self, qualifiedName: str): ...
    @property
    def QualifiedName(self) -> str: ...
    @property
    def Functions(self) -> Iterable[FunctionDescriptor]: ...
    def Equals(self, obj: Object) -> bool: ...
    def GetHashCode(self) -> int: ...


class FunctionType:
    GenericFunction = 0
    Constructor = 1
    StaticMethod = 2
    InstanceMethod = 3
    StaticProperty = 4
    InstanceProperty = 5


class LibraryServices(LogSourceBase):
    @overload
    def __init__(self, libraryManagementCore: Core, pathManager: IPathManager): ...
    @overload
    def __init__(self, libraryManagementCore: Core, pathManager: IPathManager, preferences: IPreferences): ...
    @property
    def LibraryManagementCore(self) -> Core: ...
    def Dispose(self) -> None: ...
    @property
    def ImportedLibraries(self) -> Iterable[str]: ...
    @property
    def BuiltinFunctionGroups(self) -> Iterable[FunctionGroup]: ...
    @property
    def ImportedFunctionGroups(self) -> Iterable[FunctionGroup]: ...
    def add_LibraryLoading(self, value: EventHandler) -> None: ...
    def remove_LibraryLoading(self, value: EventHandler) -> None: ...
    def add_LibraryLoadFailed(self, value: EventHandler) -> None: ...
    def remove_LibraryLoadFailed(self, value: EventHandler) -> None: ...
    def add_LibraryLoaded(self, value: EventHandler) -> None: ...
    def remove_LibraryLoaded(self, value: EventHandler) -> None: ...
    @overload
    def GetFunctionDescriptor(self, library: str, mangledName: str) -> FunctionDescriptor: ...
    def GetPriorNames(self) -> Dictionary: ...
    @overload
    def GetFunctionDescriptor(self, managledName: str) -> FunctionDescriptor: ...
    def GetAllFunctionDescriptors(self, qualifiedName: str) -> Iterable[FunctionDescriptor]: ...


class XmlDocumentationExtensions:
    def add_LogToConsole(value: Action) -> None: ...
    def remove_LogToConsole(value: Action) -> None: ...


class Categories:


class LibraryLoadFailedEventArgs:
    def __init__(self, libraryPath: str, reason: str, throwOnFailure: bool): ...
    @property
    def LibraryPath(self) -> str: ...
    @property
    def Reason(self) -> str: ...
    @property
    def ThrowOnFailure(self) -> bool: ...


class LibraryLoadedEventArgs:
    def __init__(self, libraryPaths: Iterable[str]): ...
    @property
    def LibraryPaths(self) -> Iterable[str]: ...


class LibraryLoadingEventArgs:
    def __init__(self, libraryPath: str): ...
    @property
    def LibraryPath(self) -> str: ...
