from typing import Tuple, Set, Iterable, List


class EventHandlerProxy:
    def __init__(self): ...
    def add_DocumentOpened(self, value: EventHandler) -> None: ...
    def remove_DocumentOpened(self, value: EventHandler) -> None: ...
    def add_DocumentClosing(self, value: EventHandler) -> None: ...
    def remove_DocumentClosing(self, value: EventHandler) -> None: ...
    def add_DocumentClosed(self, value: EventHandler) -> None: ...
    def remove_DocumentClosed(self, value: EventHandler) -> None: ...
    def add_ViewActivating(self, value: EventHandler) -> None: ...
    def remove_ViewActivating(self, value: EventHandler) -> None: ...
    def add_ViewActivated(self, value: EventHandler) -> None: ...
    def remove_ViewActivated(self, value: EventHandler) -> None: ...
    def OnApplicationDocumentOpened(self, sender: Object, args: DocumentOpenedEventArgs) -> None: ...
    def OnApplicationDocumentClosing(self, sender: Object, args: DocumentClosingEventArgs) -> None: ...
    def OnApplicationDocumentClosed(self, sender: Object, args: DocumentClosedEventArgs) -> None: ...
    def OnApplicationViewActivating(self, sender: Object, args: ViewActivatingEventArgs) -> None: ...
    def OnApplicationViewActivated(self, sender: Object, args: ViewActivatedEventArgs) -> None: ...
