from typing import Tuple, Set, Iterable, List


class CustomNodeWorkspaceModel(WorkspaceModel):
    @overload
    def __init__(self, info: WorkspaceInfo, factory: NodeFactory): ...
    @overload
    def __init__(self, factory: NodeFactory, nodes: Iterable[NodeModel], notes: Iterable[NoteModel], annotations: Iterable[AnnotationModel], presets: Iterable[PresetModel], elementResolver: ElementResolver, info: WorkspaceInfo): ...
    @property
    def CustomNodeId(self) -> Guid: ...
    @property
    def CustomNodeDependencies(self) -> Iterable[CustomNodeDefinition]: ...
    @property
    def CustomNodeDefinition(self) -> CustomNodeDefinition: ...
    @property
    def CustomNodeInfo(self) -> CustomNodeInfo: ...
    def GetSharedName(self) -> str: ...
    def SetInfo(self, newName: str, newCategory: str, newDescription: str, newFilename: str) -> None: ...
    @property
    def Category(self) -> str: ...
    @Category.setter
    def Category(self, value: str) -> None: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @property
    def IsVisibleInDynamoLibrary(self) -> bool: ...
    @IsVisibleInDynamoLibrary.setter
    def IsVisibleInDynamoLibrary(self, value: bool) -> None: ...
    def add_InfoChanged(self, value: Action) -> None: ...
    def remove_InfoChanged(self, value: Action) -> None: ...
    def add_DefinitionUpdated(self, value: Action) -> None: ...
    def remove_DefinitionUpdated(self, value: Action) -> None: ...
    def add_FunctionIdChanged(self, value: Action) -> None: ...
    def remove_FunctionIdChanged(self, value: Action) -> None: ...
    def Save(self, newPath: str, isBackup: bool, engine: EngineController) -> None: ...


class HomeWorkspaceModel(WorkspaceModel):
    @overload
    def __init__(self, engine: EngineController, scheduler: DynamoScheduler, factory: NodeFactory, verboseLogging: bool, isTestMode: bool, linterManager: LinterManager, fileName: str): ...
    @overload
    def __init__(self, guid: Guid, engine: EngineController, scheduler: DynamoScheduler, factory: NodeFactory, traceData: Iterable[KeyValuePair], nodes: Iterable[NodeModel], notes: Iterable[NoteModel], annotations: Iterable[AnnotationModel], presets: Iterable[PresetModel], resolver: ElementResolver, info: WorkspaceInfo, verboseLogging: bool, isTestMode: bool, linterManager: LinterManager): ...
    @overload
    def __init__(self, engine: EngineController, scheduler: DynamoScheduler, factory: NodeFactory, traceData: Iterable[KeyValuePair], nodes: Iterable[NodeModel], notes: Iterable[NoteModel], annotations: Iterable[AnnotationModel], presets: Iterable[PresetModel], resolver: ElementResolver, info: WorkspaceInfo, verboseLogging: bool, isTestMode: bool, linterManager: LinterManager): ...
    @property
    def EngineController(self) -> EngineController: ...
    @property
    def IsTestMode(self) -> bool: ...
    @IsTestMode.setter
    def IsTestMode(self, value: bool) -> None: ...
    @property
    def HasRunWithoutCrash(self) -> bool: ...
    @HasRunWithoutCrash.setter
    def HasRunWithoutCrash(self, value: bool) -> None: ...
    @property
    def RunSettings(self) -> RunSettings: ...
    @RunSettings.setter
    def RunSettings(self, value: RunSettings) -> None: ...
    @property
    def EvaluationCount(self) -> Int64: ...
    @property
    def GraphDocumentationURL(self) -> Uri: ...
    @GraphDocumentationURL.setter
    def GraphDocumentationURL(self, value: Uri) -> None: ...
    @property
    def Thumbnail(self) -> str: ...
    @Thumbnail.setter
    def Thumbnail(self, value: str) -> None: ...
    def add_EvaluationStarted(self, value: EventHandler) -> None: ...
    def remove_EvaluationStarted(self, value: EventHandler) -> None: ...
    def OnEvaluationStarted(self, e: EventArgs) -> None: ...
    def add_EvaluationCompleted(self, value: EventHandler) -> None: ...
    def remove_EvaluationCompleted(self, value: EventHandler) -> None: ...
    def OnEvaluationCompleted(self, e: EvaluationCompletedEventArgs) -> None: ...
    def add_RefreshCompleted(self, value: EventHandler) -> None: ...
    def remove_RefreshCompleted(self, value: EventHandler) -> None: ...
    def OnRefreshCompleted(self, e: EvaluationCompletedEventArgs) -> None: ...
    def Dispose(self) -> None: ...
    def Clear(self) -> None: ...
    def Run(self) -> None: ...


class ICustomNodeWorkspaceModel:
    @property
    def CustomNodeId(self) -> Guid: ...
    @property
    def CustomNodeDefinition(self) -> CustomNodeDefinition: ...
    @property
    def CustomNodeInfo(self) -> CustomNodeInfo: ...
    def add_InfoChanged(self, value: Action) -> None: ...
    def remove_InfoChanged(self, value: Action) -> None: ...
    def add_DefinitionUpdated(self, value: Action) -> None: ...
    def remove_DefinitionUpdated(self, value: Action) -> None: ...
    def add_FunctionIdChanged(self, value: Action) -> None: ...
    def remove_FunctionIdChanged(self, value: Action) -> None: ...


class IWorkspaceModel:
    @property
    def Name(self) -> str: ...
    @property
    def Description(self) -> str: ...
    @property
    def FileName(self) -> str: ...
    @property
    def Connectors(self) -> Iterable[ConnectorModel]: ...
    @property
    def Nodes(self) -> Iterable[NodeModel]: ...
    @property
    def CurrentSelection(self) -> Iterable[NodeModel]: ...
    @property
    def CenterX(self) -> float: ...
    @property
    def CenterY(self) -> float: ...
    def add_NodeAdded(self, value: Action) -> None: ...
    def remove_NodeAdded(self, value: Action) -> None: ...
    def add_NodeRemoved(self, value: Action) -> None: ...
    def remove_NodeRemoved(self, value: Action) -> None: ...
    def add_NodesCleared(self, value: Action) -> None: ...
    def remove_NodesCleared(self, value: Action) -> None: ...
    def add_ConnectorAdded(self, value: Action) -> None: ...
    def remove_ConnectorAdded(self, value: Action) -> None: ...
    def add_ConnectorDeleted(self, value: Action) -> None: ...
    def remove_ConnectorDeleted(self, value: Action) -> None: ...
    def RecordModelsForModification(self, models: Iterable[ModelBase]) -> None: ...


class LayoutExtensions:


class PackageDependencyState:
    Loaded = 0
    IncorrectVersion = 1
    Missing = 2
    Warning = 3
    RequiresRestart = 4


class IPackageInfo:
    @property
    def Name(self) -> str: ...
    @property
    def Version(self) -> Version: ...


class PackageInfo:
    @property
    def Name(self) -> str: ...
    @property
    def Version(self) -> Version: ...
    def Equals(self, obj: Object) -> bool: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...


class PresetExtensions:
    def ImportPresets(workspace: WorkspaceModel, presetCollection: Iterable[PresetModel]) -> None: ...


class NodeReadConverter:
    def __init__(self, manager: CustomNodeManager, libraryServices: LibraryServices, nodeFactory: NodeFactory, isTestMode: bool): ...
    @property
    def ElementResolver(self) -> ElementResolver: ...
    @ElementResolver.setter
    def ElementResolver(self, value: ElementResolver) -> None: ...
    def CanConvert(self, objectType: Type) -> bool: ...
    def ReadJson(self, reader: JsonReader, objectType: Type, existingValue: Object, serializer: JsonSerializer) -> Object: ...
    def WriteJson(self, writer: JsonWriter, value: Object, serializer: JsonSerializer) -> None: ...
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...


class DescriptionConverter:
    def __init__(self): ...
    def CanConvert(self, objectType: Type) -> bool: ...
    def ReadJson(self, reader: JsonReader, objectType: Type, existingValue: Object, serializer: JsonSerializer) -> Object: ...
    def WriteJson(self, writer: JsonWriter, value: Object, serializer: JsonSerializer) -> None: ...


class WorkspaceReadConverter:
    @overload
    def __init__(self, engine: EngineController, scheduler: DynamoScheduler, factory: NodeFactory, isTestMode: bool, verboseLogging: bool): ...
    @overload
    def __init__(self, engine: EngineController, scheduler: DynamoScheduler, factory: NodeFactory, isTestMode: bool, verboseLogging: bool, linterManager: LinterManager): ...
    def CanConvert(self, objectType: Type) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    def ReadJson(self, reader: JsonReader, objectType: Type, existingValue: Object, serializer: JsonSerializer) -> Object: ...
    def WriteJson(self, writer: JsonWriter, value: Object, serializer: JsonSerializer) -> None: ...


class WorkspaceWriteConverter:
    def __init__(self, engine: EngineController): ...
    def CanConvert(self, objectType: Type) -> bool: ...
    @property
    def CanRead(self) -> bool: ...
    def WriteJson(self, writer: JsonWriter, value: Object, serializer: JsonSerializer) -> None: ...
    def ReadJson(self, reader: JsonReader, objectType: Type, existingValue: Object, serializer: JsonSerializer) -> Object: ...


class LinterManagerConverter:
    def __init__(self, logger: ILogger): ...
    def CanConvert(self, objectType: Type) -> bool: ...
    def ReadJson(self, reader: JsonReader, objectType: Type, existingValue: Object, serializer: JsonSerializer) -> Object: ...
    def WriteJson(self, writer: JsonWriter, value: Object, serializer: JsonSerializer) -> None: ...


class NodeLibraryDependencyConverter:
    def __init__(self, logger: ILogger): ...
    def CanConvert(self, objectType: Type) -> bool: ...
    @property
    def CanRead(self) -> bool: ...
    def WriteJson(self, writer: JsonWriter, value: Object, serializer: JsonSerializer) -> None: ...
    def ReadJson(self, reader: JsonReader, objectType: Type, existingValue: Object, serializer: JsonSerializer) -> Object: ...


class DummyNodeWriteConverter:
    def __init__(self): ...
    def CanConvert(self, objectType: Type) -> bool: ...
    @property
    def CanRead(self) -> bool: ...
    def WriteJson(self, writer: JsonWriter, value: Object, serializer: JsonSerializer) -> None: ...
    def ReadJson(self, reader: JsonReader, objectType: Type, existingValue: Object, serializer: JsonSerializer) -> Object: ...


class ConnectorConverter:
    def __init__(self, logger: ILogger): ...
    def CanConvert(self, objectType: Type) -> bool: ...
    def ReadJson(self, reader: JsonReader, objectType: Type, existingValue: Object, serializer: JsonSerializer) -> Object: ...
    def WriteJson(self, writer: JsonWriter, value: Object, serializer: JsonSerializer) -> None: ...


class IdToGuidConverter:
    def __init__(self): ...
    def CanConvert(self, objectType: Type) -> bool: ...
    def ReadJson(self, reader: JsonReader, objectType: Type, existingValue: Object, serializer: JsonSerializer) -> Object: ...
    def WriteJson(self, writer: JsonWriter, value: Object, serializer: JsonSerializer) -> None: ...


class TypedParameterConverter:
    def __init__(self): ...
    def CanConvert(self, objectType: Type) -> bool: ...
    def ReadJson(self, reader: JsonReader, objectType: Type, existingValue: Object, serializer: JsonSerializer) -> Object: ...
    def WriteJson(self, writer: JsonWriter, value: Object, serializer: JsonSerializer) -> None: ...


class IdReferenceResolver:
    def __init__(self): ...
    def AddToReferenceMap(self, oldId: Guid, newObject: Object) -> None: ...
    def AddReference(self, context: Object, reference: str, value: Object) -> None: ...
    def GetReference(self, context: Object, value: Object) -> str: ...
    def IsReferenced(self, context: Object, value: Object) -> bool: ...
    def ResolveReference(self, context: Object, reference: str) -> Object: ...
    def ResolveReferenceFromMap(self, context: Object, reference: str) -> Object: ...


class SerializationExtensions:


class WorkspaceModel(NotificationObject):
    @property
    def CanUndo(self) -> bool: ...
    @property
    def CanRedo(self) -> bool: ...
    def DeleteModel(self, modelData: XmlElement) -> None: ...
    def RemoveGroup(self, model: ModelBase) -> None: ...
    def ReloadModel(self, modelData: XmlElement) -> None: ...
    def CreateModel(self, modelData: XmlElement) -> None: ...
    def GetModelForElement(self, modelData: XmlElement) -> ModelBase: ...
    def GetModelInternal(self, modelGuid: Guid) -> ModelBase: ...
    def add_DummyNodesReloaded(value: Action) -> None: ...
    def remove_DummyNodesReloaded(value: Action) -> None: ...
    def OnDummyNodesReloaded(self) -> None: ...
    def add_RequestNodeCentered(self, value: NodeEventHandler) -> None: ...
    def remove_RequestNodeCentered(self, value: NodeEventHandler) -> None: ...
    def add_CurrentOffsetChanged(self, value: PointEventHandler) -> None: ...
    def remove_CurrentOffsetChanged(self, value: PointEventHandler) -> None: ...
    def add_Saved(self, value: Action) -> None: ...
    def remove_Saved(self, value: Action) -> None: ...
    def add_WorkspaceSaving(self, value: Action) -> None: ...
    def remove_WorkspaceSaving(self, value: Action) -> None: ...
    def add_NodeAdded(self, value: Action) -> None: ...
    def remove_NodeAdded(self, value: Action) -> None: ...
    def add_NodeRemoved(self, value: Action) -> None: ...
    def remove_NodeRemoved(self, value: Action) -> None: ...
    def add_NodesCleared(self, value: Action) -> None: ...
    def remove_NodesCleared(self, value: Action) -> None: ...
    def add_NoteAdded(self, value: Action) -> None: ...
    def remove_NoteAdded(self, value: Action) -> None: ...
    def add_NoteRemoved(self, value: Action) -> None: ...
    def remove_NoteRemoved(self, value: Action) -> None: ...
    def add_NotesCleared(self, value: Action) -> None: ...
    def remove_NotesCleared(self, value: Action) -> None: ...
    def add_AnnotationAdded(self, value: Action) -> None: ...
    def remove_AnnotationAdded(self, value: Action) -> None: ...
    def add_AnnotationRemoved(self, value: Action) -> None: ...
    def remove_AnnotationRemoved(self, value: Action) -> None: ...
    def add_AnnotationsCleared(self, value: Action) -> None: ...
    def remove_AnnotationsCleared(self, value: Action) -> None: ...
    def add_ConnectorAdded(self, value: Action) -> None: ...
    def remove_ConnectorAdded(self, value: Action) -> None: ...
    def add_ConnectorDeleted(self, value: Action) -> None: ...
    def remove_ConnectorDeleted(self, value: Action) -> None: ...
    def RecordModelsForModification(self, models: Iterable[ModelBase]) -> None: ...
    def add_Disposed(self, value: Action) -> None: ...
    def remove_Disposed(self, value: Action) -> None: ...
    def add_Saving(self, value: Action) -> None: ...
    def remove_Saving(self, value: Action) -> None: ...
    @property
    def Presets(self) -> Iterable[PresetModel]: ...
    @property
    def LastSaved(self) -> DateTime: ...
    @LastSaved.setter
    def LastSaved(self, value: DateTime) -> None: ...
    @property
    def Dependencies(self) -> HashSet: ...
    @property
    def Author(self) -> str: ...
    @Author.setter
    def Author(self, value: str) -> None: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @property
    def HasUnsavedChanges(self) -> bool: ...
    @HasUnsavedChanges.setter
    def HasUnsavedChanges(self, value: bool) -> None: ...
    @property
    def IsReadOnly(self) -> bool: ...
    @IsReadOnly.setter
    def IsReadOnly(self, value: bool) -> None: ...
    @property
    def Nodes(self) -> Iterable[NodeModel]: ...
    @property
    def CurrentSelection(self) -> Iterable[NodeModel]: ...
    @property
    def Connectors(self) -> Iterable[ConnectorModel]: ...
    @property
    def Notes(self) -> Iterable[NoteModel]: ...
    @property
    def Annotations(self) -> Iterable[AnnotationModel]: ...
    @property
    def FileName(self) -> str: ...
    @FileName.setter
    def FileName(self, value: str) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def X(self) -> float: ...
    @X.setter
    def X(self, value: float) -> None: ...
    @property
    def Y(self) -> float: ...
    @Y.setter
    def Y(self, value: float) -> None: ...
    @property
    def Zoom(self) -> float: ...
    @Zoom.setter
    def Zoom(self, value: float) -> None: ...
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> None: ...
    @property
    def Width(self) -> float: ...
    @Width.setter
    def Width(self, value: float) -> None: ...
    @property
    def Rect(self) -> Rect2D: ...
    @property
    def CenterX(self) -> float: ...
    @CenterX.setter
    def CenterX(self, value: float) -> None: ...
    @property
    def CenterY(self) -> float: ...
    @CenterY.setter
    def CenterY(self, value: float) -> None: ...
    @property
    def ElementResolver(self) -> ElementResolver: ...
    @property
    def Guid(self) -> Guid: ...
    @property
    def ScaleFactor(self) -> float: ...
    def Dispose(self) -> None: ...
    def GetSharedName(self) -> str: ...
    def Clear(self) -> None: ...
    def Save(self, filePath: str, isBackup: bool, engine: EngineController) -> None: ...
    def ReportPosition(self) -> None: ...
    def add_MessageLogged(self, value: Action) -> None: ...
    def remove_MessageLogged(self, value: Action) -> None: ...
    @overload
    def FromJson(json: str, libraryServices: LibraryServices, engineController: EngineController, scheduler: DynamoScheduler, factory: NodeFactory, isTestMode: bool, verboseLogging: bool, manager: CustomNodeManager) -> WorkspaceModel: ...
    @overload
    def FromJson(json: str, libraryServices: LibraryServices, engineController: EngineController, scheduler: DynamoScheduler, factory: NodeFactory, isTestMode: bool, verboseLogging: bool, manager: CustomNodeManager, linterManager: LinterManager) -> WorkspaceModel: ...
    @overload
    def UpdateWithExtraWorkspaceViewInfo(self, workspaceViewInfo: ExtraWorkspaceViewInfo) -> None: ...
    @overload
    def UpdateWithExtraWorkspaceViewInfo(self, workspaceViewInfo: ExtraWorkspaceViewInfo, offsetX: float, offsetY: float) -> None: ...


class WorkspaceInfo:
    @overload
    def __init__(self, id: str, name: str, description: str, runType: RunType): ...
    @overload
    def __init__(self): ...
    @property
    def Version(self) -> str: ...
    @property
    def Description(self) -> str: ...
    @property
    def Category(self) -> str: ...
    @property
    def X(self) -> float: ...
    @property
    def Y(self) -> float: ...
    @property
    def Zoom(self) -> float: ...
    @property
    def ScaleFactor(self) -> float: ...
    @property
    def Name(self) -> str: ...
    @property
    def ID(self) -> str: ...
    @property
    def FileName(self) -> str: ...
    @property
    def RunType(self) -> RunType: ...
    @property
    def RunPeriod(self) -> int: ...
    @property
    def HasRunWithoutCrash(self) -> bool: ...
    @property
    def IsVisibleInDynamoLibrary(self) -> bool: ...
    @property
    def IsCustomNodeWorkspace(self) -> bool: ...


class ExtraWorkspaceViewInfo:
    def __init__(self): ...


class ExtraNodeViewInfo:
    def __init__(self): ...


class ExtraNoteViewInfo:
    def __init__(self): ...


class ExtraConnectorPinInfo:
    def __init__(self): ...


class ExtraAnnotationViewInfo:
    def __init__(self): ...
    def Equals(self, obj: Object) -> bool: ...


class WorkspaceSavedEvent:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, model: WorkspaceModel) -> None: ...
    def BeginInvoke(self, model: WorkspaceModel, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class PointEventHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, sender: Object, e: EventArgs) -> None: ...
    def BeginInvoke(self, sender: Object, e: EventArgs, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
