from typing import Tuple, Set, Iterable, List


class LogWarningMessageEventArgs:
    def __init__(self, msg: str): ...
    @property
    def message(self) -> str: ...


class LogWarningMessageEventHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, args: LogWarningMessageEventArgs) -> None: ...
    def BeginInvoke(self, args: LogWarningMessageEventArgs, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class LogWarningMessageEvents:
    def add_LogWarningMessage(value: LogWarningMessageEventHandler) -> None: ...
    def remove_LogWarningMessage(value: LogWarningMessageEventHandler) -> None: ...
    def OnLogWarningMessage(message: str) -> None: ...
    def OnLogInfoMessage(message: str) -> None: ...


class RegisterForTraceAttribute:
    def __init__(self): ...


class TraceUtils:
    def GetTraceData(key: str) -> str: ...
    def SetTraceData(key: str, value: str) -> None: ...


class Validity:
    def __init__(self): ...
    @overload
    def Assert(cond: bool) -> None: ...
    @overload
    def Assert(cond: bool, message: str) -> None: ...


class NodeInternalException:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, message: str): ...
    @overload
    def __init__(self, message: str, inner: Exception): ...
