from typing import Tuple, Set, Iterable, List


class IRenderPackage:
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @property
    def IsSelected(self) -> bool: ...
    @IsSelected.setter
    def IsSelected(self, value: bool) -> None: ...
    @property
    def HasRenderingData(self) -> bool: ...
    @property
    def DisplayLabels(self) -> bool: ...
    @DisplayLabels.setter
    def DisplayLabels(self, value: bool) -> None: ...
    @property
    def RequiresPerVertexColoration(self) -> bool: ...
    @RequiresPerVertexColoration.setter
    def RequiresPerVertexColoration(self, value: bool) -> None: ...
    @property
    def PointVertexCount(self) -> int: ...
    @property
    def LineVertexCount(self) -> int: ...
    @property
    def MeshVertexCount(self) -> int: ...
    @property
    def LineStripVertexCounts(self) -> Iterable[int]: ...
    @property
    def LineStripVertices(self) -> Iterable[float]: ...
    @property
    def LineStripVertexColors(self) -> Iterable[Byte]: ...
    @property
    def LineStripIndices(self) -> Iterable[int]: ...
    @property
    def MeshVertices(self) -> Iterable[float]: ...
    @property
    def MeshVertexColors(self) -> Iterable[Byte]: ...
    @property
    def MeshIndices(self) -> Iterable[int]: ...
    @property
    def MeshNormals(self) -> Iterable[float]: ...
    @property
    def MeshTextureCoordinates(self) -> Iterable[float]: ...
    @property
    def PointVertices(self) -> Iterable[float]: ...
    @property
    def PointVertexColors(self) -> Iterable[Byte]: ...
    @property
    def PointIndices(self) -> Iterable[int]: ...
    @property
    def Colors(self) -> Iterable[Byte]: ...
    @property
    def ColorsStride(self) -> int: ...
    @ColorsStride.setter
    def ColorsStride(self, value: int) -> None: ...
    def AddPointVertex(self, x: float, y: float, z: float) -> None: ...
    def AddPointVertexColor(self, red: Byte, green: Byte, blue: Byte, alpha: Byte) -> None: ...
    def AddTriangleVertex(self, x: float, y: float, z: float) -> None: ...
    def AddTriangleVertexNormal(self, x: float, y: float, z: float) -> None: ...
    def AddTriangleVertexUV(self, u: float, v: float) -> None: ...
    def AddTriangleVertexColor(self, red: Byte, green: Byte, blue: Byte, alpha: Byte) -> None: ...
    def AddLineStripVertex(self, x: float, y: float, z: float) -> None: ...
    def AddLineStripVertexCount(self, n: int) -> None: ...
    def AddLineStripVertexColor(self, red: Byte, green: Byte, blue: Byte, alpha: Byte) -> None: ...
    def ApplyPointVertexColors(self, colors: Set(Byte)) -> None: ...
    def ApplyLineVertexColors(self, colors: Set(Byte)) -> None: ...
    def ApplyMeshVertexColors(self, colors: Set(Byte)) -> None: ...
    def SetColors(self, colors: Set(Byte)) -> None: ...
    def Clear(self) -> None: ...


class IRenderPackageSupplement:
    @property
    def PointVertexColorCount(self) -> int: ...
    @property
    def LineVertexColorCount(self) -> int: ...
    @property
    def MeshVertexColorCount(self) -> int: ...
    def UpdatePointVertexColorForRange(self, startIndex: int, endIndex: int, red: Byte, green: Byte, blue: Byte, alpha: Byte) -> None: ...
    def AppendPointVertexColorRange(self, colors: Set(Byte)) -> None: ...
    def UpdateLineVertexColorForRange(self, startIndex: int, endIndex: int, red: Byte, green: Byte, blue: Byte, alpha: Byte) -> None: ...
    def AppendLineVertexColorRange(self, colors: Set(Byte)) -> None: ...
    def UpdateMeshVertexColorForRange(self, startIndex: int, endIndex: int, red: Byte, green: Byte, blue: Byte, alpha: Byte) -> None: ...
    def AppendMeshVertexColorRange(self, colors: Set(Byte)) -> None: ...
    @property
    def TextureMapsList(self) -> List: ...
    @property
    def TextureMapsStrideList(self) -> List: ...
    @property
    def MeshVerticesRangesAssociatedWithTextureMaps(self) -> List: ...
    def AddTextureMapForMeshVerticesRange(self, startIndex: int, endIndex: int, textureMap: Set(Byte), stride: int) -> None: ...
    @property
    def AllowLegacyColorOperations(self) -> bool: ...
    @AllowLegacyColorOperations.setter
    def AllowLegacyColorOperations(self, value: bool) -> None: ...


class IRenderLabels:
    @property
    def LabelData(self) -> List: ...
    @overload
    def AddLabel(self, label: str, vertexType: VertexType, index: int) -> None: ...
    @overload
    def AddLabel(self, label: str, x: float, y: float, z: float) -> None: ...
    @property
    def AutoGenerateLabels(self) -> bool: ...
    @AutoGenerateLabels.setter
    def AutoGenerateLabels(self, value: bool) -> None: ...
    def ClearLabels(self) -> None: ...


class IRenderInstancedLabels:
    def AddInstancedLabel(self, label: str, vertexType: VertexType, vertIndex: int, instanceIndex: int, BaseTessellationId: Guid) -> None: ...
    def InstanceCount(self, baseTessellationID: Guid) -> int: ...


class IInstancingRenderPackage:
    def ContainsTessellationId(self, id: Guid) -> bool: ...
    def AddInstanceGuidForMeshVertexRange(self, startIndex: int, endIndex: int, id: Guid) -> None: ...
    def AddInstanceGuidForLineVertexRange(self, startIndex: int, endIndex: int, id: Guid) -> None: ...
    @overload
    def AddInstanceMatrix(self, m11: Single, m12: Single, m13: Single, m14: Single, m21: Single, m22: Single, m23: Single, m24: Single, m31: Single, m32: Single, m33: Single, m34: Single, m41: Single, m42: Single, m43: Single, m44: Single, id: Guid) -> None: ...
    @overload
    def AddInstanceMatrix(self, matrix: Set(Single), id: Guid) -> None: ...


class VertexType:
    Point = 0
    Line = 1
    Mesh = 2
    MeshInstance = 3
    LineInstance = 4


class IGraphicItem:
    def Tessellate(self, package: IRenderPackage, parameters: TessellationParameters) -> None: ...


class ITransformable:
    @property
    def RequiresCustomTransform(self) -> bool: ...
    @RequiresCustomTransform.setter
    def RequiresCustomTransform(self, value: bool) -> None: ...
    @property
    def Transform(self) -> Set(float): ...
    @overload
    def SetTransform(self, m11: float, m12: float, m13: float, m14: float, m21: float, m22: float, m23: float, m24: float, m31: float, m32: float, m33: float, m34: float, m41: float, m42: float, m43: float, m44: float) -> None: ...
    @overload
    def SetTransform(self, matrix: Set(float)) -> None: ...


class IInstanceableGraphicItem:
    @property
    def BaseTessellationGuid(self) -> Guid: ...
    @property
    def InstanceInfoAvailable(self) -> bool: ...
    def AddBaseTessellation(self, package: IInstancingRenderPackage, parameters: TessellationParameters) -> None: ...
    def AddInstance(self, package: IInstancingRenderPackage, parameters: TessellationParameters, labelKey: str) -> None: ...


class TessellationParameters:
    def __init__(self): ...
    @property
    def Tolerance(self) -> float: ...
    @Tolerance.setter
    def Tolerance(self, value: float) -> None: ...
    @property
    def MaxTessellationDivisions(self) -> int: ...
    @MaxTessellationDivisions.setter
    def MaxTessellationDivisions(self, value: int) -> None: ...
    @property
    def ShowEdges(self) -> bool: ...
    @ShowEdges.setter
    def ShowEdges(self, value: bool) -> None: ...
    @property
    def UseRenderInstancing(self) -> bool: ...
    @UseRenderInstancing.setter
    def UseRenderInstancing(self, value: bool) -> None: ...


class IGraphicDataProvider:
    def GetGraphicItems(self, obj: Object) -> List: ...
    def Tessellate(self, objects: List, package: IRenderPackage, parameters: TessellationParameters) -> None: ...


class LegacyRenderPackageMethodException:
    def __init__(self): ...


class ExtensionStartupParams:
    @property
    def DisableADP(self) -> bool: ...
    @DisableADP.setter
    def DisableADP(self, value: bool) -> None: ...
