from typing import Tuple, Set, Iterable, List


class ConnectorType:
    BEZIER = 0
    POLYLINE = 1


class ConnectorModel(ModelBase):
    def __init__(self, start: PortModel, end: PortModel, guid: Guid): ...
    @property
    def IsHidden(self) -> bool: ...
    @IsHidden.setter
    def IsHidden(self, value: bool) -> None: ...
    @property
    def Start(self) -> PortModel: ...
    @property
    def End(self) -> PortModel: ...
    @property
    def ConnectorPinModels(self) -> ObservableCollection: ...
    @property
    def GUID(self) -> Guid: ...
    @GUID.setter
    def GUID(self, value: Guid) -> None: ...
    def op_Equality(lhs: ConnectorModel, rhs: ConnectorModel) -> bool: ...
    def op_Inequality(lhs: ConnectorModel, rhs: ConnectorModel) -> bool: ...
    def add_Deleted(self, value: Action) -> None: ...
    def remove_Deleted(self, value: Action) -> None: ...
