from typing import Tuple, Set, Iterable, List


class NoteModel(ModelBase):
    @overload
    def __init__(self, x: float, y: float, text: str, guid: Guid): ...
    @overload
    def __init__(self, x: float, y: float, text: str, guid: Guid, pinnedNode: NodeModel): ...
    @property
    def Text(self) -> str: ...
    @Text.setter
    def Text(self, value: str) -> None: ...
    @property
    def PinnedNode(self) -> NodeModel: ...
    @PinnedNode.setter
    def PinnedNode(self, value: NodeModel) -> None: ...
    @property
    def PinnedNodeGuid(self) -> Guid: ...
    @PinnedNodeGuid.setter
    def PinnedNodeGuid(self, value: Guid) -> None: ...
    @property
    def UndoRedoAction(self) -> UndoAction: ...
    @UndoRedoAction.setter
    def UndoRedoAction(self, value: UndoAction) -> None: ...


class UndoAction:
    Pin = 0
    Unpin = 1
