from typing import Tuple, Set, Iterable, List


class ISelectable:
    @property
    def IsSelected(self) -> bool: ...
    @IsSelected.setter
    def IsSelected(self, value: bool) -> None: ...
    def Select(self) -> None: ...
    def Deselect(self) -> None: ...
