from typing import Tuple, Set, Iterable, List


class ILibraryViewCustomization:
    def add_SpecificationUpdated(self, value: EventHandler) -> None: ...
    def remove_SpecificationUpdated(self, value: EventHandler) -> None: ...
    def GetSpecification(self) -> LayoutSpecification: ...
    def SetSpecification(self, specification: LayoutSpecification) -> None: ...
    def ToJSONStream(self) -> Stream: ...
    def AddSections(self, sections: Iterable[LayoutSection]) -> bool: ...
    def AddElements(self, elements: Iterable[LayoutElement], sectionText: str) -> bool: ...
    def AddIncludeInfo(self, includes: Iterable[LayoutIncludeInfo], sectionText: str) -> bool: ...
    def RegisterResourceStream(self, urlpath: str, resource: Stream) -> bool: ...
    def OnAppShutdown(self) -> None: ...


class LayoutSpecification:
    def __init__(self): ...
    @property
    def sections(self) -> List: ...
    @sections.setter
    def sections(self, value: List) -> None: ...
    def ToJSONStream(self) -> Stream: ...
    def FromJSONString(jsonText: str) -> LayoutSpecification: ...
    def FromJSONStream(stream: Stream) -> LayoutSpecification: ...
    def Clone(self) -> LayoutSpecification: ...


class LayoutIncludeInfo:
    def __init__(self): ...
    @property
    def path(self) -> str: ...
    @path.setter
    def path(self, value: str) -> None: ...
    @property
    def iconUrl(self) -> str: ...
    @iconUrl.setter
    def iconUrl(self, value: str) -> None: ...
    @property
    def inclusive(self) -> bool: ...
    @inclusive.setter
    def inclusive(self, value: bool) -> None: ...


class LayoutElementType:
    section = 0
    category = 1
    group = 2
    create = 3
    action = 4
    query = 5
    none = 6
    classType = 7


class LayoutElement:
    def __init__(self, text: str): ...
    @property
    def text(self) -> str: ...
    @text.setter
    def text(self, value: str) -> None: ...
    @property
    def iconUrl(self) -> str: ...
    @iconUrl.setter
    def iconUrl(self, value: str) -> None: ...
    @property
    def elementType(self) -> LayoutElementType: ...
    @elementType.setter
    def elementType(self, value: LayoutElementType) -> None: ...
    @property
    def include(self) -> List: ...
    @include.setter
    def include(self, value: List) -> None: ...
    @property
    def childElements(self) -> List: ...
    @childElements.setter
    def childElements(self, value: List) -> None: ...
    def EnumerateIncludes(self) -> Iterable[LayoutIncludeInfo]: ...
    def EnumerateChildren(self) -> Iterable[LayoutElement]: ...


class LayoutSection(LayoutElement):
    def __init__(self, text: str): ...
    @property
    def showHeader(self) -> bool: ...
    @showHeader.setter
    def showHeader(self, value: bool) -> None: ...
