from typing import Tuple, Set, Iterable, List


class AsyncTaskCompletedHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, asyncTask: AsyncTask) -> None: ...
    def BeginInvoke(self, asyncTask: AsyncTask, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class AsyncTask:
    @property
    def Priority(self) -> TaskPriority: ...
    def add_Completed(self, value: AsyncTaskCompletedHandler) -> None: ...
    def remove_Completed(self, value: AsyncTaskCompletedHandler) -> None: ...


class AsyncTaskExtensions:
    def Then(task: AsyncTask, action: AsyncTaskCompletedHandler) -> IDisposable: ...
    def ThenPost(task: AsyncTask, action: AsyncTaskCompletedHandler, context: SynchronizationContext) -> IDisposable: ...
    def ThenSend(task: AsyncTask, action: AsyncTaskCompletedHandler, context: SynchronizationContext) -> IDisposable: ...
    def AllComplete(tasks: Iterable[AsyncTask], action: Action) -> IDisposable: ...


class DelegateBasedAsyncTask(AsyncTask):
    @overload
    def __init__(self, scheduler: IScheduler): ...
    @overload
    def __init__(self, scheduler: IScheduler, action: Action): ...
    @property
    def Priority(self) -> TaskPriority: ...


class TaskStateChangedEventArgs:


class TaskStateChangedEventHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, sender: DynamoScheduler, e: TaskStateChangedEventArgs) -> None: ...
    def BeginInvoke(self, sender: DynamoScheduler, e: TaskStateChangedEventArgs, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class IScheduler:
    @property
    def NextTimeStamp(self) -> TimeStamp: ...
    def ProcessNextTask(self, waitIfTaskQueueIsEmpty: bool) -> bool: ...
    def ScheduleForExecution(self, asyncTask: AsyncTask) -> None: ...
    @property
    def Tasks(self) -> Iterable[AsyncTask]: ...


class TaskProcessMode:
    Synchronous = 0
    Asynchronous = 1


class DynamoScheduler:
    @property
    def NextTimeStamp(self) -> TimeStamp: ...
    def ScheduleForExecution(self, asyncTask: AsyncTask) -> None: ...
    @property
    def ProcessMode(self) -> TaskProcessMode: ...
    @ProcessMode.setter
    def ProcessMode(self, value: TaskProcessMode) -> None: ...
    def ProcessNextTask(self, waitIfTaskQueueIsEmpty: bool) -> bool: ...
    @property
    def Tasks(self) -> Iterable[AsyncTask]: ...
    @property
    def HasTaskInProgress(self) -> bool: ...
    @property
    def HasPendingTasks(self) -> bool: ...


class ISchedulerThread:
    def Initialize(self, owningScheduler: IScheduler) -> None: ...
    def Shutdown(self) -> None: ...


class TimeStamp:
    def Equals(self, other: Object) -> bool: ...
    def GetHashCode(self) -> int: ...
    def op_GreaterThan(timeStamp0: TimeStamp, timeStamp1: TimeStamp) -> bool: ...
    def op_LessThan(timeStamp0: TimeStamp, timeStamp1: TimeStamp) -> bool: ...


class TaskPriority:
    Critical = 0
    Highest = 1
    AboveNormal = 2
    Normal = 3
    BelowNormal = 4
    Lowest = 5
    Idle = 6


class TaskMergeInstruction:
    KeepBoth = 0
    KeepThis = 1
    KeepOther = 2


class State:
    Scheduled = 0
    Discarded = 1
    ExecutionStarting = 2
    ExecutionFailed = 3
    ExecutionCompleted = 4
    CompletionHandled = 5
