from typing import Tuple, Set, Iterable, List


class ExecutionStateHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, session: IExecutionSession) -> None: ...
    def BeginInvoke(self, session: IExecutionSession, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class ExecutionEvents:
    def add_GraphPreExecution(value: ExecutionStateHandler) -> None: ...
    def remove_GraphPreExecution(value: ExecutionStateHandler) -> None: ...
    def add_GraphPostExecution(value: ExecutionStateHandler) -> None: ...
    def remove_GraphPostExecution(value: ExecutionStateHandler) -> None: ...
    @property
    def ActiveSession() -> IExecutionSession: ...


class WorkspaceAddedEventHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, args: WorkspacesModificationEventArgs) -> None: ...
    def BeginInvoke(self, args: WorkspacesModificationEventArgs, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class WorkspaceRemoveStartedEventHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, args: WorkspacesModificationEventArgs) -> None: ...
    def BeginInvoke(self, args: WorkspacesModificationEventArgs, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class WorkspaceRemovedEventHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, args: WorkspacesModificationEventArgs) -> None: ...
    def BeginInvoke(self, args: WorkspacesModificationEventArgs, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class WorkspaceSettingsChangedEventHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, args: WorkspacesSettingsChangedEventArgs) -> None: ...
    def BeginInvoke(self, args: WorkspacesSettingsChangedEventArgs, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class WorkspaceClearingEventHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self) -> None: ...
    def BeginInvoke(self, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class WorkspaceClearedEventHandler:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self) -> None: ...
    def BeginInvoke(self, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...


class WorkspaceEvents:
    def add_WorkspaceAdded(value: WorkspaceAddedEventHandler) -> None: ...
    def remove_WorkspaceAdded(value: WorkspaceAddedEventHandler) -> None: ...
    def add_WorkspaceRemoveStarted(value: WorkspaceRemoveStartedEventHandler) -> None: ...
    def remove_WorkspaceRemoveStarted(value: WorkspaceRemoveStartedEventHandler) -> None: ...
    def add_WorkspaceRemoved(value: WorkspaceRemovedEventHandler) -> None: ...
    def remove_WorkspaceRemoved(value: WorkspaceRemovedEventHandler) -> None: ...
    def add_WorkspaceClearing(value: WorkspaceClearingEventHandler) -> None: ...
    def remove_WorkspaceClearing(value: WorkspaceClearingEventHandler) -> None: ...
    def add_WorkspaceCleared(value: WorkspaceClearedEventHandler) -> None: ...
    def remove_WorkspaceCleared(value: WorkspaceClearedEventHandler) -> None: ...
    def add_WorkspaceSettingsChanged(value: WorkspaceSettingsChangedEventHandler) -> None: ...
    def remove_WorkspaceSettingsChanged(value: WorkspaceSettingsChangedEventHandler) -> None: ...


class WorkspacesModificationEventArgs:
    def __init__(self, id: Guid, name: str, type: Type): ...
    @property
    def Id(self) -> Guid: ...
    @property
    def Name(self) -> str: ...
    @property
    def Type(self) -> Type: ...


class WorkspacesSettingsChangedEventArgs:
    def __init__(self, scaleFactor: float): ...
    @property
    def ScaleFactor(self) -> float: ...
