from typing import Tuple, Set, Iterable, List


class Color:
    @property
    def Red(self) -> Byte: ...
    @property
    def Green(self) -> Byte: ...
    @property
    def Blue(self) -> Byte: ...
    @property
    def Alpha(self) -> Byte: ...
    def ByARGB(alpha: int, red: int, green: int, blue: int) -> Color: ...
    def Brightness(color: Color) -> Single: ...
    def Saturation(color: Color) -> Single: ...
    def Hue(color: Color) -> Single: ...
    def Components(color: Color) -> Dictionary: ...
    def BuildColorFrom1DRange(colors: List, parameters: List, parameter: float) -> Color: ...
    def BuildColorFrom2DRange(colors: List[Color], parameters: List[UV], parameter: UV) -> Color: ...
    def Lerp(start: Color, end: Color, t: float) -> Color: ...
    def Blerp(colors: List[Color+IndexedColor2D], parameter: UV) -> Color: ...
    def ToString(self) -> str: ...
    def Equals(self, obj: Object) -> bool: ...
    def Add(color: Color, otherColor: Color) -> Color: ...
    def Multiply(color: Color, multiplier: float) -> Color: ...
    def Divide(color: Color, dividend: float) -> Color: ...
    def GetHashCode(self) -> int: ...


class ColorRange1D:
    @property
    def IndexedColors(self) -> Iterable[IndexedColor1D]: ...
    def ByColorsAndParameters(colors: List, parameters: List) -> ColorRange1D: ...
    def GetColorAtParameter(colorRange: ColorRange1D, parameter: float) -> Color: ...
    def Default() -> ColorRange1D: ...
    def ToString(self) -> str: ...


class DefaultColorRanges:


class ColorRange:
    def ByColorsAndParameters(colors: List[Color], parameters: List[UV]) -> ColorRange: ...
    def GetColorAtParameter(self, parameter: UV) -> Color: ...


class Compare:
    def GreaterThan(a: Object, b: Object) -> bool: ...
    def GreaterThanOrEqual(a: Object, b: Object) -> bool: ...
    def LessThan(a: Object, b: Object) -> bool: ...
    def LessThanOrEqual(a: Object, b: Object) -> bool: ...


class Data:
    def ParseJSON(json: str) -> Object: ...
    def StringifyJSON(values: Object) -> str: ...
    def CanObjectBeCached(inputObject: Object) -> bool: ...
    def Remember(inputObject: Object, cachedJson: str) -> Dictionary: ...
    def SafeExtractDictionaryValue(dict: Dictionary, key: str) -> Object: ...
    def EvaluateDefineDataNode(inputValue: Object, typeString: str, isList: bool, isAutoMode: bool, playerValue: str) -> Dictionary: ...


class DateTime:
    @property
    def MinValue() -> DateTime: ...
    @property
    def MaxValue() -> DateTime: ...
    @property
    def Now() -> DateTime: ...
    @property
    def Today() -> DateTime: ...
    def Format(dateTime: DateTime, format: str) -> str: ...
    def ByDate(year: int, month: int, day: int) -> DateTime: ...
    def ByDateAndTime(year: int, month: int, day: int, hour: int, minute: int, second: int, millisecond: int) -> DateTime: ...
    def SubtractTimeSpan(dateTime: DateTime, timeSpan: TimeSpan) -> DateTime: ...
    def AddTimeSpan(dateTime: DateTime, timeSpan: TimeSpan) -> DateTime: ...
    def DaysInMonth(year: int, month: int) -> int: ...
    def IsDaylightSavingsTime(dateTime: DateTime) -> bool: ...
    def IsLeapYear(year: int) -> bool: ...
    def FromString(string: str) -> DateTime: ...
    def Date(dateTime: DateTime) -> DateTime: ...
    def Components(dateTime: DateTime) -> Dictionary: ...
    def DayOfWeek(dateTime: DateTime) -> DayOfWeek: ...
    def DayOfYear(dateTime: DateTime) -> int: ...
    def TimeOfDay(dateTime: DateTime) -> TimeSpan: ...


class DayOfWeek:
    Sunday = 0
    Monday = 1
    Tuesday = 2
    Wednesday = 3
    Thursday = 4
    Friday = 5
    Saturday = 6


class TimeSpan:
    def ByDateDifference(dateTime: DateTime, otherDateTime: DateTime) -> TimeSpan: ...
    @property
    def Zero() -> TimeSpan: ...
    @property
    def MaxValue() -> TimeSpan: ...
    @property
    def MinValue() -> TimeSpan: ...
    def Create(days: float, hours: float, minutes: float, seconds: float, milliseconds: float) -> TimeSpan: ...
    def Scale(timeSpan: TimeSpan, scaleFactor: float) -> TimeSpan: ...
    def Negate(timeSpan: TimeSpan) -> TimeSpan: ...
    def Add(timeSpan1: TimeSpan, timeSpan2: TimeSpan) -> TimeSpan: ...
    def Subtract(timeSpan1: TimeSpan, timeSpan2: TimeSpan) -> TimeSpan: ...
    def FromString(string: str) -> TimeSpan: ...
    def Components(timeSpan: TimeSpan) -> Dictionary: ...
    def TotalDays(timeSpan: TimeSpan) -> float: ...
    def TotalHours(timeSpan: TimeSpan) -> float: ...
    def TotalMinutes(timeSpan: TimeSpan) -> float: ...
    def TotalSeconds(timeSpan: TimeSpan) -> float: ...
    def TotalMilliseconds(timeSpan: TimeSpan) -> float: ...


class List:
    @property
    def Empty() -> IList: ...
    def UniqueItems(list: IList) -> IList: ...
    def Contains(list: IList, item: Object) -> bool: ...
    def IsHomogeneous(list: IList) -> bool: ...
    def IsRectangular(list: IList) -> bool: ...
    def IsUniformDepth(list: IList) -> bool: ...
    def SetDifference(list1: List[Object], list2: List[Object]) -> IList: ...
    def SetIntersection(list1: List[Object], list2: List[Object]) -> IList: ...
    def SetUnion(list1: List[Object], list2: List[Object]) -> IList: ...
    def IndexOf(list: IList, element: Object) -> Nullable: ...
    def CountFalse(list: IList) -> int: ...
    def CountTrue(list: IList) -> int: ...
    def Insert(list: IList, element: Object, index: int) -> IList: ...
    def Reorder(list: IList, indices: IList) -> IList: ...
    def SortIndexByValue(list: List) -> IEnumerable: ...
    def NormalizeDepth(list: IList, rank: int) -> IList: ...
    def Reverse(list: IList) -> IList: ...
    def __Create(items: IList) -> IList: ...
    def Sublists(list: IList, ranges: IList, offset: int) -> IList: ...
    def Sort(list: Iterable[Object]) -> IList: ...
    def MinimumItem(list: Iterable[Object]) -> Object: ...
    def MaximumItem(list: Iterable[Object]) -> Object: ...
    def FilterByBoolMask(list: IList, mask: IList) -> Dictionary: ...
    def Deconstruct(list: IList) -> IDictionary: ...
    def SortByKey(list: IList, keys: IList) -> IDictionary: ...
    def GroupByKey(list: IList, keys: IList) -> IDictionary: ...
    def AddItemToFront(item: Object, list: IList) -> IList: ...
    def AddItemToEnd(item: Object, list: IList) -> IList: ...
    def TakeItems(list: IList, amount: int) -> IList: ...
    def DropItems(list: IList, amount: int) -> IList: ...
    def ShiftIndices(list: IList, amount: int) -> IList: ...
    def GetItemAtIndex(list: IList, index: int) -> Object: ...
    def ReplaceItemAtIndex(list: IList, index: int, item: Object) -> IList: ...
    def Slice(list: IList, start: Nullable, end: Nullable, step: int) -> IList: ...
    def RemoveItemAtIndex(list: IList, indices: Set(int)) -> IList: ...
    def DropEveryNthItem(list: IList, n: int, offset: int) -> IList: ...
    def TakeEveryNthItem(list: IList, n: int, offset: int) -> IList: ...
    def IsEmpty(list: IList) -> bool: ...
    def AllTrue(list: IList) -> bool: ...
    def AllFalse(list: IList) -> bool: ...
    def AnyTrue(list: IList) -> bool: ...
    def AnyFalse(list: IList) -> bool: ...
    def Count(list: IList) -> int: ...
    def Join(lists: Set(IList)) -> IList: ...
    def FirstItem(list: IList) -> Object: ...
    def RestOfItems(list: IList) -> IList: ...
    def Chop(list: IList, lengths: List) -> IList: ...
    def DiagonalRight(list: IList, subLength: int) -> IList: ...
    def DiagonalLeft(list: IList, rowLength: int) -> IList: ...
    def Transpose(lists: IList) -> IList: ...
    def Clean(list: IList, preserveIndices: bool) -> IList: ...
    def OfRepeatedItem(item: Object, amount: int) -> IList: ...
    def Cycle(list: IList, amount: int) -> IList: ...
    def Repeat(list: IList, amount: int) -> IList: ...
    def LastItem(list: IList) -> Object: ...
    @overload
    def Shuffle(list: IList) -> IList: ...
    @overload
    def Shuffle(list: IList, seed: int) -> IList: ...
    def Permutations(list: IList, length: Nullable) -> IList: ...
    def Combinations(list: IList, length: int, replace: bool) -> IList: ...
    def FirstIndexOf(list: IList, item: Object) -> int: ...
    def AllIndicesOf(list: IList, item: Object) -> IList: ...
    def Flatten(list: IList, amount: int) -> IList: ...


class Math:
    @overload
    def Random(seed: Nullable) -> float: ...
    @overload
    def Random(value1: float, value2: float) -> float: ...
    @overload
    def Random(value1: float, value2: float, seed: int) -> float: ...
    @overload
    def RandomList(amount: int) -> IList: ...
    @overload
    def RandomList(amount: int, value1: float, value2: float, seed: int) -> IList: ...
    @property
    def PiTimes2() -> float: ...
    def Average(numbers: List[float]) -> float: ...
    def Map(rangeMin: float, rangeMax: float, inputValue: float) -> float: ...
    def MapTo(rangeMin: float, rangeMax: float, inputValue: float, targetRangeMin: float, targetRangeMax: float) -> float: ...
    def RemapRange(numbers: List[float], newMin: float, newMax: float) -> IList: ...
    @property
    def PI() -> float: ...
    @property
    def E() -> float: ...
    @property
    def GoldenRatio() -> float: ...
    def RadiansToDegrees(radians: float) -> float: ...
    def DegreesToRadians(degrees: float) -> float: ...
    @overload
    def Abs(number: float) -> float: ...
    @overload
    def Equals(lhs: float, rhs: float, tol: float) -> bool: ...
    @overload
    def Abs(integer: Int64) -> Int64: ...
    def Acos(ratio: float) -> float: ...
    def Asin(ratio: float) -> float: ...
    def Atan(ratio: float) -> float: ...
    def Atan2(numerator: float, denominator: float) -> float: ...
    def Ceiling(number: float) -> Int64: ...
    def Cos(angle: float) -> float: ...
    def Cosh(angle: float) -> float: ...
    def DivRem(dividend: Int64, divisor: Int64) -> Int64: ...
    def EvaluateFormula(formulaString: str, parameters: Set(str), arguments: Set(Object)) -> Object: ...
    def Exp(number: float) -> float: ...
    def Floor(number: float) -> Int64: ...
    def IEEERemainder(value1: float, value2: float) -> float: ...
    @overload
    def Log(number: float) -> float: ...
    @overload
    def Log(number: float, logBase: float) -> float: ...
    def Log10(number: float) -> float: ...
    @overload
    def Max(value1: float, value2: float) -> float: ...
    @overload
    def Max(int1: Int64, int2: Int64) -> Int64: ...
    @overload
    def Min(value1: float, value2: float) -> float: ...
    @overload
    def Min(int1: Int64, int2: Int64) -> Int64: ...
    def Pow(number: float, power: float) -> float: ...
    def Rand() -> float: ...
    @overload
    def Round(number: float) -> float: ...
    @overload
    def Round(number: float, digits: int) -> float: ...
    @overload
    def Sign(number: float) -> Int64: ...
    @overload
    def Sign(int: Int64) -> Int64: ...
    def Sin(angle: float) -> float: ...
    def Sinh(angle: float) -> float: ...
    def Sqrt(number: float) -> float: ...
    def Tan(angle: float) -> float: ...
    def Tanh(angle: float) -> float: ...
    def Truncate(value: float) -> float: ...
    def Sum(values: Iterable[float]) -> float: ...
    def Factorial(number: Int64) -> Int64: ...
    def Xor(bool: bool, otherBool: bool) -> bool: ...


class Object:
    def IsNull(object: Object) -> bool: ...
    def Identity(object: Object) -> Object: ...
    def Type(object: Object) -> str: ...


class BoundaryConditionHelper:
    def __init__(self): ...
    def BoundaryConditionFromString(val: str) -> PanelSurfaceBoundaryCondition: ...


class PythonEvaluator:
    def __init__(self): ...
    def Evaluate(engineName: str, code: str, bindingNames: IList, bindingValues: IList) -> Object: ...


class Quadtree:
    @property
    def Root(self) -> Node: ...
    @Root.setter
    def Root(self, value: Node) -> None: ...
    def ByUVs(uvs: Iterable[UV]) -> Quadtree: ...
    def FindPointsWithinRadius(self, center: UV, radius: float) -> List: ...
    def FindPointsInRectangle(self, rectangle: UVRect) -> List: ...


class Node:
    def __init__(self, min: UV, max: UV): ...
    @property
    def Parent(self) -> Node: ...
    @property
    def NW(self) -> Node: ...
    @property
    def NE(self) -> Node: ...
    @property
    def SW(self) -> Node: ...
    @property
    def SE(self) -> Node: ...
    @property
    def Point(self) -> UV: ...
    @Point.setter
    def Point(self, value: UV) -> None: ...
    @property
    def Bounds(self) -> UVRect: ...
    @Bounds.setter
    def Bounds(self, value: UVRect) -> None: ...
    @property
    def Item(self) -> Object: ...
    @Item.setter
    def Item(self, value: Object) -> None: ...
    @property
    def IsLeafNode(self) -> bool: ...
    def Contains(self, uv: UV) -> bool: ...
    def Insert(self, uv: UV) -> None: ...
    def TryFind(self, uv: UV) -> Tuple[bool, Node]: ...
    def GetAllNodes(self) -> List: ...
    def FindAllNodesUpLevel(self, count: int) -> List: ...
    def FindNodeWhichContains(self, point: UV) -> Node: ...
    def FindNodesWithinRadius(self, location: UV, radius: float) -> List: ...
    def FindNodesIntersectingRectangle(self, rectangle: UVRect) -> List: ...


class UVRect:
    def __init__(self, min: UV, max: UV): ...
    @property
    def Min(self) -> UV: ...
    @Min.setter
    def Min(self, value: UV) -> None: ...
    @property
    def Max(self) -> UV: ...
    @Max.setter
    def Max(self, value: UV) -> None: ...
    @property
    def Width(self) -> float: ...
    @property
    def Height(self) -> float: ...
    @property
    def CenterPoint(self) -> UV: ...
    def Contains(self, uv: UV) -> bool: ...
    def Intersects(self, rect: UVRect) -> bool: ...


class Sorting:
    def minByKey(list: IList, keys: IList) -> Object: ...
    def maxByKey(list: IList, keys: IList) -> Object: ...
    def sortByKey(list: IList, keys: IList) -> IList: ...
    def groupByKey(list: IList, keys: IList) -> IList: ...


class String:
    def FromObject(obj: Object) -> str: ...
    def ToNumber(string: str) -> Object: ...
    def GetNumber(string: str) -> str: ...
    def Concat(strings: Set(str)) -> str: ...
    def Length(string: str) -> int: ...
    def Split(string: str, separators: Set(str)) -> Set(str): ...
    def Join(separator: str, strings: Set(str)) -> str: ...
    def ToUpper(string: str) -> str: ...
    def ToLower(string: str) -> str: ...
    def ToTitle(str: str) -> str: ...
    def ChangeCase(string: str, upper: bool) -> str: ...
    def Substring(string: str, startIndex: int, length: int) -> str: ...
    def Contains(string: str, searchFor: str, ignoreCase: bool) -> bool: ...
    def CountOccurrences(string: str, searchFor: str, ignoreCase: bool) -> int: ...
    def Replace(string: str, searchFor: str, replaceWith: str) -> str: ...
    def EndsWith(string: str, searchFor: str, ignoreCase: bool) -> bool: ...
    def StartsWith(string: str, searchFor: str, ignoreCase: bool) -> bool: ...
    def TrimWhitespace(string: str) -> str: ...
    def TrimLeadingWhitespace(string: str) -> str: ...
    def TrimTrailingWhitespace(string: str) -> str: ...
    def IndexOf(string: str, searchFor: str, ignoreCase: bool) -> int: ...
    def AllIndicesOf(string: str, searchFor: str, ignoreCase: bool) -> Set(int): ...
    def LastIndexOf(string: str, searchFor: str, ignoreCase: bool) -> int: ...
    def PadLeft(string: str, newLength: int, padChars: str) -> str: ...
    def PadRight(string: str, newLength: int, padChars: str) -> str: ...
    def Center(string: str, newLength: int, padChars: str) -> str: ...
    def Insert(string: str, index: int, toInsert: str) -> str: ...
    def Remove(string: str, startIndex: int, count: Nullable) -> str: ...


class Thread:
    def Pause(object: Object, msTimeout: int) -> Object: ...


class Types:
    def __init__(self): ...
    def FindTypeByNameInAssembly(typeName: str, assemblyName: str) -> Type: ...


class Web:
    def __init__(self): ...
    def WebRequestByUrl(url: str) -> str: ...


class IndexedColor1D:
    def __init__(self, color: Color, parameter: float): ...
    @property
    def Color(self) -> Color: ...
    @Color.setter
    def Color(self, value: Color) -> None: ...
    @property
    def Parameter(self) -> float: ...
    @Parameter.setter
    def Parameter(self, value: float) -> None: ...
    def CompareTo(self, obj: Object) -> int: ...


class IndexedColor2D:
    def __init__(self, color: Color, parameter: UV): ...
    @property
    def Color(self) -> Color: ...
    @Color.setter
    def Color(self, value: Color) -> None: ...
    @property
    def Parameter(self) -> UV: ...
    @Parameter.setter
    def Parameter(self, value: UV) -> None: ...
