from typing import Tuple, Set, Iterable, List


class SupressImportIntoVMAttribute:
    def __init__(self): ...


class IsVisibleInDynamoLibraryAttribute:
    def __init__(self, visible: bool): ...
    @property
    def Visible(self) -> bool: ...


class ArbitraryDimensionArrayImportAttribute:
    def __init__(self): ...


class GraphicDataProviderAttribute:
    def __init__(self, providerType: Type): ...
    @property
    def Type(self) -> Type: ...


class AllowRankReductionAttribute:
    def __init__(self): ...
    def ReduceRank(self, collection: Object) -> Object: ...
    def IsRankReducible(collection: Object) -> bool: ...


class MultiReturnAttribute:
    def __init__(self, returnKeys: Set(str)): ...
    @property
    def ReturnKeys(self) -> Set(str): ...
    @ReturnKeys.setter
    def ReturnKeys(self, value: Set(str)) -> None: ...


class RuntimeRequirementAttribute:
    def __init__(self): ...
    @property
    def RequireTracing(self) -> bool: ...
    @RequireTracing.setter
    def RequireTracing(self, value: bool) -> None: ...


class DefaultArgumentAttribute:
    def __init__(self, defaultArgumentExpression: str): ...
    @property
    def ArgumentExpression(self) -> str: ...


class CanUpdatePeriodicallyAttribute:
    def __init__(self, canUpdatePeriodically: bool): ...
    @property
    def CanUpdatePeriodically(self) -> bool: ...


class PreferredShortNameAttribute:
    def __init__(self, preferredShortName: str): ...
    @property
    def PreferredShortName(self) -> str: ...


class IsObsoleteAttribute:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, message: str): ...
    @overload
    def __init__(self, descriptionResourceID: str, resourceType: Type): ...
    @overload
    def __init__(self, descriptionResourceID: str, typeName: str): ...
    @property
    def Message(self) -> str: ...


class KeepReferenceAttribute:
    def __init__(self): ...


class KeepReferenceThisAttribute:
    def __init__(self): ...


class IsLacingDisabledAttribute:
    def __init__(self): ...


class AllowArrayPromotionAttribute:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, isAllowed: bool): ...
    @property
    def IsAllowed(self) -> bool: ...
