from typing import Tuple, Set, Iterable, List


class ConnectorPinModel(ModelBase):
    def __init__(self, x: float, y: float, id: Guid, connectorId: Guid): ...
    @property
    def ConnectorId(self) -> Guid: ...
    @ConnectorId.setter
    def ConnectorId(self, value: Guid) -> None: ...
    @property
    def StaticWidth() -> float: ...
    @property
    def Height(self) -> float: ...
    @property
    def Width(self) -> float: ...


class SaveContext:
    File = 0
    Copy = 1
    Undo = 2
    Preset = 3
    #None = 4
    Save = 5
    SaveAs = 6


class UpdateValueParams:
    def __init__(self, propertyName: str, propertyValue: str, elementResolver: ElementResolver): ...
    @property
    def PropertyName(self) -> str: ...
    @property
    def PropertyValue(self) -> str: ...
    @property
    def ElementResolver(self) -> ElementResolver: ...


class ModelBase(NotificationObject):
    def add_Disposed(self, value: Action) -> None: ...
    def remove_Disposed(self, value: Action) -> None: ...
    def add_DeletionStarted(self, value: EventHandler) -> None: ...
    def remove_DeletionStarted(self, value: EventHandler) -> None: ...
    @property
    def CenterX(self) -> float: ...
    @CenterX.setter
    def CenterX(self, value: float) -> None: ...
    @property
    def CenterY(self) -> float: ...
    @CenterY.setter
    def CenterY(self, value: float) -> None: ...
    @property
    def X(self) -> float: ...
    @X.setter
    def X(self, value: float) -> None: ...
    def ShouldSerializeX(self) -> bool: ...
    @property
    def Y(self) -> float: ...
    @Y.setter
    def Y(self, value: float) -> None: ...
    def ShouldSerializeY(self) -> bool: ...
    @property
    def Position(self) -> Point2D: ...
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> None: ...
    @property
    def Width(self) -> float: ...
    @Width.setter
    def Width(self, value: float) -> None: ...
    @property
    def Rect(self) -> Rect2D: ...
    @property
    def IsSelected(self) -> bool: ...
    @IsSelected.setter
    def IsSelected(self, value: bool) -> None: ...
    @property
    def GUID(self) -> Guid: ...
    @GUID.setter
    def GUID(self, value: Guid) -> None: ...
    def Select(self) -> None: ...
    def Deselect(self) -> None: ...
    def ReportPosition(self) -> None: ...
    def SetSize(self, w: float, h: float) -> None: ...
    def Dispose(self) -> None: ...
    def OnDeletionStarted(self, e: CancelEventArgs) -> None: ...
    def UpdateValue(self, updateValueParams: UpdateValueParams) -> bool: ...
    def Serialize(self, xmlDocument: XmlDocument, context: SaveContext) -> XmlElement: ...
    def Deserialize(self, element: XmlElement, context: SaveContext) -> None: ...
    def add_MessageLogged(self, value: Action) -> None: ...
    def remove_MessageLogged(self, value: Action) -> None: ...


class ILocatable:
    @property
    def X(self) -> float: ...
    @X.setter
    def X(self, value: float) -> None: ...
    @property
    def Y(self) -> float: ...
    @Y.setter
    def Y(self, value: float) -> None: ...
    @property
    def Width(self) -> float: ...
    @Width.setter
    def Width(self, value: float) -> None: ...
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> None: ...
    @property
    def Rect(self) -> Rect2D: ...
    @property
    def CenterX(self) -> float: ...
    @CenterX.setter
    def CenterX(self, value: float) -> None: ...
    @property
    def CenterY(self) -> float: ...
    @CenterY.setter
    def CenterY(self, value: float) -> None: ...
    def ReportPosition(self) -> None: ...


class NodeGraph:
    @property
    def Nodes(self) -> List: ...
    @property
    def Connectors(self) -> List: ...
    @property
    def Notes(self) -> List: ...
    @property
    def Annotations(self) -> List: ...
    @property
    def ElementResolver(self) -> ElementResolver: ...
    @property
    def Presets(self) -> List: ...
    def LoadNodeFromXml(elNode: XmlElement, context: SaveContext, nodeFactory: NodeFactory, resolver: ElementResolver) -> NodeModel: ...
    def LoadConnectorFromXml(connEl: XmlElement, nodes: IDictionary) -> ConnectorModel: ...
    def LoadNoteFromXml(note: XmlNode) -> NoteModel: ...
    def LoadPresetsFromXml(xmlDoc: XmlDocument, nodesInNodeGraph: Iterable[NodeModel]) -> Iterable[PresetModel]: ...
    def LoadGraphFromXml(xmlDoc: XmlDocument, nodeFactory: NodeFactory) -> NodeGraph: ...
