from typing import Tuple, Set, Iterable, List


class AreaPlanView(PlanView):
    def ByLevelAndAreaScheme(level: Level, areaScheme: Element) -> AreaPlanView: ...


class AxonometricView(View3D):
    def ByEyePointAndTarget(eyePoint: Point, target: Point, name: str) -> AxonometricView: ...
    def ByEyePointTargetAndElement(eyePoint: Point, target: Point, name: str, element: Element, isolateElement: bool) -> AxonometricView: ...
    def ByEyePointTargetAndBoundingBox(eyePoint: Point, target: Point, boundingBox: BoundingBox, name: str, isolateElement: bool) -> AxonometricView: ...


class CeilingPlanView(PlanView):
    def ByLevel(level: Level) -> CeilingPlanView: ...


class DraftingView(View):
    @property
    def InternalElement(self) -> Element: ...
    def ByName(name: str) -> DraftingView: ...


class FloorPlanView(PlanView):
    def ByLevel(level: Level) -> FloorPlanView: ...


class Legend(View):
    @property
    def InternalElement(self) -> Element: ...


class PerspectiveView(View3D):
    def ByEyePointAndTarget(eyePoint: Point, target: Point, element: Object, name: str, isolateElement: bool) -> PerspectiveView: ...
    def ByEyePointTargetAndElement(eyePoint: Point, target: Point, element: Element, name: str, isolateElement: bool) -> PerspectiveView: ...
    def ByEyePointTargetAndBoundingBox(eyePoint: Point, target: Point, boundingBox: BoundingBox, name: str, isolateElement: bool) -> PerspectiveView: ...


class ScheduleView(View):
    @property
    def InternalElement(self) -> Element: ...
    def CreateSchedule(category: Category, name: str, scheduleType: str) -> ScheduleView: ...
    def CreateAreaSchedule(areaScheme: Element, name: str) -> ScheduleView: ...
    def RemoveFields(self, fields: List) -> ScheduleView: ...
    def AddFields(self, fields: List) -> ScheduleView: ...
    def Export(self, path: str, exportOptions: ScheduleExportOptions) -> ScheduleView: ...
    def AddFilters(self, scheduleFilters: List) -> ScheduleView: ...
    def ClearAllFilters(self) -> ScheduleView: ...
    @property
    def ScheduleFilters(self) -> List: ...
    @property
    def Fields(self) -> List: ...
    @property
    def SchedulableFields(self) -> List: ...


class SectionView(View):
    @property
    def InternalElement(self) -> Element: ...
    def ByBoundingBox(box: BoundingBox) -> SectionView: ...
    def ByCoordinateSystemMinPointMaxPoint(cs: CoordinateSystem, minPoint: Point, maxPoint: Point) -> SectionView: ...


class Sheet(View):
    @property
    def InternalElement(self) -> Element: ...
    def Dispose(self) -> None: ...
    @property
    def SheetName(self) -> str: ...
    @property
    def SheetNumber(self) -> str: ...
    def SetSheetNumber(self, sheetNumber: str) -> Sheet: ...
    def SetSheetName(self, sheetName: str) -> Sheet: ...
    @property
    def Views(self) -> Set(View): ...
    @property
    def Viewports(self) -> Set(Viewport): ...
    @property
    def Schedules(self) -> Set(ScheduleOnSheet): ...
    @property
    def TitleBlock(self) -> Set(Element): ...
    def ByNameNumberTitleBlockAndViews(sheetName: str, sheetNumber: str, titleBlockFamilyType: FamilyType, views: Set(View)) -> Sheet: ...
    def ByNameNumberTitleBlockAndView(sheetName: str, sheetNumber: str, titleBlockFamilyType: FamilyType, view: View) -> Sheet: ...
    def ByNameNumberTitleBlock(sheetName: str, sheetNumber: str, titleBlockFamilyType: FamilyType) -> Sheet: ...
    def ByNameNumberTitleBlockViewsAndLocations(sheetName: str, sheetNumber: str, titleBlockFamilyType: FamilyType, views: Set(View), locations: Set(Point)) -> Sheet: ...
    def ByNameNumberTitleBlockViewAndLocation(sheetName: str, sheetNumber: str, titleBlockFamilyType: FamilyType, view: View, location: Point) -> Sheet: ...
    def DuplicateSheet(sheet: Sheet, duplicateWithContents: bool, duplicateWithView: bool, viewDuplicateOption: str, prefix: str, suffix: str) -> Sheet: ...


class StructuralPlanView(PlanView):
    def ByLevel(level: Level) -> StructuralPlanView: ...


class View(Element):
    def ExportAsImage(self, path: str) -> Bitmap: ...
    @property
    def Discipline(self) -> str: ...
    def SetDiscipline(self, discipline: str) -> View: ...
    @property
    def Displaystyle(self) -> str: ...
    def SetDisplayStyle(self, displayStyle: str) -> View: ...
    @overload
    def ToString(self) -> str: ...
    @property
    def Outline(self) -> BoundingBox: ...
    @property
    def Origin(self) -> Point: ...
    def AddFilter(self, parameterFilter: ParameterFilterElement) -> View: ...
    @property
    def Filters(self) -> Iterable[ParameterFilterElement]: ...
    def SetFilterOverrides(self, parameterFilter: ParameterFilterElement, overrides: OverrideGraphicSettings, hide: bool) -> View: ...
    def FilterOverrides(self, parameterFilter: ParameterFilterElement) -> OverrideGraphicSettings: ...
    def IsViewTemplate(self) -> bool: ...
    def SetCategoryOverrides(self, category: Category, overrides: OverrideGraphicSettings, hide: bool) -> View: ...
    def GetCategoryOverrides(self, category: Category) -> OverrideGraphicSettings: ...
    def IsCategoryHidden(self, category: Category) -> bool: ...
    def HideCategoriesTemporary(self, categories: Iterable[Category]) -> View: ...
    def HideElementsTemporary(self, elements: Iterable[Element]) -> View: ...
    def IsolateCategoriesTemporary(self, categories: Iterable[Category]) -> View: ...
    def IsolateElementsTemporary(self, elements: Iterable[Element]) -> View: ...
    def SetScale(self, scale: int) -> View: ...
    @property
    def Scale(self) -> int: ...
    def CanViewBeDuplicated(self, viewDuplicateOption: str) -> bool: ...
    def DuplicateView(view: View, viewDuplicateOption: str, prefix: str, suffix: str) -> View: ...
    @property
    def CropBox(self) -> BoundingBox: ...
    @property
    def CropBoxActive(self) -> bool: ...
    @property
    def CropBoxVisible(self) -> bool: ...
    def SetCropBoxActive(self, isActive: bool) -> View: ...
    def SetCropBoxVisible(self, isVisible: bool) -> View: ...
    def SetCropBox(self, boundingBox: BoundingBox) -> View: ...
    @property
    def ViewDirection(self) -> Vector: ...
    @property
    def RightDirection(self) -> Vector: ...
    @property
    def SketchPlane(self) -> SketchPlane: ...
    def SetSketchPlane(self, sketchPlane: SketchPlane) -> View: ...
    @property
    def Partsvisibility(self) -> str: ...
    def SetPartsVisibility(self, partsVisibility: str) -> View: ...


class View3D(View):
    @property
    def InternalElement(self) -> Element: ...
    def CreateUniqueViewName(name: str) -> str: ...


class View3DTemplate(View3D):


class ScheduleType:
    KeySchedule = 0
    RegularSchedule = 1
    MaterialTakeoff = 2
