from typing import Tuple, Set, Iterable, List


class GraphicsManager:
    def __init__(self): ...
    @property
    def TesselationLevelOfDetail() -> float: ...
    @TesselationLevelOfDetail.setter
    def TesselationLevelOfDetail(value: float) -> None: ...
    def PushMesh(mesh: Mesh, package: IRenderPackage) -> None: ...
