from typing import Tuple, Set, Iterable, List


class AbstractFamilyInstance(Element):
    @property
    def InternalElement(self) -> Element: ...
    @property
    def Type(self) -> FamilyType: ...
    @property
    def Location(self) -> Point: ...
    @overload
    def ToString(self) -> str: ...


class AdaptiveComponent(AbstractFamilyInstance):
    @property
    def Type(self) -> FamilyType: ...
    @property
    def Locations(self) -> List: ...
    @overload
    def ByParametersOnFace(uvs: Set(Set(float)), faceReference: ElementFaceReference, familyType: FamilyType) -> AdaptiveComponent: ...
    @overload
    def ByParametersOnFace(uvs: Set(UV), faceReference: ElementFaceReference, familyType: FamilyType) -> AdaptiveComponent: ...
    @overload
    def ByParametersOnFace(uvs: Set(Set(float)), surface: Surface, familyType: FamilyType) -> AdaptiveComponent: ...
    @overload
    def ByParametersOnCurveReference(parameters: Set(float), revitCurve: Element, familyType: FamilyType) -> AdaptiveComponent: ...
    @overload
    def ByParametersOnCurveReference(parameters: Set(float), revitCurve: ElementCurveReference, familyType: FamilyType) -> AdaptiveComponent: ...
    def ByPoints(points: Set(Set(Point)), familyType: FamilyType) -> Set(AdaptiveComponent): ...
    @overload
    def ByParametersOnFace(uvs: Set(UV), surface: Surface, familyType: FamilyType) -> AdaptiveComponent: ...
    @overload
    def ByParametersOnCurveReference(parameters: Set(float), curve: Curve, familyType: FamilyType) -> AdaptiveComponent: ...


class AppearanceAssetElement(Element):
    @property
    def InternalElement(self) -> Element: ...
    def GetRenderingAssetTextureImages(self) -> Dictionary: ...
    def SetRenderingAssetTextureImage(self, imageProperty: str, imagePath: str) -> AppearanceAssetElement: ...


class Area(Element):
    @property
    def InternalElement(self) -> Element: ...
    @property
    def Boundaries(self) -> List: ...


class Category:
    @property
    def Name(self) -> str: ...
    @property
    def Id(self) -> Int64: ...
    def ByName(name: str) -> Category: ...
    def ById(id: Int64) -> Category: ...
    def ToString(self) -> str: ...
    def Equals(self, obj: Object) -> bool: ...
    def GetHashCode(self) -> int: ...


class Ceiling(Element):
    @property
    def InternalElement(self) -> Element: ...
    @overload
    def ByOutlineTypeAndLevel(outlineCurves: Set(Curve), ceilingType: CeilingType, level: Level) -> Ceiling: ...
    @overload
    def ByOutlineTypeAndLevel(outline: PolyCurve, ceilingType: CeilingType, level: Level) -> Ceiling: ...


class CeilingType(ElementType):
    @property
    def Name(self) -> str: ...
    def ByName(name: str) -> CeilingType: ...
    def GetThermalProperties(self) -> Dictionary: ...
    @overload
    def ToString(self) -> str: ...


class Coordinates:
    def ProjectRotation() -> float: ...
    def BasePoint() -> Point: ...
    def SurveyPoint() -> Point: ...


class CurtainPanel(AbstractFamilyInstance):
    @property
    def Boundaries(self) -> Set(PolyCurve): ...
    @property
    def HasPlane(self) -> bool: ...
    @property
    def PanelPlane(self) -> Plane: ...
    @property
    def Length(self) -> float: ...
    @property
    def IsRectangular(self) -> bool: ...
    @property
    def Width(self) -> float: ...
    @property
    def Height(self) -> float: ...
    def ByElement(hostingElement: Element) -> Set(CurtainPanel): ...
    def SupportingMullions(self) -> Set(Mullion): ...
    def AsFamilyInstance(self) -> FamilyInstance: ...
    @overload
    def ToString(self) -> str: ...


class CurtainSystem(Element):
    @property
    def InternalElement(self) -> Element: ...
    def ByFace(face: Surface, curtainSystemType: CurtainSystemType) -> CurtainSystem: ...
    def AddCurtainGrid(self, face: Surface) -> None: ...
    def RemoveCurtainGrid(self, face: Surface) -> None: ...
    @property
    def CurtainSystemType(self) -> CurtainSystemType: ...


class CurtainSystemType(ElementType):
    @property
    def Name(self) -> str: ...
    def ByName(name: str) -> CurtainSystemType: ...
    @overload
    def ToString(self) -> str: ...


class CurveByPoints(CurveElement):
    def ByReferencePoints(points: Set(ReferencePoint), isReferenceLine: bool) -> CurveByPoints: ...
    @overload
    def ToString(self) -> str: ...


class CurveElement(Element):
    @property
    def InternalElement(self) -> Element: ...
    @property
    def ElementCurveReference(self) -> ElementCurveReference: ...
    @property
    def Curve(self) -> Curve: ...
    @overload
    def Tessellate(self, package: IRenderPackage, parameters: TessellationParameters) -> None: ...


class DetailCurve(CurveElement):
    def ByCurve(view: View, curve: Curve) -> DetailCurve: ...
    @property
    def Curve(self) -> Curve: ...
    def SetCurve(self, curve: Curve) -> None: ...
    @overload
    def ToString(self) -> str: ...


class Dimension(Element):
    @property
    def InternalElement(self) -> Element: ...
    def ByElements(view: View, referenceElements: Iterable[Element], line: Line, suffix: str, prefix: str) -> Dimension: ...
    def ByFaces(view: View, referenceSurfaces: Iterable[Surface], line: Line, suffix: str, prefix: str) -> Dimension: ...
    def ByEdges(view: View, referenceCurves: Iterable[Curve], line: Line, suffix: str, prefix: str) -> Dimension: ...
    def ByReferences(view: View, referenceGeometries: Iterable[ElementGeometryReference], line: Line, suffix: str, prefix: str) -> Dimension: ...
    def ByElementDirection(view: View, element: Element, direction: Vector, line: Line, suffix: str, prefix: str) -> Dimension: ...
    @property
    def Value(self) -> Iterable[float]: ...
    @property
    def Prefix(self) -> Iterable[str]: ...
    def SetPrefix(self, values: Iterable[str]) -> None: ...
    @property
    def Suffix(self) -> Iterable[str]: ...
    def SetSuffix(self, values: Iterable[str]) -> None: ...
    @property
    def ValueOverride(self) -> Iterable[str]: ...
    def SetValueOverride(self, values: Iterable[str]) -> None: ...
    @property
    def AboveValue(self) -> List: ...
    @property
    def BelowValue(self) -> List: ...
    def SetAboveValue(self, value: str) -> Element: ...
    def SetBelowValue(self, value: str) -> Element: ...


class DimensionType(Element):
    @property
    def InternalElement(self) -> Element: ...
    def FromExisting(dimensionType: Element, name: str) -> DimensionType: ...
    @property
    def StyleType(self) -> str: ...


class DirectShapeState(SerializableId):
    @overload
    def __init__(self, intID: int, stringID: str, syncId: str, materialId: Int64): ...
    @overload
    def __init__(self, ds: DirectShape, syncId: str, materialId: ElementId): ...
    @property
    def syncId(self) -> str: ...
    @syncId.setter
    def syncId(self, value: str) -> None: ...
    @property
    def materialId(self) -> Int64: ...
    @materialId.setter
    def materialId(self, value: Int64) -> None: ...


class DirectShape(Element):
    @property
    def DynamoPreviewMaterial() -> Material: ...
    @property
    def InternalElement(self) -> Element: ...
    def ByGeometry(geometry: Geometry, category: Category, material: Material, name: str) -> DirectShape: ...
    def ByMesh(mesh: Mesh, category: Category, material: Material, name: str) -> DirectShape: ...
    @overload
    def ToString(self) -> str: ...


class DividedPath(Element):
    @property
    def InternalElement(self) -> Element: ...
    @property
    def Points(self) -> Iterable[Point]: ...
    @overload
    def ByCurveAndDivisions(element: ElementCurveReference, divisions: int) -> DividedPath: ...
    @overload
    def ByCurvesAndDivisions(curveReferences: Set(ElementCurveReference), divisions: int) -> DividedPath: ...
    @overload
    def ByCurveAndDivisions(element: Element, divisions: int) -> DividedPath: ...
    @overload
    def ByCurvesAndDivisions(elements: Set(Element), divisions: int) -> DividedPath: ...
    @overload
    def ByCurveAndDivisions(curve: Curve, divisions: int) -> DividedPath: ...
    @overload
    def ByCurvesAndDivisions(curve: Set(Curve), divisions: int) -> DividedPath: ...


class DividedSurface(Element):
    @property
    def InternalElement(self) -> Element: ...
    @property
    def UDivisions(self) -> int: ...
    @property
    def VDivisions(self) -> int: ...
    @property
    def Rotation(self) -> float: ...
    @overload
    def ByFaceAndUVDivisions(elementFace: ElementFaceReference, uDivs: int, vDivs: int) -> DividedSurface: ...
    @overload
    def ByFaceUVDivisionsAndRotation(faceReference: ElementFaceReference, uDivs: int, vDivs: int, gridRotation: float) -> DividedSurface: ...
    @overload
    def ByFaceAndUVDivisions(elementFace: Surface, uDivs: int, vDivs: int) -> DividedSurface: ...
    @overload
    def ByFaceUVDivisionsAndRotation(surface: Surface, uDivs: int, vDivs: int, gridRotation: float) -> DividedSurface: ...


class Element:
    @property
    def Parameters(self) -> Set(Parameter): ...
    @property
    def Name(self) -> str: ...
    @property
    def BoundingBox(self) -> BoundingBox: ...
    @property
    def Id(self) -> Int64: ...
    @property
    def UniqueId(self) -> str: ...
    @property
    def IsPinned(self) -> bool: ...
    def AreJoined(self, otherElement: Element) -> bool: ...
    @property
    def InternalElement(self) -> Element: ...
    @property
    def GetCategory(self) -> Category: ...
    @property
    def ElementType(self) -> ElementType: ...
    def Dispose(self) -> None: ...
    @overload
    def ToString(self) -> str: ...
    def Equals(self, obj: Object) -> bool: ...
    def GetHashCode(self) -> int: ...
    @overload
    def ToString(self, format: str, formatProvider: IFormatProvider) -> str: ...
    def Tessellate(self, package: IRenderPackage, parameters: TessellationParameters) -> None: ...
    def Delete(element: Element) -> Set(Int64): ...
    def GetParameterValueByName(self, parameterName: str) -> Object: ...
    def SetParameterByName(self, parameterName: str, value: Object) -> Element: ...
    def OverrideColorInView(self, color: Color) -> Element: ...
    def OverrideInView(self, overrides: OverrideGraphicSettings, hide: bool) -> Element: ...
    @property
    def OverridesInView(self) -> OverrideGraphicSettings: ...
    def IsHiddeninView(self, view: View) -> bool: ...
    def Geometry(self) -> Set(Object): ...
    def GetGeometry(self, detailLevel: str) -> Set(Object): ...
    def GetHostedElements(self, includeOpenings: bool, includeHostedElementsOfJoinedHosts: bool, includeEmbeddedWalls: bool, includeSharedEmbeddedInserts: bool) -> Iterable[Element]: ...
    def SetPinnedStatus(self, pinned: bool) -> Element: ...
    @property
    def Solids(self) -> Set(Solid): ...
    @property
    def Curves(self) -> Set(Curve): ...
    @property
    def Faces(self) -> Set(Surface): ...
    @property
    def ElementCurveReferences(self) -> Set(ElementCurveReference): ...
    @property
    def ElementFaceReferences(self) -> Set(ElementFaceReference): ...
    def GetChildElements(self) -> Iterable[Element]: ...
    def GetParentElement(self) -> Element: ...
    def GetJoinedElements(self) -> Iterable[Element]: ...
    def GetIntersectingElementsOfCategory(self, category: Category) -> Iterable[Element]: ...
    def UnjoinGeometry(self, otherElement: Element) -> Iterable[Element]: ...
    def UnjoinAllGeometry(elements: List) -> Iterable[Element]: ...
    def SetGeometryJoinOrder(cuttingElement: Element, otherElement: Element) -> Iterable[Element]: ...
    def JoinGeometry(self, otherElement: Element) -> Iterable[Element]: ...
    def SetLocation(self, geometry: Geometry) -> None: ...
    def GetLocation(self) -> Geometry: ...
    def MoveByVector(self, vector: Vector) -> None: ...
    def GetMaterials(self, paintMaterials: bool) -> Iterable[Material]: ...


class ElementType(Element):
    @property
    def InternalElement(self) -> Element: ...
    @property
    def Name(self) -> str: ...
    @property
    def FamilyName(self) -> str: ...
    @property
    def CanBeDeleted(self) -> bool: ...
    @property
    def CanBeCopied(self) -> bool: ...
    @property
    def CanBeRenamed(self) -> bool: ...
    def Duplicate(self, name: str) -> ElementType: ...
    def ByName(name: str) -> ElementType: ...
    def GetPreviewImage(self, size: int) -> Bitmap: ...


class ElevationMarker(Element):
    @property
    def InternalElement(self) -> Element: ...
    def ByViewTypeLocation(viewFamilyType: Element, location: Point, initialViewScale: int) -> ElevationMarker: ...
    def CreateElevationByMarkerIndex(self, planView: View, index: int) -> SectionView: ...
    def GetView(self, index: int) -> SectionView: ...
    @property
    def CurrentViewCount(self) -> int: ...


class FaceWall(Element):
    @property
    def InternalElement(self) -> Element: ...


class Family(Element):
    @property
    def InternalElement(self) -> Element: ...
    @property
    def Types(self) -> Set(FamilyType): ...
    @property
    def Name(self) -> str: ...
    def ByName(name: str) -> Family: ...
    def FamilyDocument(self) -> FamilyDocument: ...
    @overload
    def ToString(self) -> str: ...


class FamilyInstance(AbstractFamilyInstance):
    @property
    def Type(self) -> FamilyType: ...
    @property
    def Location(self) -> Point: ...
    @property
    def FacingOrientation(self) -> Vector: ...
    @property
    def Room(self) -> Element: ...
    @property
    def Space(self) -> Element: ...
    def ByPoint(familyType: FamilyType, point: Point) -> FamilyInstance: ...
    @overload
    def ByFace(familyType: FamilyType, face: Surface, line: Line) -> FamilyInstance: ...
    @overload
    def ByFace(familyType: FamilyType, face: Surface, location: Point, referenceDirection: Vector) -> FamilyInstance: ...
    def ByCoordinates(familyType: FamilyType, x: float, y: float, z: float) -> FamilyInstance: ...
    def ByPointAndLevel(familyType: FamilyType, point: Point, level: Level) -> FamilyInstance: ...
    def ByFamilyType(familyType: FamilyType) -> Set(FamilyInstance): ...
    def ByCoordinateSystem(familyType: FamilyType, coordinateSystem: CoordinateSystem) -> FamilyInstance: ...
    def ByHostAndPoint(familyType: FamilyType, host: Element, point: Point) -> FamilyInstance: ...
    @overload
    def ToString(self) -> str: ...
    @property
    def GetHost(self) -> Element: ...
    @property
    def GetFamily(self) -> Family: ...
    @property
    def GetType(self) -> FamilyType: ...
    def SetRotation(self, degree: float) -> FamilyInstance: ...
    def Transform(self, fromCoordinateSystem: CoordinateSystem, contextCoordinateSystem: CoordinateSystem) -> FamilyInstance: ...


class FamilyParameter:
    @property
    def Name(self) -> str: ...
    @property
    def IsReadOnly(self) -> bool: ...
    @property
    def IsShared(self) -> bool: ...
    @property
    def Id(self) -> Int64: ...
    @property
    def SpecType(self) -> SpecType: ...
    @property
    def GroupType(self) -> GroupType: ...
    @property
    def Unit(self) -> Unit: ...
    @property
    def StorageType(self) -> str: ...
    @property
    def CanAssignFormula(self) -> bool: ...
    @property
    def IsReporting(self) -> bool: ...


class FamilyType(ElementType):
    @property
    def Name(self) -> str: ...
    @property
    def Family(self) -> Family: ...
    def ByFamilyAndName(family: Family, name: str) -> FamilyType: ...
    def ByFamilyNameAndTypeName(familyName: str, typeName: str) -> FamilyType: ...
    def ByName(name: str) -> FamilyType: ...
    def ByGeometry(solidGeometry: Solid, name: str, category: Category, templatePath: str, material: Material, subcategory: str) -> FamilyType: ...
    def VoidByGeometry(solidGeometry: Solid, name: str, category: Category, templatePath: str) -> FamilyType: ...
    @overload
    def ToString(self) -> str: ...


class FilledRegion(Element):
    @property
    def InternalElement(self) -> Element: ...
    def ByCurves(view: View, boundary: Iterable[Curve], regionType: FilledRegionType) -> FilledRegion: ...


class FilledRegionType(ElementType):
    def ByName(name: str) -> FilledRegionType: ...
    @property
    def Name(self) -> str: ...
    @property
    def Color(self) -> Color: ...
    @property
    def FillPatternId(self) -> ElementId: ...


class FillPatternElement(Element):
    @property
    def InternalElement(self) -> Element: ...
    def GetByName(name: str, fillPatternTarget: str) -> FillPatternElement: ...


class Floor(Element):
    @property
    def InternalElement(self) -> Element: ...
    @overload
    def ByOutlineTypeAndLevel(outlineCurves: Set(Curve), floorType: FloorType, level: Level) -> Floor: ...
    @overload
    def ByOutlineTypeAndLevel(outline: PolyCurve, floorType: FloorType, level: Level) -> Floor: ...
    @property
    def Points(self) -> Iterable[Point]: ...
    def AddPoint(self, point: Point) -> Floor: ...
    def MovePoint(self, point: Point, offset: float) -> Floor: ...


class FloorType(ElementType):
    @property
    def Name(self) -> str: ...
    @property
    def IsFoundationSlab(self) -> bool: ...
    def ByName(name: str) -> FloorType: ...
    def GetStructuralMaterial(self) -> Material: ...
    def GetThermalProperties(self) -> Dictionary: ...
    @overload
    def ToString(self) -> str: ...


class ForgeType:
    @property
    def TypeId(self) -> str: ...
    @property
    def IsValidObject(self) -> bool: ...
    def ToString(self) -> str: ...


class Form(Element):
    @property
    def InternalElement(self) -> Element: ...
    @overload
    def ByLoftCrossSections(curves: Set(Set(ElementCurveReference)), isSolid: bool) -> Form: ...
    @overload
    def ByLoftCrossSections(curves: Set(Set(Element)), isSolid: bool) -> Form: ...
    @overload
    def ByLoftCrossSections(curves: Set(Set(Curve)), isSolid: bool) -> Form: ...


class FreeForm(Element):
    @property
    def InternalElement(self) -> Element: ...


class GlobalParameter(Element):
    @property
    def InternalElement(self) -> Element: ...
    def FindByName(name: str) -> GlobalParameter: ...
    @property
    def Name(self) -> str: ...
    @property
    def Value(self) -> Object: ...
    def SetValue(parameter: GlobalParameter, value: Object) -> None: ...
    def SetValueToElementId(parameter: GlobalParameter, elementId: Int64) -> None: ...
    @property
    def Visible(self) -> bool: ...
    @property
    def SpecType(self) -> SpecType: ...
    @property
    def GroupType(self) -> GroupType: ...
    def ByName(name: str, specType: SpecType) -> GlobalParameter: ...


class Grid(Element):
    @property
    def InternalElement(self) -> Element: ...
    @property
    def Curve(self) -> Curve: ...
    @property
    def ElementCurveReference(self) -> ElementCurveReference: ...
    def ByLine(line: Line) -> Grid: ...
    def ByStartPointEndPoint(start: Point, end: Point) -> Grid: ...
    def ByArc(arc: Arc) -> Grid: ...


class Group(Element):
    @property
    def InternalElement(self) -> Element: ...
    def ByElements(elements: List) -> Group: ...
    def PlaceInstance(location: Point, groupType: Element) -> Group: ...
    @property
    def Location(self) -> Point: ...
    @property
    def GroupType(self) -> Element: ...
    @property
    def IsAttached(self) -> bool: ...
    @property
    def AttachedDetailGroup(self) -> List: ...
    def GetMembers(self) -> List: ...
    def UngroupElements(self) -> List: ...


class GroupType(ForgeType):
    def ByTypeId(typeId: str) -> GroupType: ...
    def ToString(self) -> str: ...


class ImportInstance(Element):
    @property
    def InternalElement(self) -> Element: ...
    @property
    def Path(self) -> str: ...
    def BySATFile(pathToFile: str) -> ImportInstance: ...
    def ByGeometries(geometries: Set(Geometry)) -> ImportInstance: ...
    def ByGeometriesAndView(geometries: Set(Geometry), view: View) -> ImportInstance: ...
    def ByGeometry(geometry: Geometry) -> ImportInstance: ...
    def ByGeometryAndView(geometry: Geometry, view: View) -> ImportInstance: ...


class ElementSelector:
    def __init__(self): ...
    @overload
    def ByElementId(elementId: Int64, isRevitOwned: bool) -> Element: ...
    @overload
    def ByElementId(elementId: Int64) -> Element: ...
    def ByUniqueId(uniqueId: str, isRevitOwned: bool) -> Element: ...


class ElementWrapper:
    def ToDSType(ele: Element, isRevitOwned: bool) -> Element: ...
    @overload
    def Wrap(element: Element, isRevitOwned: bool) -> UnknownElement: ...
    @overload
    def Wrap(ele: FamilyInstance, isRevitOwned: bool) -> AbstractFamilyInstance: ...
    @overload
    def Wrap(ele: Area, isRevitOwned: bool) -> Area: ...
    @overload
    def Wrap(ele: Ceiling, isRevitOwned: bool) -> Ceiling: ...
    @overload
    def Wrap(ele: CeilingType, isRevitOwned: bool) -> CeilingType: ...
    @overload
    def Wrap(ele: DirectShape, isRevitOwned: bool) -> DirectShape: ...
    @overload
    def Wrap(ele: DividedPath, isRevitOwned: bool) -> DividedPath: ...
    @overload
    def Wrap(elementType: ElementType, isRevitOwned: bool) -> ElementType: ...
    @overload
    def Wrap(ele: DividedSurface, isRevitOwned: bool) -> DividedSurface: ...
    @overload
    def Wrap(ele: Family, isRevitOwned: bool) -> Family: ...
    @overload
    def Wrap(ele: FamilySymbol, isRevitOwned: bool) -> FamilyType: ...
    @overload
    def Wrap(ele: Floor, isRevitOwned: bool) -> Floor: ...
    @overload
    def Wrap(ele: FloorType, isRevitOwned: bool) -> FloorType: ...
    @overload
    def Wrap(ele: Form, isRevitOwned: bool) -> Form: ...
    @overload
    def Wrap(ele: FreeFormElement, isRevitOwned: bool) -> FreeForm: ...
    @overload
    def Wrap(ele: Grid, isRevitOwned: bool) -> Grid: ...
    @overload
    def Wrap(ele: Group, isRevitOwned: bool) -> Group: ...
    @overload
    def Wrap(ele: Level, isRevitOwned: bool) -> Level: ...
    @overload
    def Wrap(ele: ModelCurve, isRevitOwned: bool) -> ModelCurve: ...
    @overload
    def Wrap(ele: CurveByPoints, isRevitOwned: bool) -> CurveByPoints: ...
    @overload
    def Wrap(ele: ModelText, isRevitOwned: bool) -> ModelText: ...
    @overload
    def Wrap(ele: ModelTextType, isRevitOwned: bool) -> ModelTextType: ...
    @overload
    def Wrap(ele: ReferencePlane, isRevitOwned: bool) -> ReferencePlane: ...
    @overload
    def Wrap(ele: ReferencePoint, isRevitOwned: bool) -> ReferencePoint: ...
    @overload
    def Wrap(ele: SketchPlane, isRevitOwned: bool) -> SketchPlane: ...
    @overload
    def Wrap(ele: Wall, isRevitOwned: bool) -> Wall: ...
    @overload
    def Wrap(ele: WallType, isRevitOwned: bool) -> WallType: ...
    @overload
    def Wrap(view: View3D, isRevitOwned: bool) -> View3D: ...
    @overload
    def Wrap(view: ViewPlan, isRevitOwned: bool) -> Element: ...
    @overload
    def Wrap(view: ViewSection, isRevitOwned: bool) -> SectionView: ...
    @overload
    def Wrap(view: ViewSchedule, isRevitOwned: bool) -> ScheduleView: ...
    @overload
    def Wrap(view: View, isRevitOwned: bool) -> Element: ...
    @overload
    def Wrap(view: ViewSheet, isRevitOwned: bool) -> Sheet: ...
    @overload
    def Wrap(view: ViewDrafting, isRevitOwned: bool) -> DraftingView: ...
    @overload
    def Wrap(topoSurface: TopographySurface, isRevitOwned: bool) -> Topography: ...
    @overload
    def Wrap(toposolid: Toposolid, isRevitOwned: bool) -> Toposolid: ...
    @overload
    def Wrap(toposolidType: ToposolidType, isRevitOwned: bool) -> ToposolidType: ...
    @overload
    def Wrap(ele: Panel, isRevitOwned: bool) -> Object: ...
    @overload
    def Wrap(ele: Mullion, isRevitOwned: bool) -> Mullion: ...
    @overload
    def Wrap(ele: Dimension, isRevitOwned: bool) -> Dimension: ...
    @overload
    def Wrap(ele: DimensionType, isRevitOwned: bool) -> DimensionType: ...
    @overload
    def Wrap(ele: FilledRegionType, isRevitOwned: bool) -> FilledRegionType: ...
    @overload
    def Wrap(ele: FilledRegion, isRevitOwned: bool) -> FilledRegion: ...
    @overload
    def Wrap(ele: FillPatternElement, isRevitOwned: bool) -> FillPatternElement: ...
    @overload
    def Wrap(ele: LinePatternElement, isRevitOwned: bool) -> LinePatternElement: ...
    @overload
    def Wrap(ele: TextNote, isRevitOwned: bool) -> TextNote: ...
    @overload
    def Wrap(ele: IndependentTag, isRevitOwned: bool) -> Tag: ...
    @overload
    def Wrap(ele: TextNoteType, isRevitOwned: bool) -> TextNoteType: ...
    @overload
    def Wrap(ele: Revision, isRevitOwned: bool) -> Revision: ...
    @overload
    def Wrap(ele: RevisionCloud, isRevitOwned: bool) -> RevisionCloud: ...
    @overload
    def Wrap(ele: ParameterFilterElement, isRevitOwned: bool) -> ParameterFilterElement: ...
    @overload
    def Wrap(ele: Room, isRevitOwned: bool) -> Room: ...
    @overload
    def Wrap(ele: DetailCurve, isRevitOwned: bool) -> DetailCurve: ...
    @overload
    def Wrap(ele: ImportInstance, isRevitOwned: bool) -> ImportInstance: ...
    @overload
    def Wrap(ele: GlobalParameter, isRevitOwned: bool) -> GlobalParameter: ...
    @overload
    def Wrap(ele: FaceWall, isRevitOwned: bool) -> FaceWall: ...
    @overload
    def Wrap(ele: CurtainSystem, isRevitOwned: bool) -> CurtainSystem: ...
    @overload
    def Wrap(ele: Material, isRevitOwned: bool) -> Material: ...
    @overload
    def Wrap(ele: PathOfTravel, isRevitOwned: bool) -> PathOfTravel: ...
    @overload
    def Wrap(ele: Viewport, isRevitOwned: bool) -> Viewport: ...
    @overload
    def Wrap(ele: ElevationMarker, isRevitOwned: bool) -> ElevationMarker: ...
    @overload
    def Wrap(ele: Space, isRevitOwned: bool) -> Space: ...
    @overload
    def Wrap(ele: RoofType, isRevitOwned: bool) -> RoofType: ...
    @overload
    def Wrap(ele: RoofBase, isRevitOwned: bool) -> Roof: ...
    @overload
    def Wrap(ele: ScheduleSheetInstance, isRevitOwned: bool) -> ScheduleOnSheet: ...
    @overload
    def Wrap(ele: AppearanceAssetElement, isRevitOwned: bool) -> AppearanceAssetElement: ...
    @overload
    def Wrap(ele: RevitLinkInstance, isRevitOwned: bool) -> LinkInstance: ...


class ParseEnum:
    def __init__(self): ...
    def ByString(value: str, typeName: str) -> Object: ...


class LevelTraceData(SerializableId):
    @overload
    def __init__(self, intID: int, stringID: str, inputName: str): ...
    @overload
    def __init__(self, lev: Level, inputName: str): ...
    @property
    def InputName(self) -> str: ...
    @InputName.setter
    def InputName(self, value: str) -> None: ...


class Level(Element):
    @property
    def InternalElement(self) -> Element: ...
    @property
    def Elevation(self) -> float: ...
    @property
    def ProjectElevation(self) -> float: ...
    @property
    def Name(self) -> str: ...
    def ByElevationAndName(elevation: float, name: str) -> Level: ...
    def ByElevation(elevation: float) -> Level: ...
    def ByLevelAndOffset(level: Level, offset: float) -> Level: ...
    def ByLevelOffsetAndName(level: Level, offset: float, name: str) -> Level: ...
    @overload
    def ToString(self) -> str: ...


class LinePatternElement(Element):
    @property
    def InternalElement(self) -> Element: ...
    def GetByName(name: str) -> LinePatternElement: ...


class LinkElement:
    def GetLocation(linkedElement: Element) -> Geometry: ...
    def GetGeometry(linkedElement: Element, detailLevel: str) -> Object: ...
    def LinkTransform(linkedElement: Element) -> CoordinateSystem: ...
    def LinkInverseTransform(linkedElement: Element) -> CoordinateSystem: ...
    def BoundingBox(linkedElement: Element) -> BoundingBox: ...
    def ByRayBounce(origin: Point, direction: Vector, maxBounces: int, view: View3D) -> Dictionary: ...


class LinkInstance(Element):
    @property
    def InternalElement(self) -> Element: ...
    def AllElementsAtLevel(linkInstance: LinkInstance, level: Level) -> List: ...
    def AllElementsOfCategory(linkInstance: LinkInstance, category: Category) -> List: ...
    def AllElementsOfCategoryInView(linkInstance: LinkInstance, category: Category, view: View) -> List: ...
    def AllElementsOfClass(linkInstance: LinkInstance, elementClass: Type) -> List: ...
    def ByName(name: str) -> List: ...
    def ElementById(id: Object, linkInstance: LinkInstance) -> Element: ...
    def Document(linkInstance: LinkInstance) -> Document: ...
    def ByTitle(title: str) -> List: ...


class Material(Element):
    @property
    def InternalElement(self) -> Element: ...
    def ByName(name: str) -> Material: ...
    @property
    def Name(self) -> str: ...
    @property
    def Shininess(self) -> int: ...
    @property
    def Smoothness(self) -> int: ...
    @property
    def Transparency(self) -> int: ...
    @property
    def SurfacePatternColor(self) -> Color: ...
    @property
    def MaterialClass(self) -> str: ...
    @property
    def MaterialCategory(self) -> str: ...
    @property
    def CutPatternColor(self) -> Color: ...
    @property
    def Color(self) -> Color: ...
    @property
    def CutPatternId(self) -> Int64: ...
    @property
    def AppearanceParameters(self) -> Iterable[Parameter]: ...
    @property
    def ThermalParameters(self) -> Iterable[Parameter]: ...
    @property
    def StructuralParameters(self) -> Iterable[Parameter]: ...
    @property
    def AppearanceAssetElement(self) -> AppearanceAssetElement: ...


class ModelCurve(CurveElement):
    def ByCurve(curve: Curve) -> ModelCurve: ...
    def ReferenceCurveByCurve(curve: Curve) -> ModelCurve: ...
    @overload
    def ToString(self) -> str: ...


class ModelText(Element):
    @property
    def InternalElement(self) -> Element: ...
    @property
    def Text(self) -> str: ...
    @property
    def Depth(self) -> float: ...
    @property
    def Position(self) -> Point: ...
    def ByTextSketchPlaneAndPosition(text: str, sketchPlane: SketchPlane, xCoordinateInPlane: float, yCoordinateInPlane: float, textDepth: float, modelTextType: ModelTextType) -> ModelText: ...


class ModelTextType(ElementType):
    def ByName(name: str) -> ModelTextType: ...


class Mullion(AbstractFamilyInstance):
    @property
    def LocationCurve(self) -> Curve: ...
    def ByElement(hostingElement: Element) -> Set(Mullion): ...
    def SupportedPanels(self) -> Set(CurtainPanel): ...
    def AsFamilyInstance(self) -> FamilyInstance: ...
    @overload
    def ToString(self) -> str: ...


class Parameter:
    @property
    def Name(self) -> str: ...
    @property
    def Value(self) -> Object: ...
    @property
    def HasValue(self) -> bool: ...
    @property
    def IsReadOnly(self) -> bool: ...
    @property
    def IsShared(self) -> bool: ...
    @property
    def Id(self) -> Int64: ...
    @property
    def SpecType(self) -> SpecType: ...
    @property
    def GroupType(self) -> GroupType: ...
    @property
    def Unit(self) -> Unit: ...
    def ParameterByName(element: Element, name: str) -> Parameter: ...
    def SetValue(parameter: Parameter, value: Object) -> None: ...
    @property
    def StorageType(self) -> str: ...
    def ToString(self) -> str: ...
    def SharedParameterFile() -> str: ...
    def CreateSharedParameterForAllCategories(parameterName: str, groupName: str, specType: SpecType, groupType: GroupType, instance: bool) -> None: ...
    def CreateSharedParameter(parameterName: str, groupName: str, specType: SpecType, groupType: GroupType, instance: bool, categoryList: Iterable[Category]) -> None: ...
    def CreateProjectParameterForAllCategories(parameterName: str, groupName: str, specType: SpecType, groupType: GroupType, instance: bool) -> None: ...
    def CreateProjectParameter(parameterName: str, groupName: str, specType: SpecType, groupType: GroupType, instance: bool, categoryList: Iterable[Category]) -> None: ...


class PathOfTravel(Element):
    @property
    def InternalElement(self) -> Element: ...
    def LongestOfShortestExitPaths(floorPlan: FloorPlanView, endPtsList: Set(Point)) -> Set(PathOfTravel): ...
    def ByFloorPlanPoints(floorPlan: FloorPlanView, startPtsList: Set(Point), endPtsList: Set(Point), manyToMany: bool) -> Set(PathOfTravel): ...
    def GetWayPoints(self) -> List[XYZ]: ...
    def RemoveWayPoint(self, index: int) -> PathOfTravel: ...
    def InsertWayPoint(self, wayPoint: Point, index: int) -> PathOfTravel: ...
    def SetWayPoint(self, newPosition: Point, index: int) -> PathOfTravel: ...
    def Update(elements: Set(PathOfTravel)) -> Set(PathOfTravel): ...


class ReferencePlane(Element):
    @property
    def InternalElement(self) -> Element: ...
    @property
    def Plane(self) -> Plane: ...
    @property
    def ElementPlaneReference(self) -> ElementPlaneReference: ...
    def ByLine(line: Line) -> ReferencePlane: ...
    def ByStartPointEndPoint(start: Point, end: Point) -> ReferencePlane: ...


class ReferencePoint(Element):
    @property
    def InternalElement(self) -> Element: ...
    @property
    def X(self) -> float: ...
    @X.setter
    def X(self, value: float) -> None: ...
    @property
    def Y(self) -> float: ...
    @Y.setter
    def Y(self, value: float) -> None: ...
    @property
    def Z(self) -> float: ...
    @Z.setter
    def Z(self, value: float) -> None: ...
    @property
    def Point(self) -> Point: ...
    @property
    def XYPlane(self) -> Plane: ...
    @property
    def YZPlane(self) -> Plane: ...
    @property
    def XZPlane(self) -> Plane: ...
    def ByCoordinates(x: float, y: float, z: float) -> ReferencePoint: ...
    def ByPoint(pt: Point) -> ReferencePoint: ...
    def ByPointVectorDistance(basePoint: Point, direction: Vector, distance: float) -> ReferencePoint: ...
    def ByLengthOnCurveReference(elementCurveReference: Object, length: float) -> ReferencePoint: ...
    def ByParameterOnCurveReference(elementCurveReference: Object, parameter: float) -> ReferencePoint: ...
    def ByParametersOnFaceReference(elementFaceReference: Object, u: float, v: float) -> ReferencePoint: ...
    @overload
    def ToString(self) -> str: ...
    @overload
    def ToString(self, format: str, formatProvider: IFormatProvider) -> str: ...


class Revision(Element):
    @property
    def InternalElement(self) -> Element: ...
    def ByName(name: str, revDate: str, description: str, issued: bool, issuedBy: str, issuedTo: str, visibility: str, numberType: str) -> Revision: ...
    @property
    def RevisionDate(self) -> str: ...
    def SetRevisionDate(self, value: str) -> None: ...
    @property
    def IssuedTo(self) -> str: ...
    def SetIssuedTo(self, value: str) -> None: ...
    @property
    def IssuedBy(self) -> str: ...
    def SetIssuedBy(self, value: str) -> None: ...
    @property
    def Issued(self) -> bool: ...
    def SetIssued(self, value: bool) -> None: ...


class RevisionCloud(Element):
    @property
    def InternalElement(self) -> Element: ...
    def ByCurve(view: View, curves: Iterable[Curve], revision: Element) -> RevisionCloud: ...
    @property
    def Revision(self) -> Revision: ...
    @property
    def Curves(self) -> Iterable[Curve]: ...


class Roof(Element):
    @property
    def InternalElement(self) -> Element: ...
    def ByOutlineTypeAndLevel(outline: Set(Curve), roofType: RoofType, level: Level) -> Roof: ...
    def ByOutlineExtrusionTypeAndLevel(outline: PolyCurve, roofType: RoofType, level: Level, plane: ReferencePlane, extrusionStart: float, extrusionEnd: float) -> Roof: ...
    @property
    def Points(self) -> Iterable[Point]: ...
    def AddPoint(self, point: Point) -> None: ...
    def MovePoint(self, point: Point, offset: float) -> None: ...


class RoofType(ElementType):
    @property
    def Name(self) -> str: ...
    def ByName(name: str) -> RoofType: ...
    def GetThermalProperties(self) -> Dictionary: ...
    @overload
    def ToString(self) -> str: ...


class Room(Element):
    @property
    def InternalElement(self) -> Element: ...
    def ByLocation(level: Level, location: Point, name: str, number: str) -> Room: ...
    @property
    def Name(self) -> str: ...
    @property
    def Number(self) -> str: ...
    @property
    def Area(self) -> float: ...
    @property
    def Height(self) -> float: ...
    @property
    def Volume(self) -> float: ...
    @property
    def CenterBoundary(self) -> Iterable[Iterable[Curve]]: ...
    @property
    def CoreBoundary(self) -> Iterable[Iterable[Curve]]: ...
    @property
    def FinishBoundary(self) -> Iterable[Iterable[Curve]]: ...
    @property
    def CoreCenterBoundary(self) -> Iterable[Iterable[Curve]]: ...
    @property
    def Location(self) -> Point: ...
    def IsInsideRoom(self, point: Point) -> bool: ...
    def SetName(self, value: str) -> None: ...
    def SetNumber(self, value: str) -> None: ...


class ScheduleOnSheet(Element):
    @property
    def InternalElement(self) -> Element: ...
    @property
    def Location(self) -> Point: ...
    @overload
    def SetLocation(self, point: Point) -> ScheduleOnSheet: ...
    @property
    def Sheet(self) -> Sheet: ...
    @property
    def ScheduleView(self) -> ScheduleView: ...
    def BySheetScheduleLocation(sheet: Sheet, scheduleView: ScheduleView, location: Point) -> ScheduleOnSheet: ...


class SketchPlane(Element):
    @property
    def InternalElement(self) -> Element: ...
    @property
    def ElementPlaneReference(self) -> ElementPlaneReference: ...
    @property
    def Plane(self) -> Plane: ...
    def ByPlane(plane: Plane) -> SketchPlane: ...


class Space(Element):
    @property
    def InternalElement(self) -> Element: ...
    def ByLevelLocation(level: Level, location: Point, name: str, number: str) -> Space: ...
    @property
    def Name(self) -> str: ...
    @property
    def Number(self) -> str: ...
    @property
    def Area(self) -> float: ...
    @property
    def Height(self) -> float: ...
    @property
    def Volume(self) -> float: ...
    @property
    def CenterBoundary(self) -> Iterable[Iterable[Curve]]: ...
    @property
    def CoreBoundary(self) -> Iterable[Iterable[Curve]]: ...
    @property
    def FinishBoundary(self) -> Iterable[Iterable[Curve]]: ...
    @property
    def CoreCenterBoundary(self) -> Iterable[Iterable[Curve]]: ...
    @property
    def Location(self) -> Point: ...
    def IsPointInsideSpace(self, point: Point) -> bool: ...
    def SetName(self, value: str) -> Space: ...
    def SetNumber(self, value: str) -> Space: ...


class SpecType(ForgeType):
    def ByTypeId(typeId: str) -> SpecType: ...
    def ToString(self) -> str: ...


class StructuralType:
    Beam = 0
    Brace = 1
    Column = 2
    Footing = 3
    NonStructural = 4


class StructuralFraming(AbstractFamilyInstance):
    @property
    def Location(self) -> Curve: ...
    @property
    def Type(self) -> FamilyType: ...
    @property
    def GetType(self) -> FamilyType: ...
    def ByCurveLevelUpVectorAndType(curve: Curve, level: Level, upVector: Vector, structuralType: StructuralType, structuralFramingType: FamilyType) -> StructuralFraming: ...
    def BeamByCurve(curve: Curve, level: Level, structuralFramingType: FamilyType) -> StructuralFraming: ...
    def BraceByCurve(curve: Curve, level: Level, structuralFramingType: FamilyType) -> StructuralFraming: ...
    def ColumnByCurve(curve: Curve, level: Level, structuralColumnType: FamilyType) -> StructuralFraming: ...


class SunSettings(Element):
    def Current() -> SunSettings: ...
    @property
    def InternalElement(self) -> Element: ...
    @property
    def SunDirection(self) -> Vector: ...
    @property
    def Altitude(self) -> float: ...
    @property
    def Azimuth(self) -> float: ...
    @property
    def StartDateTime(self) -> DateTime: ...
    @property
    def EndDateTime(self) -> DateTime: ...
    @property
    def CurrentDateTime(self) -> DateTime: ...
    @overload
    def ToString(self) -> str: ...


class Tag(TextElement):
    def ByElement(view: View, element: Element, horizontal: bool, addLeader: bool, horizontalAlignment: str, verticalAlignment: str, offset: Vector, isOffset: bool) -> Tag: ...
    def ByElementAndLocation(view: View, element: Element, location: Point, horizontal: bool, addLeader: bool) -> Tag: ...
    def ByElementAndOffset(view: View, element: Element, offset: Vector, horizontalAlignment: str, verticalAlignment: str, horizontal: bool, addLeader: bool) -> Tag: ...
    @property
    def TagText(self) -> str: ...
    @property
    def TaggedElement(self) -> Element: ...
    @property
    def HeadLocation(self) -> Point: ...
    def SetHeadLocation(self, location: Point) -> Tag: ...
    @property
    def LeaderElbow(self) -> Point: ...
    def SetLeaderElbow(self, location: Point) -> Tag: ...
    @property
    def LeaderEnd(self) -> Point: ...
    def SetLeaderEnd(self, location: Point) -> Tag: ...
    @property
    def GetLeaderEndCondition(self) -> str: ...
    def SetLeaderEndCondition(self, leaderEndCondition: str) -> Tag: ...


class TextElement(Element):
    @property
    def InternalElement(self) -> Element: ...
    @overload
    def Tessellate(self, package: IRenderPackage, parameters: TessellationParameters) -> None: ...


class TextNote(TextElement):
    def ByLocation(view: View, location: Point, text: str, alignment: str, type: TextNoteType, keepRotatedTextReadable: bool, rotation: float) -> TextNote: ...
    @property
    def Text(self) -> str: ...
    def SetText(self, value: str) -> None: ...
    def SetKeepRotatedTextReadable(self, value: bool) -> None: ...
    def SetHorizontalAlignment(self, value: str) -> None: ...
    @property
    def HorizontalAlignment(self) -> str: ...
    @property
    def VerticalAlignment(self) -> str: ...
    @property
    def Height(self) -> float: ...
    @property
    def Typename(self) -> str: ...


class TextNoteType(ElementType):
    def ByName(name: str) -> TextNoteType: ...
    def Default() -> TextNoteType: ...


class Topography(Element):
    @property
    def InternalElement(self) -> Element: ...
    @property
    def Points(self) -> List: ...
    @property
    def Mesh(self) -> Mesh: ...
    def ByPoints(points: Iterable[Point]) -> Topography: ...
    @overload
    def ToString(self) -> str: ...


class Toposolid(Element):
    @property
    def InternalElement(self) -> Element: ...
    @property
    def Points(self) -> Iterable[Point]: ...
    @overload
    def ByOutlinePointsTypeAndLevel(outlineCurves: Set(Curve), points: Iterable[Point], toposolidType: ToposolidType, level: Level) -> Toposolid: ...
    @overload
    def ByOutlinePointsTypeAndLevel(outline: PolyCurve, points: Iterable[Point], toposolidType: ToposolidType, level: Level) -> Toposolid: ...
    @overload
    def ByOutlineTypeAndLevel(outlineCurves: Set(Curve), toposolidType: ToposolidType, level: Level) -> Toposolid: ...
    @overload
    def ByOutlineTypeAndLevel(outline: PolyCurve, toposolidType: ToposolidType, level: Level) -> Toposolid: ...
    def ByPointsTypeAndLevel(points: Iterable[Point], toposolidType: ToposolidType, level: Level) -> Toposolid: ...


class ToposolidType(ElementType):
    def ByName(name: str) -> ToposolidType: ...


class UnknownElement(Element):
    @property
    def InternalElement(self) -> Element: ...
    @overload
    def ToString(self) -> str: ...


class Viewport(Element):
    @property
    def InternalElement(self) -> Element: ...
    @property
    def Sheet(self) -> Sheet: ...
    @property
    def View(self) -> View: ...
    @property
    def BoxCenter(self) -> Point: ...
    def SetBoxCenter(self, point: Point) -> Viewport: ...
    @property
    def BoxOutline(self) -> BoundingBox: ...
    @property
    def LabelOutline(self) -> BoundingBox: ...
    @property
    def LabelOffset(self) -> Point: ...
    def SetLabelOffset(self, point: Point) -> Viewport: ...
    @property
    def LabelLineLength(self) -> float: ...
    def SetLabelLineLength(self, length: float) -> Viewport: ...
    def BySheetViewLocation(sheet: Sheet, view: View, location: Point) -> Viewport: ...


class PlanView(View):
    def __init__(self): ...
    @property
    def InternalElement(self) -> Element: ...


class Wall(Element):
    @property
    def InternalElement(self) -> Element: ...
    def ByCurveAndHeight(curve: Curve, height: float, level: Level, wallType: WallType) -> Wall: ...
    def ByCurveAndLevels(curve: Curve, startLevel: Level, endLevel: Level, wallType: WallType) -> Wall: ...
    def ByFace(locationLine: str, wallType: WallType, surface: Surface) -> Element: ...


class WallType(ElementType):
    @property
    def Name(self) -> str: ...
    @property
    def Width(self) -> float: ...
    @property
    def Kind(self) -> str: ...
    @property
    def Function(self) -> str: ...
    def ByName(name: str) -> WallType: ...
    def GetThermalProperties(self) -> Dictionary: ...


class BuiltinNodeCategories:


class FailureMessage:
    def __init__(self, message: FailureMessage): ...
    @property
    def Description(self) -> str: ...
    @property
    def FailingElements(self) -> ICollection: ...
    @property
    def Severity(self) -> str: ...
    def ToString(self) -> str: ...


class PerformanceAdviserRule:
    def __init__(self, id: PerformanceAdviserRuleId): ...
    @property
    def Name(self) -> str: ...
    @property
    def Description(self) -> str: ...
    @property
    def Enabled(self) -> bool: ...
    @SetEnabled.setter
    def SetEnabled(self, value: bool) -> None: ...
    @property
    def RuleId(self) -> Guid: ...
    def Execute(rules: Iterable[PerformanceAdviserRule]) -> List[FailureMessage]: ...
    def ById(guid: str) -> PerformanceAdviserRule: ...
    def ToString(self) -> str: ...
