from typing import Tuple, Set, Iterable, List




class Function:
    def __init__(self, def: CustomNodeDefinition, name: str, description: str, category: str): ...
    def UpdatePortsForUnresolved(self, inputs: Set(PortModel), outputs: Set(PortModel)) -> None: ...
    @property
    def FunctionSignature(self) -> Guid: ...
    @property
    def FunctionType(self) -> str: ...
    @property
    def NodeType(self) -> str: ...
    @property
    def Definition(self) -> CustomNodeDefinition: ...
    def ResyncWithDefinition(self, def: CustomNodeDefinition) -> None: ...


class Symbol(NodeModel):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, inPorts: Iterable[PortModel], outPorts: Iterable[PortModel], parameter: TypedParameter, elementResolver: ElementResolver): ...
    @property
    def NodeType(self) -> str: ...
    @property
    def IsInputNode(self) -> bool: ...
    @property
    def IsOutputNode(self) -> bool: ...
    @property
    def ElementResolver(self) -> ElementResolver: ...
    @ElementResolver.setter
    def ElementResolver(self, value: ElementResolver) -> None: ...
    @property
    def InputSymbol(self) -> str: ...
    @InputSymbol.setter
    def InputSymbol(self, value: str) -> None: ...
    @property
    def Parameter(self) -> TypedParameter: ...
    def GetAstIdentifierForOutputIndex(self, outputIndex: int) -> IdentifierNode: ...


class Output(NodeModel):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, inPorts: Iterable[PortModel], outPorts: Iterable[PortModel]): ...
    @property
    def NodeType(self) -> str: ...
    @property
    def IsInputNode(self) -> bool: ...
    @property
    def IsOutputNode(self) -> bool: ...
    @property
    def ElementResolver(self) -> ElementResolver: ...
    @ElementResolver.setter
    def ElementResolver(self, value: ElementResolver) -> None: ...
    @property
    def Symbol(self) -> str: ...
    @Symbol.setter
    def Symbol(self, value: str) -> None: ...
    @property
    def Return(self) -> Tuple: ...


class ICustomNodeManager:
    def AddUninitializedCustomNodesInPath(self, path: str, isTestMode: bool, isPackageMember: bool) -> Iterable[CustomNodeInfo]: ...
    def GuidFromPath(self, path: str) -> Guid: ...
    def TryGetFunctionWorkspace(self, id: Guid, isTestMode: bool) -> Tuple[bool, ICustomNodeWorkspaceModel]: ...


class ICustomNodeSource:
    def CreateCustomNodeInstance(self, id: Guid, name: str, isTestMode: bool) -> Function: ...
