from typing import Tuple, Set, Iterable, List


class MigrationManager(LogSourceBase):
    def __init__(self, displayFutureFileMessage: FutureFileCallback, displayObsoleteFileMessage: ObsoleteFileCallback): ...
    @property
    def MigrationTargets(self) -> List: ...
    @MigrationTargets.setter
    def MigrationTargets(self, value: List) -> None: ...
    def AddMigrationType(self, t: TypeLoadData) -> None: ...
    def ProcessWorkspace(self, workspaceInfo: WorkspaceInfo, xmlDoc: XmlDocument, isTestMode: bool, factory: NodeFactory) -> bool: ...
    def ProcessWorkspaceMigrations(self, currentVersion: Version, xmlDoc: XmlDocument, workspaceVersion: Version) -> None: ...
    def ProcessNodesInWorkspace(self, xmlDoc: XmlDocument, workspaceVersion: Version, currentVersion: Version, nodeFactory: NodeFactory) -> None: ...
    def MigrateXmlNode(self, currentVersion: Version, elNode: XmlNode, type: Type, workspaceVersion: Version) -> NodeMigrationData: ...
    def CreateFunctionNode(document: XmlDocument, oldNode: XmlElement, nodeIndex: int, assembly: str, name: str, signature: str) -> XmlElement: ...
    def CreateVarArgFunctionNode(document: XmlDocument, oldNode: XmlElement, nodeIndex: int, assembly: str, name: str, signature: str, inputcount: str) -> XmlElement: ...
    def CreateCodeBlockNodeModelNode(document: XmlDocument, oldNode: XmlElement, nodeIndex: int, codeText: str) -> XmlElement: ...
    def CreateNode(document: XmlDocument, oldNode: XmlElement, nodeIndex: int, type: str, name: str) -> XmlElement: ...
    @overload
    def CreateFunctionNodeFrom(srcElement: XmlElement, attribNames: Set(str)) -> XmlElement: ...
    def CreateCustomNodeFrom(document: XmlDocument, srcElement: XmlElement, id: str, name: str, description: str, inputs: List, outputs: List) -> XmlElement: ...
    @overload
    def CreateFunctionNodeFrom(srcElement: XmlElement) -> XmlElement: ...
    def CreateVarArgFunctionNodeFrom(srcElement: XmlElement) -> XmlElement: ...
    def CreateCodeBlockNodeFrom(srcElement: XmlElement) -> XmlElement: ...
    def CloneAndChangeName(element: XmlElement, type: str, name: str, cloneInnerXml: bool) -> XmlElement: ...
    def CreateDummyNode(element: XmlElement, inportCount: int, outportCount: int) -> XmlElement: ...
    def CreateMissingNode(element: XmlElement, inportCount: int, outportCount: int) -> XmlElement: ...
    def SetFunctionSignature(element: XmlElement, assemblyName: str, methodName: str, signature: str) -> None: ...
    def ReplaceAttributeValue(element: XmlElement, attribute: str, from_: str, to: str) -> None: ...
    def GetGuidFromXmlElement(element: XmlElement) -> str: ...


class PortId:
    def __init__(self, owningNode: str, portIndex: int, type: PortType): ...
    @property
    def OwningNode(self) -> str: ...
    @property
    def PortIndex(self) -> int: ...
    @property
    def PortType(self) -> PortType: ...


class NodeMigrationData:
    def __init__(self, document: XmlDocument): ...
    def FindConnector(self, startPort: PortId, endPort: PortId) -> XmlElement: ...
    def FindFirstConnector(self, portId: PortId) -> XmlElement: ...
    def RemoveFirstConnector(self, portId: PortId) -> None: ...
    def FindConnectors(self, portId: PortId) -> Iterable[XmlElement]: ...
    def ReconnectToPort(self, connector: XmlElement, port: PortId) -> None: ...
    @overload
    def CreateConnector(self, startNode: XmlElement, startIndex: int, endNode: XmlElement, endIndex: int) -> None: ...
    def CreateConnectorFromId(self, startNodeId: str, startIndex: int, endNodeId: str, endIndex: int) -> None: ...
    @overload
    def CreateConnector(self, connector: XmlElement) -> None: ...
    def AppendNode(self, node: XmlElement) -> None: ...
    @property
    def Document(self) -> XmlDocument: ...
    @property
    def MigratedNodes(self) -> Iterable[XmlElement]: ...


class NodeMigrationAttribute:
    def __init__(self, version: str): ...
    @property
    def Version(self) -> Version: ...


class WorkspaceMigrationAttribute:
    def __init__(self, from_: str, to: str): ...
    @property
    def From(self) -> Version: ...
    @property
    def To(self) -> Version: ...


class WorkspaceMigrations:
    def __init__(self, dynamoModel: DynamoModel): ...
    def Migrate_0_5_3_to_0_6_0(self, doc: XmlDocument) -> None: ...


class Decision:
    Abort = 0
    Migrate = 1
    Retain = 2


class FutureFileCallback:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, fileName: str, fileVersion: Version, currentVersion: Version) -> bool: ...
    def BeginInvoke(self, fileName: str, fileVersion: Version, currentVersion: Version, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> bool: ...


class ObsoleteFileCallback:
    def __init__(self, object: Object, method: IntPtr): ...
    def Invoke(self, fileName: str, fileVersion: Version, currentVersion: Version) -> None: ...
    def BeginInvoke(self, fileName: str, fileVersion: Version, currentVersion: Version, callback: AsyncCallback, object: Object) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
