from typing import Tuple, Set, Iterable, List


class RevitSchedulerThread:
    def __init__(self, revitApplication: UIApplication): ...
    def Initialize(self, owningScheduler: IScheduler) -> None: ...
    def Shutdown(self) -> None: ...
