from typing import Tuple, Set, Iterable, List


class BinaryVersion:
    def FromString(version: str) -> BinaryVersion: ...
    def ToString(self) -> str: ...
    def GetHashCode(self) -> int: ...
    def Equals(self, other: Object) -> bool: ...
    def op_LessThan(lhs: BinaryVersion, rhs: BinaryVersion) -> bool: ...
    def op_LessThanOrEqual(lhs: BinaryVersion, rhs: BinaryVersion) -> bool: ...
    def op_GreaterThan(lhs: BinaryVersion, rhs: BinaryVersion) -> bool: ...
    def op_GreaterThanOrEqual(lhs: BinaryVersion, rhs: BinaryVersion) -> bool: ...
    def op_Equality(lhs: BinaryVersion, rhs: BinaryVersion) -> bool: ...
    def op_Inequality(lhs: BinaryVersion, rhs: BinaryVersion) -> bool: ...
