from typing import Tuple, Set, Iterable, List


class EvaluationState:
    Success = 0
    Failed = 1


class PythonEngine:
    @property
    def InputDataMarshaler(self) -> Object: ...
    @property
    def OutputDataMarshaler(self) -> Object: ...
    @property
    def Name(self) -> str: ...
    def add_EvaluationStarted(self, value: EvaluationStartedEventHandler) -> None: ...
    def remove_EvaluationStarted(self, value: EvaluationStartedEventHandler) -> None: ...
    def add_EvaluationFinished(self, value: EvaluationFinishedEventHandler) -> None: ...
    def remove_EvaluationFinished(self, value: EvaluationFinishedEventHandler) -> None: ...
    def Evaluate(self, code: str, bindingNames: IList, bindingValues: IList) -> Object: ...


class PythonEngineManager:
    @property
    def Instance() -> PythonEngineManager: ...
