from typing import Tuple, Set, Iterable, List


class Resources:
    @property
    def ResourceManager() -> ResourceManager: ...
    @property
    def Culture() -> CultureInfo: ...
    @Culture.setter
    def Culture(value: CultureInfo) -> None: ...
    @property
    def MismatchedAssemblyList() -> str: ...
    @property
    def MismatchedAssemblyVersion() -> str: ...
    @property
    def MismatchedAssemblyVersionShortMessage() -> str: ...
    @property
    def MismatchedAssemblyVersionTitle() -> str: ...
    @property
    def SplashScreenPreLoadingAsm() -> str: ...
