from typing import Tuple, Set, Iterable, List


class ElementQueries:
    def OfFamilyType(familyType: FamilyType) -> List[Element]: ...
    def OfElementType(elementType: Type) -> List[Element]: ...
    def OfCategory(category: Category, view: View) -> List[Element]: ...
    def AtLevel(arg: Level) -> List[Element]: ...
    def ById(id: Object) -> Element: ...
    def RoomsByStatus() -> List: ...


class ElementUtils:
    def __init__(self): ...
    def UpdateLevelName(name: str) -> Tuple[str]: ...
    def GetParameterValue(param: Parameter) -> Object: ...
    def GetParameterType(parameter: Parameter) -> Type: ...
    @overload
    def SetParameterValue(param: Parameter, value: float) -> None: ...
    @overload
    def SetParameterValue(param: Parameter, value: Element) -> None: ...
    @overload
    def SetParameterValue(param: Parameter, value: int) -> None: ...
    @overload
    def SetParameterValue(param: Parameter, value: str) -> None: ...
    @overload
    def SetParameterValue(param: Parameter, value: bool) -> None: ...


class TransformUtils:
    def __init__(self): ...
    def ExtractEularAnglesFromTransform(transform: Transform) -> Tuple[Set(float)]: ...
