from typing import Tuple, Set, Iterable, List


class IPathResolver:
    @property
    def AdditionalResolutionPaths(self) -> Iterable[str]: ...
    @property
    def AdditionalNodeDirectories(self) -> Iterable[str]: ...
    @property
    def PreloadedLibraryPaths(self) -> Iterable[str]: ...
    @property
    def UserDataRootFolder(self) -> str: ...
    @property
    def CommonDataRootFolder(self) -> str: ...
    def GetDynamoUserDataLocations(self) -> Iterable[str]: ...


class IPathManager:
    @property
    def DynamoCoreDirectory(self) -> str: ...
    @property
    def HostApplicationDirectory(self) -> str: ...
    @property
    def UserDataDirectory(self) -> str: ...
    @property
    def CommonDataDirectory(self) -> str: ...
    @property
    def DefaultUserDefinitions(self) -> str: ...
    @property
    def DefinitionDirectories(self) -> Iterable[str]: ...
    @property
    def CommonDefinitions(self) -> str: ...
    @property
    def LogDirectory(self) -> str: ...
    @property
    def DefaultPackagesDirectory(self) -> str: ...
    @property
    def PackagesDirectories(self) -> Iterable[str]: ...
    @property
    def ExtensionsDirectories(self) -> Iterable[str]: ...
    @property
    def ViewExtensionsDirectories(self) -> Iterable[str]: ...
    @property
    def SamplesDirectory(self) -> str: ...
    @property
    def TemplatesDirectory(self) -> str: ...
    @property
    def BackupDirectory(self) -> str: ...
    @property
    def PreferenceFilePath(self) -> str: ...
    @property
    def PythonTemplateFilePath(self) -> str: ...
    @property
    def NodeDirectories(self) -> Iterable[str]: ...
    @property
    def PreloadedLibraries(self) -> Iterable[str]: ...
    @property
    def MajorFileVersion(self) -> int: ...
    @property
    def MinorFileVersion(self) -> int: ...
    @property
    def PathResolver(self) -> IPathResolver: ...
    def AddResolutionPath(self, path: str) -> None: ...
    def ResolveLibraryPath(self, library: str) -> Tuple[bool, str]: ...
    def ResolveDocumentPath(self, document: str) -> Tuple[bool, str]: ...


class IPreferences:
    @property
    def BackgroundPreviews(self) -> List: ...
    @BackgroundPreviews.setter
    def BackgroundPreviews(self, value: List) -> None: ...
    @property
    def ShowPreviewBubbles(self) -> bool: ...
    @ShowPreviewBubbles.setter
    def ShowPreviewBubbles(self, value: bool) -> None: ...
    @property
    def ConsoleHeight(self) -> int: ...
    @ConsoleHeight.setter
    def ConsoleHeight(self, value: int) -> None: ...
    @property
    def ShowConnector(self) -> bool: ...
    @ShowConnector.setter
    def ShowConnector(self, value: bool) -> None: ...
    @property
    def ConnectorType(self) -> ConnectorType: ...
    @ConnectorType.setter
    def ConnectorType(self, value: ConnectorType) -> None: ...
    @property
    def IsBackgroundGridVisible(self) -> bool: ...
    @IsBackgroundGridVisible.setter
    def IsBackgroundGridVisible(self, value: bool) -> None: ...
    @property
    def GridScaleFactor(self) -> Single: ...
    @GridScaleFactor.setter
    def GridScaleFactor(self, value: Single) -> None: ...
    @property
    def IsBackgroundPreviewActive(self) -> bool: ...
    @IsBackgroundPreviewActive.setter
    def IsBackgroundPreviewActive(self, value: bool) -> None: ...
    @property
    def NumberFormat(self) -> str: ...
    @NumberFormat.setter
    def NumberFormat(self, value: str) -> None: ...
    @property
    def IsADPAnalyticsReportingApproved(self) -> bool: ...
    @IsADPAnalyticsReportingApproved.setter
    def IsADPAnalyticsReportingApproved(self, value: bool) -> None: ...
    @property
    def IsFirstRun(self) -> bool: ...
    @IsFirstRun.setter
    def IsFirstRun(self, value: bool) -> None: ...
    @property
    def WindowX(self) -> float: ...
    @WindowX.setter
    def WindowX(self, value: float) -> None: ...
    @property
    def WindowY(self) -> float: ...
    @WindowY.setter
    def WindowY(self, value: float) -> None: ...
    @property
    def WindowH(self) -> float: ...
    @WindowH.setter
    def WindowH(self, value: float) -> None: ...
    @property
    def WindowW(self) -> float: ...
    @WindowW.setter
    def WindowW(self, value: float) -> None: ...
    @property
    def MaxNumRecentFiles(self) -> int: ...
    @MaxNumRecentFiles.setter
    def MaxNumRecentFiles(self, value: int) -> None: ...
    @property
    def RecentFiles(self) -> List: ...
    @RecentFiles.setter
    def RecentFiles(self, value: List) -> None: ...
    @property
    def BackupFiles(self) -> List: ...
    @BackupFiles.setter
    def BackupFiles(self, value: List) -> None: ...
    @property
    def PackageDirectoriesToUninstall(self) -> List: ...
    @PackageDirectoriesToUninstall.setter
    def PackageDirectoriesToUninstall(self, value: List) -> None: ...
    @property
    def CustomPackageFolders(self) -> List: ...
    @CustomPackageFolders.setter
    def CustomPackageFolders(self, value: List) -> None: ...
    @property
    def ShowEdges(self) -> bool: ...
    @ShowEdges.setter
    def ShowEdges(self, value: bool) -> None: ...
    def Save(self, filePath: str) -> bool: ...
    @property
    def PythonTemplateFilePath(self) -> str: ...
    @PythonTemplateFilePath.setter
    def PythonTemplateFilePath(self, value: str) -> None: ...
    @property
    def TemplateFilePath(self) -> str: ...
    @TemplateFilePath.setter
    def TemplateFilePath(self, value: str) -> None: ...
    def GetIsBackgroundPreviewActive(self, name: str) -> bool: ...
    def SetIsBackgroundPreviewActive(self, name: str, value: bool) -> None: ...
    @property
    def GraphChecksumItemsList(self) -> List: ...
    @GraphChecksumItemsList.setter
    def GraphChecksumItemsList(self, value: List) -> None: ...


class IRenderPrecisionPreference:
    @property
    def RenderPrecision(self) -> int: ...
    @RenderPrecision.setter
    def RenderPrecision(self, value: int) -> None: ...


class BackgroundPreviewActiveState:
    def __init__(self): ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def IsActive(self) -> bool: ...
    @IsActive.setter
    def IsActive(self, value: bool) -> None: ...


class IDynamoModel:
    @property
    def Workspaces(self) -> Iterable[WorkspaceModel]: ...
    @property
    def CurrentWorkspace(self) -> WorkspaceModel: ...
    def add_WorkspaceCleared(self, value: Action) -> None: ...
    def remove_WorkspaceCleared(self, value: Action) -> None: ...
    def add_ShutdownStarted(self, value: DynamoModelHandler) -> None: ...
    def remove_ShutdownStarted(self, value: DynamoModelHandler) -> None: ...
    def add_EvaluationCompleted(self, value: EventHandler) -> None: ...
    def remove_EvaluationCompleted(self, value: EventHandler) -> None: ...
    def add_WorkspaceAdded(self, value: Action) -> None: ...
    def remove_WorkspaceAdded(self, value: Action) -> None: ...
    def add_WorkspaceRemoved(self, value: Action) -> None: ...
    def remove_WorkspaceRemoved(self, value: Action) -> None: ...
    def add_WorkspaceOpening(self, value: Action) -> None: ...
    def remove_WorkspaceOpening(self, value: Action) -> None: ...
