from typing import Tuple, Set, Iterable, List


class FileSystem:
    def AbsolutePath(path: str, hintPath: str) -> str: ...
    def FileFromPath(path: str) -> FileInfo: ...
    @overload
    def ReadText(file: FileInfo) -> str: ...
    def MoveFile(path: str, newPath: str, overwrite: bool) -> None: ...
    def DeleteFile(path: str) -> None: ...
    def CopyFile(file: FileInfo, destinationPath: str, overwrite: bool) -> bool: ...
    def FileExists(path: str) -> bool: ...
    def WriteText(filePath: str, text: str) -> None: ...
    def AppendText(filePath: str, text: str) -> None: ...
    def CombinePath(strings: Set(str)) -> str: ...
    def FileExtension(path: str) -> str: ...
    def ChangePathExtension(path: str, newExtension: str) -> str: ...
    def DirectoryName(path: str) -> str: ...
    def FileName(path: str, withExtension: bool) -> str: ...
    def FileHasExtension(path: str) -> bool: ...
    def GetDirectoryContents(directory: DirectoryInfo, searchString: str, includeSubdirectories: bool) -> Dictionary: ...
    def CopyDirectory(directory: DirectoryInfo, destinationPath: str, overwriteFiles: bool) -> None: ...
    def DeleteDirectory(path: str, recursive: bool) -> None: ...
    def DirectoryExists(path: str) -> bool: ...
    def DirectoryFromPath(path: str) -> DirectoryInfo: ...
    def MoveDirectory(path: str, newPath: str, overwriteFiles: bool) -> None: ...
    def ReadImage(path: str, xSamples: int, ySamples: int) -> Set(Color): ...
    def LoadImageFromPath(path: str) -> Bitmap: ...
    @overload
    def ReadText(path: str) -> str: ...
    def WriteImage(filePath: str, fileName: str, image: Bitmap) -> bool: ...
    def ExportToCSV(filePath: str, data: Set(Set(Object))) -> bool: ...


class Image:
    def ReadFromFile(file: FileInfo) -> Bitmap: ...
    def Pixels(image: Bitmap, xSamples: Nullable, ySamples: Nullable) -> Set(Set(Color)): ...
    @overload
    def FromPixels(colors: Set(Set(Color))) -> Bitmap: ...
    @overload
    def FromPixels(colors: Set(Color), width: int, height: int) -> Bitmap: ...
    def Dimensions(image: Bitmap) -> Dictionary: ...
    def WriteToFile(path: str, image: Bitmap) -> Bitmap: ...
