from typing import Tuple, Set, Iterable, List


class DSFunction(DSFunctionBase):
    def __init__(self, functionDescription: FunctionDescriptor): ...
    @property
    def NodeType(self) -> str: ...
    @property
    def FunctionSignature(self) -> str: ...
    @property
    def IsInputNode(self) -> bool: ...


class DSFunctionBase:
    @property
    def IsConvertible(self) -> bool: ...
    def GetAstIdentifierForOutputIndex(self, outputIndex: int) -> IdentifierNode: ...
    def GetTypeHintForOutput(self, index: int) -> Type: ...




class DSVarArgFunction(DSFunctionBase):
    def __init__(self, descriptor: FunctionDescriptor): ...
    @property
    def FunctionSignature(self) -> str: ...
    @property
    def FunctionType(self) -> str: ...
    @property
    def NodeType(self) -> str: ...
    @property
    def VarInputController(self) -> VariableInputNodeController: ...




class UnresolvedFunctionException:
    def __init__(self, functionName: str): ...
    @property
    def FunctionName(self) -> str: ...
