from typing import Tuple, Set, Iterable, List


class AuthenticationManager:
    def __init__(self, authProvider: IAuthProvider): ...
    def add_LoginStateChanged(self, value: Action) -> None: ...
    def remove_LoginStateChanged(self, value: Action) -> None: ...
    @property
    def HasAuthProvider(self) -> bool: ...
    @property
    def LoginState(self) -> LoginState: ...
    @property
    def LoginStateInitial(self) -> LoginState: ...
    @property
    def Username(self) -> str: ...
    @property
    def AuthProvider(self) -> IAuthProvider: ...


class CrashPromptArgs:
    def __init__(self, details: str, overridingText: str, filePath: str): ...
    @property
    def Options(self) -> DisplayOptions: ...
    @property
    def Details(self) -> str: ...
    @property
    def OverridingText(self) -> str: ...
    @property
    def FilePath(self) -> str: ...


class CrashErrorReportArgs(CrashPromptArgs):
    def __init__(self, e: Exception): ...
    @property
    def SendRecordedCommands(self) -> bool: ...
    @SendRecordedCommands.setter
    def SendRecordedCommands(self, value: bool) -> None: ...


class CustomNodeManager(LogSourceBase):
    def __init__(self, nodeFactory: NodeFactory, migrationManager: MigrationManager, libraryServices: LibraryServices): ...
    @property
    def LoadedDefinitions(self) -> Iterable[CustomNodeDefinition]: ...
    @property
    def LoadedWorkspaces(self) -> Iterable[CustomNodeWorkspaceModel]: ...
    def GetWorkspaceById(self, customNodeId: Guid) -> CustomNodeWorkspaceModel: ...
    def add_DefinitionUpdated(self, value: Action) -> None: ...
    def remove_DefinitionUpdated(self, value: Action) -> None: ...
    def add_InfoUpdated(self, value: Action) -> None: ...
    def remove_InfoUpdated(self, value: Action) -> None: ...
    def add_CustomNodeRemoved(self, value: Action) -> None: ...
    def remove_CustomNodeRemoved(self, value: Action) -> None: ...
    @overload
    def CreateCustomNodeInstance(self, id: Guid, name: str, isTestMode: bool) -> Function: ...
    def TryGetCustomNodeData(self, id: Guid, name: str, isTestMode: bool) -> Tuple[bool, CustomNodeDefinition, CustomNodeInfo]: ...
    @overload
    def CreateCustomNodeInstance(self, id: Guid, name: str, isTestMode: bool, def: CustomNodeDefinition, info: CustomNodeInfo) -> Function: ...
    def GuidFromPath(self, path: str) -> Guid: ...
    def AddUninitializedCustomNode(self, file: str, isTestMode: bool) -> Tuple[bool, CustomNodeInfo]: ...
    def Remove(self, guid: Guid) -> None: ...
    @overload
    def AddUninitializedCustomNodesInPath(self, path: str, isTestMode: bool, isPackageMember: bool) -> Iterable[CustomNodeInfo]: ...
    @overload
    def AddUninitializedCustomNodesInPath(self, path: str, isTestMode: bool, packageInfo: PackageInfo) -> Iterable[CustomNodeInfo]: ...
    @overload
    def TryGetFunctionWorkspace(self, id: Guid, isTestMode: bool) -> Tuple[bool, CustomNodeWorkspaceModel]: ...
    @overload
    def TryGetFunctionWorkspace(self, id: Guid, isTestMode: bool) -> Tuple[bool, ICustomNodeWorkspaceModel]: ...
    def TryGetFunctionDefinition(self, id: Guid, isTestMode: bool) -> Tuple[bool, CustomNodeDefinition]: ...
    @overload
    def Contains(self, guid: Guid) -> bool: ...
    @overload
    def Contains(self, name: str) -> bool: ...
    def OpenCustomNodeWorkspace(self, xmlDoc: XmlDocument, workspaceInfo: WorkspaceInfo, isTestMode: bool) -> Tuple[bool, WorkspaceModel]: ...
    def Dispose(self) -> None: ...


class IDSDKManager:
    def __init__(self): ...
    def add_RequestLogin(self, value: Func) -> None: ...
    def remove_RequestLogin(self, value: Func) -> None: ...
    def add_LoginStateChanged(self, value: Action) -> None: ...
    def remove_LoginStateChanged(self, value: Action) -> None: ...
    @property
    def LoginState(self) -> LoginState: ...
    def IsLoggedIn(self) -> bool: ...
    def Login(self) -> bool: ...
    def Logout(self) -> None: ...
    @property
    def Username(self) -> str: ...
    @property
    def UserId(self) -> str: ...
    def SignRequest(self, m: RestRequest, client: RestClient) -> Tuple[RestRequest]: ...
    def GetAccessToken(self) -> str: ...
    def Dispose(self) -> None: ...


class NotificationObject:
    def add_PropertyChanged(self, value: PropertyChangedEventHandler) -> None: ...
    def remove_PropertyChanged(self, value: PropertyChangedEventHandler) -> None: ...


class DisplayOptions:
    IsDefaultTextOverridden = 1
    HasDetails = 2
    HasFilePath = 4
