from typing import Tuple, Set, Iterable, List


class CustomNodeDefinition:
    def __init__(self, functionId: Guid, displayName: str, nodeModels: Iterable[NodeModel]): ...
    @property
    def IsProxy(self) -> bool: ...
    @property
    def ContainsInvalidInput(self) -> bool: ...
    @property
    def FunctionName(self) -> str: ...
    @property
    def FunctionId(self) -> Guid: ...
    @property
    def DisplayParameters(self) -> Iterable[str]: ...
    @property
    def Parameters(self) -> Iterable[TypedParameter]: ...
    @property
    def ReturnKeys(self) -> Iterable[str]: ...
    @property
    def FunctionBody(self) -> Iterable[NodeModel]: ...
    @property
    def OutputNodes(self) -> Iterable[AssociativeNode]: ...
    @property
    def DisplayName(self) -> str: ...
    @property
    def ReturnType(self) -> Type: ...
    @property
    def Returns(self) -> Iterable[Tuple]: ...
    @property
    def Dependencies(self) -> Iterable[CustomNodeDefinition]: ...
    @property
    def DirectDependencies(self) -> Iterable[CustomNodeDefinition]: ...
    @property
    def MangledName(self) -> str: ...


class CustomNodeInfo:
    def __init__(self, functionId: Guid, name: str, category: str, description: str, path: str, isVisibleInDynamoLibrary: bool): ...
    @property
    def FunctionId(self) -> Guid: ...
    @FunctionId.setter
    def FunctionId(self, value: Guid) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def Category(self) -> str: ...
    @Category.setter
    def Category(self, value: str) -> None: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @property
    def Path(self) -> str: ...
    @Path.setter
    def Path(self, value: str) -> None: ...
    @property
    def IsPackageMember(self) -> bool: ...
    @IsPackageMember.setter
    def IsPackageMember(self, value: bool) -> None: ...
    @property
    def IsVisibleInDynamoLibrary(self) -> bool: ...
    @property
    def PackageInfo(self) -> PackageInfo: ...
