from typing import Tuple, Set, Iterable, List


class StartupUtils:
    def add_ASMPreloadFailure(value: Action) -> None: ...
    def remove_ASMPreloadFailure(value: Action) -> None: ...
    def PreloadShapeManager(geometryFactoryPath: str, preloaderLocation: str) -> Tuple[str, str]: ...
    @overload
    def MakeCLIModel(asmPath: str, userDataFolder: str, commonDataFolder: str, info: HostAnalyticsInfo) -> DynamoModel: ...
    @overload
    def MakeCLIModel(cmdLineArgs: CommandLineArguments) -> DynamoModel: ...
    @overload
    def MakeModel(CLImode: bool, asmPath: str, hostName: str) -> DynamoModel: ...
    @overload
    def MakeModel(CLImode: bool, noNetworkMode: bool, asmPath: str, info: HostAnalyticsInfo) -> DynamoModel: ...
    def SetLocale(cmdLineArgs: CommandLineArguments) -> str: ...
    def CheckAssemblyForVersionMismatches(assembly: Assembly) -> List: ...


class CommandLineArguments:
    def Parse(args: Set(str)) -> CommandLineArguments: ...
    @property
    def Locale(self) -> str: ...
    @Locale.setter
    def Locale(self, value: str) -> None: ...
    @property
    def CommandFilePath(self) -> str: ...
    @CommandFilePath.setter
    def CommandFilePath(self, value: str) -> None: ...
    @property
    def OpenFilePath(self) -> str: ...
    @OpenFilePath.setter
    def OpenFilePath(self, value: str) -> None: ...
    @property
    def Verbose(self) -> str: ...
    @Verbose.setter
    def Verbose(self, value: str) -> None: ...
    @property
    def ConvertFile(self) -> bool: ...
    @ConvertFile.setter
    def ConvertFile(self, value: bool) -> None: ...
    @property
    def GeometryFilePath(self) -> str: ...
    @GeometryFilePath.setter
    def GeometryFilePath(self, value: str) -> None: ...
    @property
    def ImportedPaths(self) -> Iterable[str]: ...
    @ImportedPaths.setter
    def ImportedPaths(self, value: Iterable[str]) -> None: ...
    @property
    def ASMPath(self) -> str: ...
    @ASMPath.setter
    def ASMPath(self, value: str) -> None: ...
    @property
    def KeepAlive(self) -> bool: ...
    @KeepAlive.setter
    def KeepAlive(self, value: bool) -> None: ...
    @property
    def NoConsole(self) -> bool: ...
    @NoConsole.setter
    def NoConsole(self, value: bool) -> None: ...
    @property
    def UserDataFolder(self) -> str: ...
    @UserDataFolder.setter
    def UserDataFolder(self, value: str) -> None: ...
    @property
    def CommonDataFolder(self) -> str: ...
    @CommonDataFolder.setter
    def CommonDataFolder(self, value: str) -> None: ...
    @property
    def DisableAnalytics(self) -> bool: ...
    @DisableAnalytics.setter
    def DisableAnalytics(self, value: bool) -> None: ...
    @property
    def NoNetworkMode(self) -> bool: ...
    @NoNetworkMode.setter
    def NoNetworkMode(self, value: bool) -> None: ...
    @property
    def AnalyticsInfo(self) -> HostAnalyticsInfo: ...
    @AnalyticsInfo.setter
    def AnalyticsInfo(self, value: HostAnalyticsInfo) -> None: ...
    @property
    def CERLocation(self) -> str: ...
    @CERLocation.setter
    def CERLocation(self, value: str) -> None: ...
    @property
    def ServiceMode(self) -> bool: ...
    @ServiceMode.setter
    def ServiceMode(self, value: bool) -> None: ...
