from typing import Tuple, Set, Iterable, List


class MaterialsManager:
    @property
    def DynamoMaterialId(self) -> ElementId: ...
    @property
    def DynamoErrorMaterialId(self) -> ElementId: ...
    @property
    def DynamoGStyleId(self) -> ElementId: ...
    @property
    def Instance() -> MaterialsManager: ...
    def InitializeForActiveDocumentOnIdle(self) -> None: ...
    def Reset() -> None: ...
