from typing import Tuple, Set, Iterable, List


class Configurations:
    def __init__(self): ...
    @property
    def SupportedLocaleDic() -> Dictionary: ...


class Context:


class DebugSettings(NotificationObject):
    def __init__(self): ...


class DynamoPlayerFolder:
    def __init__(self): ...
    @property
    def Path(self) -> str: ...
    @Path.setter
    def Path(self, value: str) -> None: ...
    @property
    def DisplayName(self) -> str: ...
    @DisplayName.setter
    def DisplayName(self, value: str) -> None: ...
    @property
    def Id(self) -> str: ...
    @Id.setter
    def Id(self, value: str) -> None: ...
    @property
    def IsRemovable(self) -> bool: ...
    @IsRemovable.setter
    def IsRemovable(self, value: bool) -> None: ...
    @property
    def Order(self) -> int: ...
    @Order.setter
    def Order(self, value: int) -> None: ...
    @property
    def IsValid(self) -> bool: ...
    @IsValid.setter
    def IsValid(self, value: bool) -> None: ...
    @property
    def IsDefault(self) -> bool: ...
    @IsDefault.setter
    def IsDefault(self, value: bool) -> None: ...


class DynamoPlayerFolderGroup:
    def __init__(self): ...
    @property
    def EntryPoint(self) -> str: ...
    @EntryPoint.setter
    def EntryPoint(self, value: str) -> None: ...
    @property
    def Folders(self) -> List: ...
    @Folders.setter
    def Folders(self, value: List) -> None: ...


class GraphChecksumItem:
    def __init__(self): ...
    @property
    def GraphId(self) -> str: ...
    @GraphId.setter
    def GraphId(self, value: str) -> None: ...
    @property
    def Checksum(self) -> str: ...
    @Checksum.setter
    def Checksum(self, value: str) -> None: ...


class GroupStyleItem(StyleItem):
    def __init__(self): ...


class PreferenceSettings(NotificationObject):
    def __init__(self): ...
    @property
    def IsFirstRun(self) -> bool: ...
    @IsFirstRun.setter
    def IsFirstRun(self, value: bool) -> None: ...
    @property
    def IsTimeStampIncludedInExportFilePath(self) -> bool: ...
    @IsTimeStampIncludedInExportFilePath.setter
    def IsTimeStampIncludedInExportFilePath(self, value: bool) -> None: ...
    @property
    def IsADPAnalyticsReportingApproved(self) -> bool: ...
    @IsADPAnalyticsReportingApproved.setter
    def IsADPAnalyticsReportingApproved(self, value: bool) -> None: ...
    @property
    def LibraryWidth(self) -> int: ...
    @LibraryWidth.setter
    def LibraryWidth(self, value: int) -> None: ...
    @property
    def Locale(self) -> str: ...
    @Locale.setter
    def Locale(self, value: str) -> None: ...
    @property
    def GraphicScaleUnit(self) -> str: ...
    @GraphicScaleUnit.setter
    def GraphicScaleUnit(self, value: str) -> None: ...
    @property
    def ConsoleHeight(self) -> int: ...
    @ConsoleHeight.setter
    def ConsoleHeight(self, value: int) -> None: ...
    @property
    def ShowPreviewBubbles(self) -> bool: ...
    @ShowPreviewBubbles.setter
    def ShowPreviewBubbles(self, value: bool) -> None: ...
    @property
    def UseHostScaleUnits(self) -> bool: ...
    @UseHostScaleUnits.setter
    def UseHostScaleUnits(self, value: bool) -> None: ...
    @property
    def ShowCodeBlockLineNumber(self) -> bool: ...
    @ShowCodeBlockLineNumber.setter
    def ShowCodeBlockLineNumber(self, value: bool) -> None: ...
    @property
    def ShowConnector(self) -> bool: ...
    @ShowConnector.setter
    def ShowConnector(self, value: bool) -> None: ...
    @property
    def ShowConnectorToolTip(self) -> bool: ...
    @ShowConnectorToolTip.setter
    def ShowConnectorToolTip(self, value: bool) -> None: ...
    @property
    def LibraryZoomScale(self) -> int: ...
    @LibraryZoomScale.setter
    def LibraryZoomScale(self, value: int) -> None: ...
    @property
    def PythonScriptZoomScale(self) -> int: ...
    @PythonScriptZoomScale.setter
    def PythonScriptZoomScale(self, value: int) -> None: ...
    @property
    def ConnectorType(self) -> ConnectorType: ...
    @ConnectorType.setter
    def ConnectorType(self, value: ConnectorType) -> None: ...
    @property
    def BackgroundPreviews(self) -> List: ...
    @BackgroundPreviews.setter
    def BackgroundPreviews(self, value: List) -> None: ...
    def GetIsBackgroundPreviewActive(self, name: str) -> bool: ...
    def SetIsBackgroundPreviewActive(self, name: str, value: bool) -> None: ...
    @property
    def IsBackgroundGridVisible(self) -> bool: ...
    @IsBackgroundGridVisible.setter
    def IsBackgroundGridVisible(self, value: bool) -> None: ...
    @property
    def GridScaleFactor(self) -> Single: ...
    @GridScaleFactor.setter
    def GridScaleFactor(self, value: Single) -> None: ...
    @property
    def DefaultScaleFactor(self) -> float: ...
    @DefaultScaleFactor.setter
    def DefaultScaleFactor(self, value: float) -> None: ...
    @property
    def IsBackgroundPreviewActive(self) -> bool: ...
    @IsBackgroundPreviewActive.setter
    def IsBackgroundPreviewActive(self, value: bool) -> None: ...
    @property
    def RenderPrecision(self) -> int: ...
    @RenderPrecision.setter
    def RenderPrecision(self, value: int) -> None: ...
    @property
    def ShowEdges(self) -> bool: ...
    @ShowEdges.setter
    def ShowEdges(self, value: bool) -> None: ...
    @property
    def UseRenderInstancing(self) -> bool: ...
    @UseRenderInstancing.setter
    def UseRenderInstancing(self, value: bool) -> None: ...
    @property
    def ShowDetailedLayout(self) -> bool: ...
    @ShowDetailedLayout.setter
    def ShowDetailedLayout(self, value: bool) -> None: ...
    @property
    def WindowX(self) -> float: ...
    @WindowX.setter
    def WindowX(self, value: float) -> None: ...
    @property
    def WindowY(self) -> float: ...
    @WindowY.setter
    def WindowY(self, value: float) -> None: ...
    @property
    def WindowW(self) -> float: ...
    @WindowW.setter
    def WindowW(self, value: float) -> None: ...
    @property
    def WindowH(self) -> float: ...
    @WindowH.setter
    def WindowH(self, value: float) -> None: ...
    @property
    def UseHardwareAcceleration(self) -> bool: ...
    @UseHardwareAcceleration.setter
    def UseHardwareAcceleration(self, value: bool) -> None: ...
    @property
    def HomePageSettings(self) -> List: ...
    @HomePageSettings.setter
    def HomePageSettings(self, value: List) -> None: ...
    @property
    def NumberFormat(self) -> str: ...
    @NumberFormat.setter
    def NumberFormat(self, value: str) -> None: ...
    @property
    def MaxNumRecentFiles(self) -> int: ...
    @MaxNumRecentFiles.setter
    def MaxNumRecentFiles(self, value: int) -> None: ...
    @property
    def RecentFiles(self) -> List: ...
    @RecentFiles.setter
    def RecentFiles(self, value: List) -> None: ...
    @property
    def BackupLocation(self) -> str: ...
    @BackupLocation.setter
    def BackupLocation(self, value: str) -> None: ...
    @property
    def TemplateFilePath(self) -> str: ...
    @TemplateFilePath.setter
    def TemplateFilePath(self, value: str) -> None: ...
    @property
    def BackupFiles(self) -> List: ...
    @BackupFiles.setter
    def BackupFiles(self, value: List) -> None: ...
    @property
    def CustomPackageFolders(self) -> List: ...
    @CustomPackageFolders.setter
    def CustomPackageFolders(self, value: List) -> None: ...
    @property
    def DisableTrustWarnings(self) -> bool: ...
    @DisableTrustWarnings.setter
    def DisableTrustWarnings(self, value: bool) -> None: ...
    @property
    def GraphChecksumItemsList(self) -> List: ...
    @GraphChecksumItemsList.setter
    def GraphChecksumItemsList(self, value: List) -> None: ...
    @property
    def TrustedLocations(self) -> List: ...
    @property
    def PackageDirectoriesToUninstall(self) -> List: ...
    @PackageDirectoriesToUninstall.setter
    def PackageDirectoriesToUninstall(self, value: List) -> None: ...
    @property
    def PythonTemplateFilePath(self) -> str: ...
    @PythonTemplateFilePath.setter
    def PythonTemplateFilePath(self, value: str) -> None: ...
    @property
    def BackupInterval(self) -> int: ...
    @BackupInterval.setter
    def BackupInterval(self, value: int) -> None: ...
    @property
    def BackupFilesCount(self) -> int: ...
    @BackupFilesCount.setter
    def BackupFilesCount(self, value: int) -> None: ...
    @property
    def PackageDownloadTouAccepted(self) -> bool: ...
    @PackageDownloadTouAccepted.setter
    def PackageDownloadTouAccepted(self, value: bool) -> None: ...
    @property
    def OpenFileInManualExecutionMode(self) -> bool: ...
    @OpenFileInManualExecutionMode.setter
    def OpenFileInManualExecutionMode(self, value: bool) -> None: ...
    @property
    def IsIronPythonDialogDisabled(self) -> bool: ...
    @IsIronPythonDialogDisabled.setter
    def IsIronPythonDialogDisabled(self, value: bool) -> None: ...
    @property
    def ShowTabsAndSpacesInScriptEditor(self) -> bool: ...
    @ShowTabsAndSpacesInScriptEditor.setter
    def ShowTabsAndSpacesInScriptEditor(self, value: bool) -> None: ...
    @property
    def EnableNodeAutoComplete(self) -> bool: ...
    @EnableNodeAutoComplete.setter
    def EnableNodeAutoComplete(self, value: bool) -> None: ...
    @property
    def DefaultEnableLegacyPolyCurveBehavior(self) -> bool: ...
    @DefaultEnableLegacyPolyCurveBehavior.setter
    def DefaultEnableLegacyPolyCurveBehavior(self, value: bool) -> None: ...
    @property
    def HideNodesBelowSpecificConfidenceLevel(self) -> bool: ...
    @HideNodesBelowSpecificConfidenceLevel.setter
    def HideNodesBelowSpecificConfidenceLevel(self, value: bool) -> None: ...
    @property
    def MLRecommendationConfidenceLevel(self) -> int: ...
    @MLRecommendationConfidenceLevel.setter
    def MLRecommendationConfidenceLevel(self, value: int) -> None: ...
    @property
    def MLRecommendationNumberOfResults(self) -> int: ...
    @MLRecommendationNumberOfResults.setter
    def MLRecommendationNumberOfResults(self, value: int) -> None: ...
    @property
    def HideAutocompleteMethodOptions(self) -> bool: ...
    @HideAutocompleteMethodOptions.setter
    def HideAutocompleteMethodOptions(self, value: bool) -> None: ...
    @property
    def EnableNotificationCenter(self) -> bool: ...
    @EnableNotificationCenter.setter
    def EnableNotificationCenter(self, value: bool) -> None: ...
    @property
    def EnablePersistExtensions(self) -> bool: ...
    @EnablePersistExtensions.setter
    def EnablePersistExtensions(self, value: bool) -> None: ...
    @property
    def EnableStaticSplashScreen(self) -> bool: ...
    @EnableStaticSplashScreen.setter
    def EnableStaticSplashScreen(self, value: bool) -> None: ...
    @property
    def IsMLAutocompleteTOUApproved(self) -> bool: ...
    @IsMLAutocompleteTOUApproved.setter
    def IsMLAutocompleteTOUApproved(self, value: bool) -> None: ...
    @property
    def DefaultPythonEngine(self) -> str: ...
    @DefaultPythonEngine.setter
    def DefaultPythonEngine(self, value: str) -> None: ...
    @property
    def SelectedPackagePathForInstall(self) -> str: ...
    @SelectedPackagePathForInstall.setter
    def SelectedPackagePathForInstall(self, value: str) -> None: ...
    @property
    def NamespacesToExcludeFromLibrary(self) -> List: ...
    @NamespacesToExcludeFromLibrary.setter
    def NamespacesToExcludeFromLibrary(self, value: List) -> None: ...
    @property
    def NamespacesToExcludeFromLibrarySpecified(self) -> bool: ...
    @NamespacesToExcludeFromLibrarySpecified.setter
    def NamespacesToExcludeFromLibrarySpecified(self, value: bool) -> None: ...
    @property
    def ViewExtensionSettings(self) -> List: ...
    @ViewExtensionSettings.setter
    def ViewExtensionSettings(self, value: List) -> None: ...
    @property
    def DisableBuiltinPackages(self) -> bool: ...
    @DisableBuiltinPackages.setter
    def DisableBuiltinPackages(self, value: bool) -> None: ...
    @property
    def DisableCustomPackageLocations(self) -> bool: ...
    @DisableCustomPackageLocations.setter
    def DisableCustomPackageLocations(self, value: bool) -> None: ...
    @property
    def DefaultRunType(self) -> RunType: ...
    @DefaultRunType.setter
    def DefaultRunType(self, value: RunType) -> None: ...
    @property
    def DefaultNodeAutocompleteSuggestion(self) -> NodeAutocompleteSuggestion: ...
    @DefaultNodeAutocompleteSuggestion.setter
    def DefaultNodeAutocompleteSuggestion(self, value: NodeAutocompleteSuggestion) -> None: ...
    @property
    def ShowRunPreview(self) -> bool: ...
    @ShowRunPreview.setter
    def ShowRunPreview(self, value: bool) -> None: ...
    @property
    def GroupStyleItemsList(self) -> List: ...
    @GroupStyleItemsList.setter
    def GroupStyleItemsList(self, value: List) -> None: ...
    @property
    def NodeSearchTagSizeLimit(self) -> int: ...
    @NodeSearchTagSizeLimit.setter
    def NodeSearchTagSizeLimit(self, value: int) -> None: ...
    @property
    def IronPythonResolveTargetVersion(self) -> str: ...
    @IronPythonResolveTargetVersion.setter
    def IronPythonResolveTargetVersion(self, value: str) -> None: ...
    @property
    def ReadNotificationIds(self) -> List: ...
    @ReadNotificationIds.setter
    def ReadNotificationIds(self, value: List) -> None: ...
    @property
    def EnableDynamoPlayerRenamedWatchAsOutput(self) -> bool: ...
    @EnableDynamoPlayerRenamedWatchAsOutput.setter
    def EnableDynamoPlayerRenamedWatchAsOutput(self, value: bool) -> None: ...
    @property
    def DynamoPlayerFolderGroups(self) -> List: ...
    @DynamoPlayerFolderGroups.setter
    def DynamoPlayerFolderGroups(self, value: List) -> None: ...
    def Save(self, filePath: str) -> bool: ...
    def SaveInternal(self, preferenceFilePath: str) -> bool: ...
    def Load(filePath: str) -> PreferenceSettings: ...
    def LoadContent(content: str) -> PreferenceSettings: ...
    @property
    def PredefinedGroupStyleFontSizes(self) -> ObservableCollection: ...
    def GetPythonTemplateFilePath() -> str: ...
    def IsTrustedLocation(self, location: str) -> bool: ...
    def AskForTrustedLocation(isOpenedFile: bool, isFileInTrustedLocation: bool, isHomeSpace: bool, isShowStartPage: bool, isDisableTrustWarnings: bool) -> AskForTrustedLocationResult: ...
    def add_MessageLogged(self, value: Action) -> None: ...
    def remove_MessageLogged(self, value: Action) -> None: ...
    def StaticFields(self) -> List: ...
    @property
    def IsCreatedFromValidFile(self) -> bool: ...


class StyleItem(NotificationObject):
    def __init__(self): ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def HexColorString(self) -> str: ...
    @HexColorString.setter
    def HexColorString(self, value: str) -> None: ...
    @property
    def IsDefault(self) -> bool: ...
    @IsDefault.setter
    def IsDefault(self, value: bool) -> None: ...
    @property
    def FontSize(self) -> int: ...
    @FontSize.setter
    def FontSize(self, value: int) -> None: ...
    @property
    def GroupStyleId(self) -> Guid: ...
    @GroupStyleId.setter
    def GroupStyleId(self, value: Guid) -> None: ...


class ViewExtensionSettings:
    def __init__(self): ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def UniqueId(self) -> str: ...
    @UniqueId.setter
    def UniqueId(self, value: str) -> None: ...
    @property
    def DisplayMode(self) -> ViewExtensionDisplayMode: ...
    @DisplayMode.setter
    def DisplayMode(self, value: ViewExtensionDisplayMode) -> None: ...
    @property
    def WindowSettings(self) -> WindowSettings: ...
    @WindowSettings.setter
    def WindowSettings(self, value: WindowSettings) -> None: ...
    @property
    def IsOpen(self) -> bool: ...
    @IsOpen.setter
    def IsOpen(self, value: bool) -> None: ...


class ViewExtensionDisplayMode:
    Unspecified = 0
    DockRight = 1
    FloatingWindow = 2


class WindowSettings:
    def __init__(self): ...
    @property
    def Status(self) -> WindowStatus: ...
    @Status.setter
    def Status(self, value: WindowStatus) -> None: ...
    @property
    def Left(self) -> int: ...
    @Left.setter
    def Left(self, value: int) -> None: ...
    @property
    def Top(self) -> int: ...
    @Top.setter
    def Top(self, value: int) -> None: ...
    @property
    def Width(self) -> int: ...
    @Width.setter
    def Width(self, value: int) -> None: ...
    @property
    def Height(self) -> int: ...
    @Height.setter
    def Height(self, value: int) -> None: ...


class WindowStatus:
    Normal = 0
    Maximized = 1


class AskForTrustedLocationResult:
    Ask = 0
    DontAsk = 1
    UnableToAsk = 2
