from typing import Tuple, Set, Iterable, List


class PresetModel(ModelBase):
    def __init__(self, name: str, description: str, inputsToSave: Iterable[NodeModel]): ...
    @property
    def Name(self) -> str: ...
    @property
    def Description(self) -> str: ...
    @property
    def Nodes(self) -> Iterable[NodeModel]: ...
    @property
    def SerializedNodes(self) -> Iterable[XmlElement]: ...
