from typing import Tuple, Set, Iterable, List


class DocumentManager:
    def add_OnLogError(value: Action) -> None: ...
    def remove_OnLogError(value: Action) -> None: ...
    @property
    def Instance() -> DocumentManager: ...
    def ElementExistsInDocument(self, id: ElementUUID) -> bool: ...
    def DeleteElement(self, element: ElementUUID) -> None: ...
    def ElementsOfType(self) -> Iterable[T]: ...
    def ElementsOfCategory(self, category: BuiltInCategory) -> Iterable[Element]: ...
    def HandleDocumentActivation(self, revitView: View) -> None: ...
    @property
    def CurrentDBDocument(self) -> Document: ...
    @property
    def ActiveDocumentHashCode(self) -> int: ...
    @property
    def CurrentUIDocument(self) -> UIDocument: ...
    @CurrentUIDocument.setter
    def CurrentUIDocument(self, value: UIDocument) -> None: ...
    @property
    def CurrentUIApplication(self) -> UIApplication: ...
    @CurrentUIApplication.setter
    def CurrentUIApplication(self, value: UIApplication) -> None: ...
    def Regenerate() -> None: ...


class SerializableId:
    def __init__(self): ...
    @property
    def StringID(self) -> str: ...
    @StringID.setter
    def StringID(self, value: str) -> None: ...
    @property
    def IntID(self) -> Int64: ...
    @IntID.setter
    def IntID(self, value: Int64) -> None: ...
    def Equals(self, other: Object) -> bool: ...
    def GetHashCode(self) -> int: ...


class MultipleSerializableId:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, elements: Iterable[Element]): ...
    @overload
    def __init__(self, stringIDs: List, intIDs: List): ...
    @property
    def StringIDs(self) -> List: ...
    @StringIDs.setter
    def StringIDs(self, value: List) -> None: ...
    @property
    def IntIDs(self) -> List: ...
    @IntIDs.setter
    def IntIDs(self, value: List) -> None: ...
    def Equals(self, other: Object) -> bool: ...
    def GetHashCode(self) -> int: ...
    def isSubset(self, other: MultipleSerializableId) -> bool: ...


class ElementUUID:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, uuid: str): ...
    @property
    def UUID(self) -> str: ...
    @UUID.setter
    def UUID(self, value: str) -> None: ...


class ElementBinder:
    def __init__(self): ...
    def GetElementIdFromTrace(document: Document) -> ElementId: ...
    def GetElementUUIDFromTrace(document: Document) -> ElementUUID: ...
    def GetElementUUIDsFromTrace(document: Document) -> List: ...
    def GetIdForUUID(document: Document, uuid: ElementUUID) -> ElementId: ...
    @overload
    def SetElementForTrace(element: Element) -> None: ...
    def SetElementsForTrace(elements: Iterable[Element]) -> None: ...
    @overload
    def SetElementForTrace(elementId: ElementId, elementUUID: ElementUUID) -> None: ...
    def GetElementFromTrace(document: Document) -> T: ...
    def GetElementsFromTrace(document: Document) -> Iterable[T]: ...
    def CleanupAndSetElementForTrace(document: Document, newElement: Element) -> None: ...
    def SetRawDataForTrace(data: str) -> None: ...
    def GetRawDataFromTrace() -> str: ...
    def GetElementAndTraceData(document: Document) -> Tuple: ...
    def GetNodesFromElementIds(ids: Iterable[ElementId], workspace: WorkspaceModel, engine: EngineController) -> Iterable[NodeModel]: ...
    def SetElementFreezeState(workspace: WorkspaceModel, node: NodeModel, engine: EngineController) -> None: ...


