from typing import Tuple, Set, Iterable, List


class NodeNameAttribute:
    def __init__(self, elementName: str): ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...


class NodeCategoryAttribute:
    def __init__(self, category: str): ...
    @property
    def ElementCategory(self) -> str: ...
    @ElementCategory.setter
    def ElementCategory(self, value: str) -> None: ...


class NodeSearchTagsAttribute:
    @overload
    def __init__(self, tagsID: str, resourceType: Type): ...
    @overload
    def __init__(self, tags: Set(str)): ...
    @property
    def Tags(self) -> List: ...
    @Tags.setter
    def Tags(self, value: List) -> None: ...


class NodeDescriptionAttribute:
    @overload
    def __init__(self, description: str): ...
    @overload
    def __init__(self, descriptionResourceID: str, resourceType: Type): ...
    @property
    def ElementDescription(self) -> str: ...
    @ElementDescription.setter
    def ElementDescription(self, value: str) -> None: ...


class DoNotLoadOnPlatformsAttribute:
    def __init__(self, values: Set(str)): ...
    @property
    def Values(self) -> Set(str): ...
    @Values.setter
    def Values(self, value: Set(str)) -> None: ...


class NodeDeprecatedAttribute:
    def __init__(self): ...


class AlsoKnownAsAttribute:
    def __init__(self, values: Set(str)): ...
    @property
    def Values(self) -> Set(str): ...
    @Values.setter
    def Values(self, value: Set(str)) -> None: ...


class IsMetaNodeAttribute:
    def __init__(self): ...


class IsDesignScriptCompatibleAttribute:
    def __init__(self): ...


class NodeObsoleteAttribute:
    @overload
    def __init__(self, message: str): ...
    @overload
    def __init__(self, descriptionResourceID: str, resourceType: Type): ...


class InPortNamesAttribute:
    @overload
    def __init__(self, resourceType: Type, resourceNames: Set(str)): ...
    @overload
    def __init__(self, names: Set(str)): ...
    @property
    def PortNames(self) -> Iterable[str]: ...


class InPortDescriptionsAttribute:
    @overload
    def __init__(self, resourceType: Type, resourceNames: Set(str)): ...
    @overload
    def __init__(self, descriptions: Set(str)): ...
    @property
    def PortDescriptions(self) -> Iterable[str]: ...


class InPortTypesAttribute:
    @overload
    def __init__(self, resourceType: Type, resourceNames: Set(str)): ...
    @overload
    def __init__(self, types: Set(str)): ...
    @property
    def PortTypes(self) -> Iterable[str]: ...


class OutPortNamesAttribute:
    @overload
    def __init__(self, resourceType: Type, resourceNames: Set(str)): ...
    @overload
    def __init__(self, names: Set(str)): ...
    @property
    def PortNames(self) -> Iterable[str]: ...


class OutPortDescriptionsAttribute:
    @overload
    def __init__(self, resourceType: Type, resourceNames: Set(str)): ...
    @overload
    def __init__(self, descriptions: Set(str)): ...
    @property
    def PortDescriptions(self) -> Iterable[str]: ...


class OutPortTypesAttribute:
    @overload
    def __init__(self, resourceType: Type, resourceNames: Set(str)): ...
    @overload
    def __init__(self, types: Set(str)): ...
    @property
    def PortTypes(self) -> Iterable[str]: ...


class CodeBlockNodeModel(NodeModel):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, libraryServices: LibraryServices): ...
    @overload
    def __init__(self, code: str, x: float, y: float, libraryServices: LibraryServices, resolver: ElementResolver): ...
    @overload
    def __init__(self, userCode: str, guid: Guid, xPos: float, yPos: float, libraryServices: LibraryServices, resolver: ElementResolver): ...
    @property
    def NodeType(self) -> str: ...
    @property
    def ShouldFocus(self) -> bool: ...
    @property
    def ElementResolver(self) -> ElementResolver: ...
    @ElementResolver.setter
    def ElementResolver(self, value: ElementResolver) -> None: ...
    @property
    def IsInputNode(self) -> bool: ...
    @property
    def IsOutputNode(self) -> bool: ...
    @property
    def IsConvertible(self) -> bool: ...
    @property
    def AstIdentifierBase(self) -> str: ...
    @property
    def Code(self) -> str: ...
    def SetCodeContent(self, newCode: str, workspaceElementResolver: ElementResolver) -> None: ...
    @property
    def CodeStatements(self) -> Iterable[Statement]: ...
    def GetAstIdentifierForOutputIndex(self, outputIndex: int) -> IdentifierNode: ...
    def GetRawAstIdentifierForOutputIndex(self, portIndex: int) -> IdentifierNode: ...
    def GetTypeHintForOutput(self, index: int) -> Type: ...
    def Migrate_2_0_0(data: NodeMigrationData) -> NodeMigrationData: ...


class Statement:
    def CreateInstance(parsedNode: Node) -> Statement: ...
    def GetReferencedVariables(astNode: Node, refVariableList: List) -> None: ...
    def GetDefinedVariableNames(s: Statement) -> List: ...
    @property
    def StartLine(self) -> int: ...
    @property
    def EndLine(self) -> int: ...
    @property
    def FirstDefinedVariable(self) -> Variable: ...
    @property
    def CurrentState(self) -> State: ...
    @property
    def CurrentType(self) -> StatementType: ...
    @property
    def AstNode(self) -> Node: ...


class Variable:
    def __init__(self, identNode: IdentifierNode): ...
    @property
    def Row(self) -> int: ...
    @property
    def StartColumn(self) -> int: ...
    @property
    def EndColumn(self) -> int: ...
    @property
    def Name(self) -> str: ...
    @property
    def NameWithIndex(self) -> str: ...
    def SetCorrectColumn(refVar: List, type: StatementType, line: int) -> None: ...


class CodeBlockUtils:


class DummyNode(NodeModel):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, inputCount: int, outputCount: int, legacyName: str, originalElement: XmlElement, legacyAssembly: str, nodeNature: Nature): ...
    @overload
    def __init__(self, id: str, inputCount: int, outputCount: int, legacyAssembly: str, originalElement: JObject): ...
    @overload
    def __init__(self, id: str, inputCount: int, outputCount: int, legacyAssembly: str, functionName: str, originalElement: JObject): ...
    @overload
    def __init__(self, id: str, inputCount: int, outputCount: int, legacyAssembly: str, functionName: str, typeName: str, originalElement: JObject): ...
    @property
    def InputCount(self) -> int: ...
    @property
    def OutputCount(self) -> int: ...
    @property
    def LegacyNodeName(self) -> str: ...
    @property
    def LegacyAssembly(self) -> str: ...
    @property
    def TypeName(self) -> str: ...
    @property
    def FunctionName(self) -> str: ...
    @property
    def LegacyFullName(self) -> str: ...
    @property
    def NodeNature(self) -> Nature: ...
    @property
    def OriginalNodeContent(self) -> Object: ...






class BuiltinNodeCategories:


class Utilities:


class NodeInputTypes:
    numberInput = 0
    booleanInput = 1
    stringInput = 2
    colorInput = 3
    dateInput = 4
    selectionInput = 5
    hostSelection = 6
    dropdownSelection = 7


class NodeInputData:
    def __init__(self): ...
    @property
    def Id(self) -> Guid: ...
    @Id.setter
    def Id(self, value: Guid) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def Type(self) -> NodeInputTypes: ...
    @Type.setter
    def Type(self, value: NodeInputTypes) -> None: ...
    @property
    def Type2(self) -> NodeInputTypes: ...
    @Type2.setter
    def Type2(self, value: NodeInputTypes) -> None: ...
    @property
    def Value(self) -> str: ...
    @Value.setter
    def Value(self, value: str) -> None: ...
    @property
    def Choices(self) -> List: ...
    @Choices.setter
    def Choices(self, value: List) -> None: ...
    @property
    def MaximumValue(self) -> Nullable: ...
    @MaximumValue.setter
    def MaximumValue(self, value: Nullable) -> None: ...
    @property
    def MinimumValue(self) -> Nullable: ...
    @MinimumValue.setter
    def MinimumValue(self, value: Nullable) -> None: ...
    @property
    def StepValue(self) -> Nullable: ...
    @StepValue.setter
    def StepValue(self, value: Nullable) -> None: ...
    @property
    def NumberType(self) -> str: ...
    @NumberType.setter
    def NumberType(self, value: str) -> None: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @property
    def SelectedIndex(self) -> Nullable: ...
    @SelectedIndex.setter
    def SelectedIndex(self, value: Nullable) -> None: ...
    def Equals(self, obj: Object) -> bool: ...


class Info:
    def Equals(self, other: Object) -> bool: ...
    def GetHashCode(self) -> int: ...
    def ToString(self) -> str: ...


class NodeModel(ModelBase):
    @property
    def CreationName(self) -> str: ...
    @property
    def NodeType(self) -> str: ...
    def DispatchOnUIThread(self, a: Action) -> None: ...
    def add_PortConnected(self, value: Action) -> None: ...
    def remove_PortConnected(self, value: Action) -> None: ...
    def add_PortDisconnected(self, value: Action) -> None: ...
    def remove_PortDisconnected(self, value: Action) -> None: ...
    def add_NodeExecutionBegin(self, value: Action) -> None: ...
    def remove_NodeExecutionBegin(self, value: Action) -> None: ...
    def add_NodeMessagesClearing(self, value: Action) -> None: ...
    def remove_NodeMessagesClearing(self, value: Action) -> None: ...
    def add_NodeInfoMessagesClearing(self, value: Action) -> None: ...
    def remove_NodeInfoMessagesClearing(self, value: Action) -> None: ...
    def add_NodeExecutionEnd(self, value: Action) -> None: ...
    def remove_NodeExecutionEnd(self, value: Action) -> None: ...
    @property
    def GUID(self) -> Guid: ...
    @GUID.setter
    def GUID(self, value: Guid) -> None: ...
    @property
    def AllConnectors(self) -> Iterable[ConnectorModel]: ...
    @property
    def IsCustomFunction(self) -> bool: ...
    @property
    def IsVisible(self) -> bool: ...
    @property
    def IsInputNode(self) -> bool: ...
    @property
    def IsSetAsInput(self) -> bool: ...
    @IsSetAsInput.setter
    def IsSetAsInput(self, value: bool) -> None: ...
    @property
    def IsOutputNode(self) -> bool: ...
    @property
    def IsSetAsOutput(self) -> bool: ...
    @IsSetAsOutput.setter
    def IsSetAsOutput(self, value: bool) -> None: ...
    @property
    def State(self) -> ElementState: ...
    @State.setter
    def State(self, value: ElementState) -> None: ...
    @property
    def IsInErrorState(self) -> bool: ...
    @property
    def PreviewPinned(self) -> bool: ...
    @property
    def NodeInfos(self) -> List: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def InPorts(self) -> ObservableCollection: ...
    @property
    def OutPorts(self) -> ObservableCollection: ...
    @property
    def InputNodes(self) -> IDictionary: ...
    @property
    def OutputNodes(self) -> IDictionary: ...
    @property
    def ArgumentLacing(self) -> LacingStrategy: ...
    @property
    def Category(self) -> str: ...
    @Category.setter
    def Category(self, value: str) -> None: ...
    @property
    def DictionaryLink(self) -> str: ...
    @DictionaryLink.setter
    def DictionaryLink(self, value: str) -> None: ...
    @property
    def CachedValue(self) -> MirrorData: ...
    @property
    def Tags(self) -> List: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @property
    def CanUpdatePeriodically(self) -> bool: ...
    @CanUpdatePeriodically.setter
    def CanUpdatePeriodically(self, value: bool) -> None: ...
    @property
    def AstIdentifierForPreview(self) -> IdentifierNode: ...
    @property
    def IsConvertible(self) -> bool: ...
    @property
    def AstIdentifierBase(self) -> str: ...
    @property
    def AstIdentifierGuid(self) -> str: ...
    @property
    def DisplayLabels(self) -> bool: ...
    @DisplayLabels.setter
    def DisplayLabels(self, value: bool) -> None: ...
    @property
    def IsPartiallyApplied(self) -> bool: ...
    @property
    def AreAllOutputsConnected(self) -> bool: ...
    def GetDescriptionStringFromAttributes(self) -> str: ...
    def GetAstIdentifierForOutputIndex(self, outputIndex: int) -> IdentifierNode: ...
    def GetTypeHintForOutput(self, index: int) -> Type: ...
    @property
    def IsFrozen(self) -> bool: ...
    @IsFrozen.setter
    def IsFrozen(self, value: bool) -> None: ...
    def ShouldSerializeX(self) -> bool: ...
    def ShouldSerializeY(self) -> bool: ...
    @property
    def InputData(self) -> NodeInputData: ...
    @property
    def OutputData(self) -> NodeOutputData: ...
    @property
    def DismissedAlerts(self) -> ObservableCollection: ...
    @DismissedAlerts.setter
    def DismissedAlerts(self, value: ObservableCollection) -> None: ...
    @property
    def DismissedAlertsCount(self) -> int: ...
    def GetValue(self, outPortIndex: int, engine: EngineController) -> MirrorData: ...
    def SetNameFromNodeNameAttribute(self) -> None: ...
    @property
    def RaisesModificationEvents(self) -> bool: ...
    @RaisesModificationEvents.setter
    def RaisesModificationEvents(self, value: bool) -> None: ...
    def add_Modified(self, value: Action) -> None: ...
    def remove_Modified(self, value: Action) -> None: ...
    def OnNodeModified(self, forceExecute: bool) -> None: ...
    def add_UpdateASTCollection(self, value: Action) -> None: ...
    def remove_UpdateASTCollection(self, value: Action) -> None: ...
    def OnUpdateASTCollection(self) -> None: ...
    def BuildOutputAst(self, inputAstNodes: List) -> Iterable[AssociativeNode]: ...
    def UseLevelAndReplicationGuide(self, inputs: List) -> None: ...
    def add_ConnectorAdded(self, value: Action) -> None: ...
    def remove_ConnectorAdded(self, value: Action) -> None: ...
    @property
    def IsTopMostNode(self) -> bool: ...
    def TryGetInput(self, data: int) -> Tuple[bool, Tuple]: ...
    def TryGetOutput(self, output: int) -> Tuple[bool, HashSet]: ...
    def ClearErrorsAndWarnings(self) -> None: ...
    def ClearInfoMessages(self) -> None: ...
    def SelectNeighbors(self) -> None: ...
    def SelectDownstreamNeighbours(self) -> None: ...
    def SelectUpstreamNeighbours(self) -> None: ...
    def SelectUpstreamAndDownstreamNeighbours(self) -> None: ...
    def Error(self, p: str) -> None: ...
    def Info(self, p: str, isPersistent: bool) -> None: ...
    def Warning(self, p: str, isPersistent: bool) -> None: ...
    def NotifyAstBuildBroken(self, p: str) -> None: ...
    def RegisterInputPorts(self, portDatas: Iterable[PortData]) -> None: ...
    def RegisterOutputPorts(self, portDatas: Iterable[PortData]) -> None: ...
    def RegisterAllPorts(self) -> None: ...
    def Deselect(self) -> None: ...
    @property
    def IsModified(self) -> bool: ...
    @property
    def NeedsForceExecution(self) -> bool: ...
    def MarkNodeAsModified(self, forceExecute: bool) -> None: ...
    def ClearDirtyFlag(self) -> None: ...
    @overload
    def RequestVisualUpdateAsync(self, scheduler: IScheduler, engine: EngineController, factory: IRenderPackageFactory, forceUpdate: bool) -> bool: ...
    @overload
    def RequestVisualUpdateAsync(self, scheduler: IScheduler, engine: EngineController, factory: IRenderPackageFactory, forceUpdate: bool, ignoreIsVisible: bool) -> bool: ...
    def add_RequestRenderPackages(self, value: Func) -> None: ...
    def remove_RequestRenderPackages(self, value: Func) -> None: ...
    def MigrateShortestLacingToAutoLacing(data: NodeMigrationData) -> NodeMigrationData: ...
    @property
    def ShouldDisplayPreview(self) -> bool: ...
    def add_RenderPackagesUpdated(self, value: Action) -> None: ...
    def remove_RenderPackagesUpdated(self, value: Action) -> None: ...


class ElementState:
    Dead = 0
    Active = 1
    Warning = 2
    PersistentWarning = 3
    Error = 4
    AstBuildBroken = 5
    Info = 6
    PersistentInfo = 7
    MigratedFormula = 8


class LacingStrategy:
    Disabled = 0
    First = 1
    Shortest = 2
    Longest = 3
    CrossProduct = 4
    Auto = 5


class PortEventType:
    MouseEnter = 0
    MouseLeave = 1
    MouseLeftButtonDown = 2


class SnapExtensionEdges:
    #None = 0
    Top = 1
    Bottom = 2


class UIDispatcherEventArgs:
    def __init__(self, a: Action): ...
    @property
    def ActionToDispatch(self) -> Action: ...
    @ActionToDispatch.setter
    def ActionToDispatch(self, value: Action) -> None: ...


class NodeModelExtensions:


class NodeOutputTypes:
    integerOutput = 0
    floatOutput = 1
    booleanOutput = 2
    stringOutput = 3
    unknownOutput = 4


class NodeOutputData:
    def __init__(self): ...
    @property
    def Id(self) -> Guid: ...
    @Id.setter
    def Id(self, value: Guid) -> None: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def Type(self) -> NodeOutputTypes: ...
    @Type.setter
    def Type(self, value: NodeOutputTypes) -> None: ...
    @property
    def InitialValue(self) -> str: ...
    @InitialValue.setter
    def InitialValue(self, value: str) -> None: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    def getNodeOutputTypeFromType(type: Type) -> NodeOutputTypes: ...
    def Equals(self, obj: Object) -> bool: ...


class PortType:
    Input = 0
    Output = 1


class PortModel(ModelBase):
    def __init__(self, portType: PortType, owner: NodeModel, data: PortData): ...
    @property
    def GUID(self) -> Guid: ...
    @GUID.setter
    def GUID(self, value: Guid) -> None: ...
    @property
    def Connectors(self) -> ObservableCollection: ...
    @Connectors.setter
    def Connectors(self, value: ObservableCollection) -> None: ...
    @property
    def Name(self) -> str: ...
    @property
    def ToolTip(self) -> str: ...
    @ToolTip.setter
    def ToolTip(self, value: str) -> None: ...
    @property
    def PortType(self) -> PortType: ...
    @property
    def Owner(self) -> NodeModel: ...
    @property
    def Index(self) -> int: ...
    @property
    def LineIndex(self) -> int: ...
    @property
    def IsEnabled(self) -> bool: ...
    @IsEnabled.setter
    def IsEnabled(self, value: bool) -> None: ...
    @property
    def Center(self) -> Point2D: ...
    @property
    def UsingDefaultValue(self) -> bool: ...
    @UsingDefaultValue.setter
    def UsingDefaultValue(self, value: bool) -> None: ...
    @property
    def DefaultValue(self) -> AssociativeNode: ...
    @DefaultValue.setter
    def DefaultValue(self, value: AssociativeNode) -> None: ...
    @property
    def MarginThickness(self) -> Thickness: ...
    @property
    def extensionEdges(self) -> SnapExtensionEdges: ...
    @extensionEdges.setter
    def extensionEdges(self, value: SnapExtensionEdges) -> None: ...
    @property
    def Level(self) -> int: ...
    @Level.setter
    def Level(self, value: int) -> None: ...
    @property
    def UseLevels(self) -> bool: ...
    @UseLevels.setter
    def UseLevels(self, value: bool) -> None: ...
    @property
    def KeepListStructure(self) -> bool: ...
    @KeepListStructure.setter
    def KeepListStructure(self, value: bool) -> None: ...
    @property
    def IsConnected(self) -> bool: ...
    @overload
    def Equals(self, other: PortModel) -> bool: ...
    def GetHashCode(self) -> int: ...


class PortData:
    @overload
    def __init__(self, name: str, toolTipString: str): ...
    @overload
    def __init__(self, name: str, toolTipString: str, defaultValue: AssociativeNode): ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def ToolTipString(self) -> str: ...
    @ToolTipString.setter
    def ToolTipString(self, value: str) -> None: ...
    @property
    def DefaultValue(self) -> AssociativeNode: ...
    @DefaultValue.setter
    def DefaultValue(self, value: AssociativeNode) -> None: ...
    @property
    def LineIndex(self) -> int: ...
    @LineIndex.setter
    def LineIndex(self, value: int) -> None: ...
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> None: ...


class ScopedNodeModel(NodeModel):
    def GetInScopeNodesForInport(self, portIndex: int, checkEscape: bool, isInclusive: bool, forceToGetNodeForInport: bool) -> Iterable[NodeModel]: ...
    def BuildOutputAstInScope(self, inputAstNodes: List, verboseLogging: bool, builder: AstBuilder) -> Iterable[AssociativeNode]: ...


class TypeLoadData:
    def __init__(self, typeIn: Type): ...
    @property
    def Assembly(self) -> Assembly: ...
    @property
    def IsObsolete(self) -> bool: ...
    @property
    def Category(self) -> str: ...


class VariableInputNode(NodeModel):
    @property
    def VariableInputPorts(self) -> bool: ...


class VariableInputNodeController:
    def GetInputIndexFromModel(self) -> int: ...
    def RemoveInputFromModel(self) -> None: ...
    def AddInputToModel(self) -> None: ...
    def SetNumInputs(self, numInputs: int) -> None: ...
    def OnBuilt(self) -> None: ...
    def SerializeInputCount(nodeElement: XmlElement, amount: int) -> None: ...
    def SerializeCore(self, element: XmlElement, context: SaveContext) -> None: ...
    def DeserializeCore(self, element: XmlElement, context: SaveContext) -> None: ...


class State:
    Normal = 0
    Warning = 1
    Error = 2


class StatementType:
    #None = 0
    Expression = 1
    Literal = 2
    Collection = 3
    AssignmentVar = 4
    FuncDeclaration = 5


class Nature:
    Deprecated = 0
    Unresolved = 1
