from typing import Tuple, Set, Iterable, List


class EnumDescriptionAttribute:
    def __init__(self, resourceKey: str, resourceType: Type): ...
    @property
    def Description(self) -> str: ...


class ExtensionData:
    def __init__(self, extensionGuid: str, name: str, version: str, data: Dictionary): ...
    @property
    def ExtensionGuid(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def Version(self) -> str: ...
    @property
    def Data(self) -> Dictionary: ...
    @Data.setter
    def Data(self, value: Dictionary) -> None: ...


class ExtensionDefinition:
    def __init__(self): ...
    @property
    def AssemblyPath(self) -> str: ...
    @AssemblyPath.setter
    def AssemblyPath(self, value: str) -> None: ...
    @property
    def TypeName(self) -> str: ...
    @TypeName.setter
    def TypeName(self, value: str) -> None: ...


class ExtensionLibraryLoader:
    def LoadNodeLibrary(self, library: Assembly) -> None: ...
    def LoadPackages(self, assemblies: Iterable[Assembly]) -> None: ...


class ExtensionLoader:
    def __init__(self): ...
    def Load(self, extensionPath: str) -> IExtension: ...
    def LoadDirectory(self, extensionsPath: str) -> Iterable[IExtension]: ...
    def add_MessageLogged(self, value: Action) -> None: ...
    def remove_MessageLogged(self, value: Action) -> None: ...
    def add_ExtensionLoading(self, value: Action) -> None: ...
    def remove_ExtensionLoading(self, value: Action) -> None: ...


class IExtensionSource:
    def add_RequestLoadExtension(self, value: Func) -> None: ...
    def remove_RequestLoadExtension(self, value: Func) -> None: ...
    def add_RequestAddExtension(self, value: Action) -> None: ...
    def remove_RequestAddExtension(self, value: Action) -> None: ...
    @property
    def RequestedExtensions(self) -> Iterable[IExtension]: ...


class ExtensionManager:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, directoriesToVerify: Iterable[str]): ...
    def Add(self, extension: IExtension) -> None: ...
    def Remove(self, extension: IExtension) -> None: ...
    @property
    def Extensions(self) -> Iterable[IExtension]: ...
    @property
    def StorageAccessExtensions(self) -> Iterable[IExtensionStorageAccess]: ...
    def add_ExtensionAdded(self, value: Action) -> None: ...
    def remove_ExtensionAdded(self, value: Action) -> None: ...
    def add_ExtensionRemoved(self, value: Action) -> None: ...
    def remove_ExtensionRemoved(self, value: Action) -> None: ...
    @property
    def ExtensionLoader(self) -> IExtensionLoader: ...
    def Dispose(self) -> None: ...
    def add_MessageLogged(self, value: Action) -> None: ...
    def remove_MessageLogged(self, value: Action) -> None: ...
    def RegisterService(self, service: T) -> str: ...
    def UnregisterService(self, serviceKey: str) -> bool: ...
    def Service(self) -> T: ...
    def GetService(self, serviceType: Type) -> Object: ...


class ICommandExecutive:
    def ExecuteCommand(self, command: RecordableCommand, uniqueId: str, extensionName: str) -> None: ...


class IExtension:
    @property
    def UniqueId(self) -> str: ...
    @property
    def Name(self) -> str: ...
    def Startup(self, sp: StartupParams) -> None: ...
    def Ready(self, sp: ReadyParams) -> None: ...
    def Shutdown(self) -> None: ...


class IExtensionLoader:
    def Load(self, extensionPath: str) -> IExtension: ...
    def LoadDirectory(self, extensionsPath: str) -> Iterable[IExtension]: ...
    def add_ExtensionLoading(self, value: Action) -> None: ...
    def remove_ExtensionLoading(self, value: Action) -> None: ...


class IExtensionManager:
    def Add(self, extension: IExtension) -> None: ...
    def Remove(self, extension: IExtension) -> None: ...
    @property
    def Extensions(self) -> Iterable[IExtension]: ...
    def add_ExtensionAdded(self, value: Action) -> None: ...
    def remove_ExtensionAdded(self, value: Action) -> None: ...
    def add_ExtensionRemoved(self, value: Action) -> None: ...
    def remove_ExtensionRemoved(self, value: Action) -> None: ...
    @property
    def ExtensionLoader(self) -> IExtensionLoader: ...


class IExtensionStorageAccess:
    @property
    def UniqueId(self) -> str: ...
    @property
    def Name(self) -> str: ...
    def OnWorkspaceOpen(self, extensionData: Dictionary) -> None: ...
    def OnWorkspaceSaving(self, extensionData: Dictionary, saveContext: SaveContext) -> None: ...


class IServiceManager:
    def RegisterService(self, service: T) -> str: ...
    def UnregisterService(self, serviceKey: str) -> bool: ...
    def Service(self) -> T: ...


class LinterExtensionBase:
    @property
    def ReadyParamsRef(self) -> ReadyParams: ...
    @property
    def IsActive(self) -> bool: ...
    @property
    def UniqueId(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def LinterRules(self) -> HashSet: ...
    def AddLinterRule(self, linterRule: LinterRule) -> None: ...
    def RemoveLinterRule(self, linterRule: LinterRule) -> None: ...
    def Ready(self, sp: ReadyParams) -> None: ...
    def Startup(self, sp: StartupParams) -> None: ...
    def Shutdown(self) -> None: ...
    def Dispose(self) -> None: ...


class ReadyParams:
    @property
    def StartupParams(self) -> StartupParams: ...
    @property
    def WorkspaceModels(self) -> Iterable[IWorkspaceModel]: ...
    @property
    def CurrentWorkspaceModel(self) -> IWorkspaceModel: ...
    @property
    def CommandExecutive(self) -> ICommandExecutive: ...
    def add_NotificationRecieved(self, value: Action) -> None: ...
    def remove_NotificationRecieved(self, value: Action) -> None: ...
    def add_CurrentWorkspaceChanged(self, value: Action) -> None: ...
    def remove_CurrentWorkspaceChanged(self, value: Action) -> None: ...
    def add_CurrentWorkspaceCleared(self, value: Action) -> None: ...
    def remove_CurrentWorkspaceCleared(self, value: Action) -> None: ...
    def add_CurrentWorkspaceClearingStarted(self, value: Action) -> None: ...
    def remove_CurrentWorkspaceClearingStarted(self, value: Action) -> None: ...
    def add_CurrentWorkspaceOpened(self, value: Action) -> None: ...
    def remove_CurrentWorkspaceOpened(self, value: Action) -> None: ...
    def add_CurrentWorkspaceRemoveStarted(self, value: Action) -> None: ...
    def remove_CurrentWorkspaceRemoveStarted(self, value: Action) -> None: ...
    def Dispose(self) -> None: ...


class StartupParams:
    @property
    def AuthProvider(self) -> IAuthProvider: ...
    @property
    def Preferences(self) -> IPreferences: ...
    @property
    def PathManager(self) -> IPathManager: ...
    @property
    def LibraryLoader(self) -> ILibraryLoader: ...
    @property
    def CustomNodeManager(self) -> ICustomNodeManager: ...
    @property
    def DynamoVersion(self) -> Version: ...
    @property
    def LinterManager(self) -> LinterManager: ...
    @property
    def NoNetworkMode(self) -> bool: ...
